### ISSUE TITLE
[Question]: Gemini Blocking Answer Generation

### ISSUE THREAD

**Issue by Juliusshipton** [danielmiessler/fabric#1000]
### What is your question?

I have successfully installed and tested fabric.  I am trying to run the following command to extract wisdom from a youtube podcast. 

`fabric -y "https://youtube.com/watch?v=ajneRM-ET1Q" | fabric --stream -p extract_wisdom`

This command executes perfectly, the youtube transcript is pulled fine, and the stream is started.  However at random points during the stream (different every run), the full output will be blocked with the following message ...

> blocked: candidate: FinishReasonSafety

I asked Gemini personally what this nonsense was all about .. to which it replied 

> You're getting the "blocked: candidate: FinishReasonSafety" error when accessing me through an API because the system has identified a potential safety risk in your request. This is a common safety measure implemented to prevent harmful or inappropriate content from being generated.

Is this a Gemini preventing the answer issue?  Everything seems to be working fine with fabric.

**Comment by Juliusshipton** [comment]
That exact command is working for other youtube videos ... could this be because of the content of the video that Gemini is preventing the answer from being generated?

**Comment by Juliusshipton** [comment]
Followup question ... are other models less prone to censorship?  Working on getting other free versions up and running now.

**Comment by eugeis** [comment]
btw. you could simplify the call

`fabric -y "https://youtube.com/watch?v=ajneRM-ET1Q" --stream -p extract_wisdom`

**Comment by Juliusshipton** [comment]
`fabric -y "https://youtube.com/watch?v=ajneRM-ET1Q" --stream -p extract_wisdom`

This one prints the whole youtube transcript for me tho

**Comment by eugeis** [comment]
And then nothing happening?

**Comment by Juliusshipton** [comment]
Ya the output is partially streamed then completely stopped with the error message below ...

> blocked: candidate: FinishReasonSafety

**Comment by eugeis** [comment]
I think it is because of the content of the video. We can't do anything here.
