### ISSUE TITLE
[Feature request]: Option to include prompt or link in output file.

### ISSUE THREAD

**Issue by BKLronin** [danielmiessler/fabric#1018]
### What do you need?

Possibility to include the prompt with the link for youtube videos in the ouput file. 
Otherwise its difficult to track where the data was obtained from, which is important.

I could not find any issue or already implemented funcitons.

Merci

**Comment by eugeis** [comment]
You can a session with contains the entire conversation or a new option that I implemented in the current release

`fabric ... -o=outputfile.txt --output-prompt`

**Comment by BKLronin** [comment]
Perfect.

**Comment by BKLronin** [comment]
Just tried, it seems to correctly output the entire prompt including input. What it doesnt include is the source, in this case the youtube link. 

Alternatively the full cli command would be a good to get a quick info what has been done and on what input(exluding the input itself.)

**Comment by eugeis** [comment]
Ok, I implemented 'meta' support for session and renamed the flag to --output-session


  -o, --output=              Output to file
      --output-session       Output the entire session (also a temporary one) to the output file
