### ISSUE TITLE
[Bug]:  Post "#/messages": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by ChatCFP** [danielmiessler/fabric#1022]
### What happened?

Fresh install on WSL2 based Ubuntu platform.  Able to run `fabric --setup` command, and have entered API keys for OpenAI, Anthropic, and YouTube.  When I run the command `yt` I receive the message "Command 'yt'' not found" and when try any Fabric command I receive the message: "Messages error: Post "#/messages": unsupported protocol scheme ""
Post "#/messages": unsupported protocol scheme "" "

### Version check

- [X] Yes I was.

**Comment by ip380** [comment]
how did you fix this, i have this ollama get "localhost" unsuported protocol scheme localhost

**Comment by mameen-omar** [comment]
Getting the following error:

```
Ollama Get "localhost:11434": unsupported protocol scheme "localhost"
```
