### ISSUE TITLE
problem running poetry shell

### ISSUE THREAD

**Issue by imenigmars** [danielmiessler/fabric#103]
OS: Windows & Linux Mint
Poetry version: 1.7.1
Python 3.10

I'm having issues on both windows and linux with getting this to work.
Sorry if this is an easy fix, I've tried a few different things to make this work, including changing my OS completely.

Followed the instructions up to the point where I need to run the poetry shell.
I don't remember what was going on with my windows machine, but he's what I get with this one.
It seems like I'm getting an error related to the "cleo" package. I've upgraded poetry, injected cleo, and tried to go back and make sure I did the earlier steps properly.
Any help is greatly appreciated.
I'm not sure if I'm just missing something, or what.

When I try to run it, 
Original exception was:
Traceback (most recent call last):
  File "/usr/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/usr/lib/python3/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/lib/python3/dist-packages/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ImportError: cannot import name 'Application' from 'cleo' (/home/enigma/.local/lib/python3.10/site-packages/cleo/__init__.py)

**Comment by agu3rra** [comment]
Hello!
I've seen a video where people run into poetry issues as well. Here's the link to the official poetry install docs: https://python-poetry.org/docs/#installing-with-pipx

In my experience, unix-based systems like macOS and Linux will store pip3 installed stuff under '/Users/[YOURNAME]/.local/bin'.

Make sure you add it either to your `~/.bashrc` or `~/.zshrc` files with the extra line at the bottom `export PATH=/Users/[YOURNAME]/.local/bin:$PATH` (replace YOURNAME). Then close the terminal window and open a new one for it to kick in.

Alternatively you can try to re-install poetry via the command they provide:
```bash
curl -sSL https://install.python-poetry.org | python3 -
```

**Comment by danielmiessler** [comment]
Thanks Andre for that. Yes, that should solve it for now, and after we do the next update this won't be necessary either.

**Comment by agu3rra** [comment]
> Thanks Andre for that. Yes, that should solve it for now, and after we do the next update this won't be necessary either.

Hey @danielmiessler 
Full disclosure: the next update on #88 doesn't actually change how people install `poetry`. It requires a working version of poetry in a machine in order for the corresponding bash script to then automatically add aliases to either `.bashrc` or `zshrc`. I suppose a next step will be to create an equivalent script in PowerShell for Windows users.
