### ISSUE TITLE
[Bug]: Pbpaste piping still not working correctly on 1.4.54.

### ISSUE THREAD

**Issue by ythefly** [danielmiessler/fabric#1031]
### What happened?

When I run pbpaste | fabric -s -p extract_wisdom or any other patterns it comes with an empty response error.  I have alias setup like this: alias extractwisdom='echo "$(pbpaste)" | fabric -s -p extract_wisdom' and it works fine. Can you please fix it. Thanks. 

### Version check

- [X] Yes I was.

### Relevant log output

```shell
empty response
```

**Comment by ythefly** [comment]
it happens if it's a url to an article or website.

**Comment by eugeis** [comment]
Please provide an full example.

Backround: 
pbpaste puts the clipboard content to te console. The pipe |  forward it to fabric as last parameter. The last parameter is considered as usser message which is send to the model.

**Comment by ythefly** [comment]
so i copied the url: https://github.com/danielmiessler/fabric?tab=readme-ov-file#updates. and I do a command of pbpaste | fabric -s -p extract_wisdom. It will come up with a response: empty response.  However if i use the raycast extract wisdom extension the script will give me a summary of the website just like it should. This happens with all the urls that has an article or website. I also just downloaded the 1.4.55 and this still did not fix the problem.

**Comment by eugeis** [comment]
If you just copied the url, it does not contain much information,  just the url.
You could use -u <url> to get the content of the url.

**Comment by ythefly** [comment]
so that means that pbpaste piping with URL no longer works as expected prior to the 1.4.0 releases? I believed it still worked till 1.4.0 and after that it stopped working since 1.4.4

**Comment by andrewjohnharvey** [comment]
I am also running into this problem with pbpaste. If run `echo "paste text here" | fabric --pattern summarize` then it will work but just running `pbpaste | fabric --pattern summarize` I get an empty response. If I run `pbpasete | fabric --pattern summarize > output.log`

**Comment by eugeis** [comment]
> so that means that pbpaste piping with URL no longer works as expected prior to the 1.4.0 releases? I believed it still worked till 1.4.0 and after that it stopped working since 1.4.4

I don't think so. There was no changes in fabric about pipes, ot is just a OS features.

In general, it is not about fabric, but about pbpaste. To my knowledge pbpaste was not able to grab content of an url automatically. Just use -u feature if you need to grab content of a web page or curl.

**Comment by eugeis** [comment]
> I am also running into this problem with pbpaste. If run `echo "paste text here" | fabric --pattern summarize` then it will work but just running `pbpaste | fabric --pattern summarize` I get an empty response. If I run `pbpasete | fabric --pattern summarize > output.log`

Please check if pbpaste is working properly. We are not maintaining pbpaste command.

**Comment by andrewjohnharvey** [comment]
Confirming pbpaste works correctly

**Comment by eugeis** [comment]
Do you still have the issue?

I just tested it on my system and it works as expected

❯ pbpaste | fabric -p ai
- The iPhone's 2007 release revolutionized the smartphone industry.
- Initial skepticism gave way to massive consumer interest and market dominance.
- Rapid early innovation included Retina display, Siri, and Apple Pay.
- Innovation pace has slowed; incremental improvements now common.
- Environmental and ethical concerns challenge the tech industry's sustainability.

**Comment by ythefly** [comment]
> Do you still have the issue?
> 
> I just tested it on my system and it works as expected
> 
> ❯ pbpaste | fabric -p ai
> 
> * The iPhone's 2007 release revolutionized the smartphone industry.
> * Initial skepticism gave way to massive consumer interest and market dominance.
> * Rapid early innovation included Retina display, Siri, and Apple Pay.
> * Innovation pace has slowed; incremental improvements now common.
> * Environmental and ethical concerns challenge the tech industry's sustainability.

Hi Eugeis,
I'm still having the problem. If i do it on a terminal with pbpaste | fabric -s -p extract_wisdom I get the "empty response" comment.  I also tried pbpaste | fabric -s -p extract_wisdom > abcd.txt and inside the text file i get the "empty response".  But what is funny is that I run the raycast script of extract wisdom with the url and it gives me the results perfectly.  I also have an alias setup like this in the .zshrc file: alias extractwisdom='echo "$(pbpaste)" | fabric -s -p extract_wisdom' and in the terminal i just run extractwisdom and it works fine.  Or now i would have to use "fabric -u $(pbpaste) -s -p extract_wisdom" which would work as well.  So in the end with pbpaste | fabric -p ai or extract_wisdom or any pattern after that just doesn't work anymore like it used to.
