### ISSUE TITLE
[Question]: How does one use the `-v=`/`--variable=` option?

### ISSUE THREAD

**Issue by erhhung** [danielmiessler/fabric#1035]
### What is your question?

After reading the documentation, I am still not clear how to use the `-v=`/`--variable=` option. According to the README and `fabric -h` help descriptions, the option can be specified like `-v=$name:John -v=$age:30`, but I don't see in pattern markup files "variable substitutions" using the _`$variable`_ convention.

Besides, specifying literally `-v=$name:John -v=$age:30` without any quotes or backslashes will likely yield `fabric -v=:John -v=:30` passed by the shell.

Would appreciate an example of an existing pattern that uses variables, and fixing the help description to include single quotes (`-v='$name:John'`) or backslashes (`\$name:John`).

**Comment by eugeis** [comment]
Yes, you are right the example description is misleading.
We need to change it to something that is not evaluated in the batch, e.g. #name:John ...

The functionality is just a simple relpaceAll, the variable names are search and replaced in the pattern.

**Comment by nnWhisperer** [comment]
So, I guess there is no "{VARIABLE_NAME}" in the patterns, unlike langchain for example.
