### ISSUE TITLE
Idea - Developer Volunteer Pipeline

### ISSUE THREAD

**Issue by profetik-777** [danielmiessler/fabric#104]
As per feedback from Daniel ( https://github.com/danielmiessler/fabric/issues/38#issuecomment-1928513674 ) , pitching an idea for potential area of contribution. 

GOAL: 

Help create a simple and easy to manage developer volunteer pipeline so Daniel has a decent volunteer "roster" to lean on to solve small to mid-level issues (or feature enhancements). 

Details: 

1. Use a website asset (or online form) that Daniel can share from time to time (or put against ads on social media) with a "Call for Volunteers" that quickly and easily outlines the following: 

- preferred languages
- areas of need
- commitment level
- contact info (in case there isn't an immediate need- but you  want to reach out to them later). 

This way - Daniel can manage expectations of those who fill out the form, while also quickly size up basic info about their background.  You can even feature in the form - an example of a great contribution/ pull request so users can align their expectations to what you need. 

What is needed: 

1. A place to submit sample form questions (so Daniel can finalize/approve). Do this in a pull request? Or just send a you a doc? 
2. Have Daniel list out preferred/ideal languages/experience that would be a good fit. 
3. A sample pull request he likes so it can be featured in the form
4. BONUS/ STRETCH GOAL: Attach this form (or link if the form lives in your website) to a BOT in your chats in discord or wherever your community lives, and have it get shared 1/month or whatever frequency. This way - you don't have to think about "recruiting" contributors. It does it for you.....
5. Bonus Bonus ;) You could experiment with running a small targeted add, to really see where recruiting volunteers can take you. I have some digital marketing experience that can assist with that - but that might be overkill. But maybe not, if you are interested in building a solid core team that you can actually trust.

**Comment by danielmiessler** [comment]
Love this. Let's bring it over to the discussions area of the project.
