### ISSUE TITLE
[Bug]: Ollama configured, not showing models

### ISSUE THREAD

**Issue by kennyparsons** [danielmiessler/fabric#1040]
## Description:
Fabric is configured to use Ollama as a model vendor, but it only lists models from OpenAI. Attempts to access models from Ollama result in errors stating the model is not found.

## Steps to Reproduce:
1. Configure Fabric to use Ollama:
    - Command: `fabric --setup-vendor Ollama`
    - URL: `http://localhost:11434`
2. Verify Ollama is running:
    - Command: `curl localhost:11434` (Output: Ollama is running)
3. List available models:
    - Command: `fabric -L`

## Expected Behavior:
Fabric should list and allow the use of models from Ollama.

## Actual Behavior:
Fabric only lists models from OpenAI. No models from Ollama are displayed.

## Configuration Details 
* Note: this is even after configuring fabric for ollama
- `.env` File:
    ```bash
    DEFAULT_VENDOR=OpenAI
    DEFAULT_MODEL=gpt-4o-mini
    PATTERNS_LOADER_GIT_REPO_URL=https://github.com/danielmiessler/fabric.git
    OPENAI_API_KEY=redacted
    OPENAI_API_BASE_URL=https://api.openai.com/v1
    JINA_AI_API_KEY=redacted
    ```

## Commands & Outputs:
1. **Setup Vendor:**
    ```bash
    ❯ fabric --setup-vendor Ollama
    http://localhost:11434
    ```
2. **Check Ollama Running:**
    ```bash
    ❯ curl localhost:11434
    Ollama is running
    ```
3. **List Models:**
    ```bash
    ❯ fabric -L
    Available vendor models:

    OpenAI
    [list of OpenAI models]
    ```

## Environment:
- Fabric version: v1.4.54
- Ollama version: 0.3.12
- OS: darwin-arm

### Version check

- [X] Yes I was.

**Comment by eugeis** [comment]
Hmm, strange, 
I will try to reproduce it.

**Comment by eugeis** [comment]
Ok, sorry, I was concentrating to issue title.

**Comment by helenagpt** [comment]
Hello, I have an issue that seems connected to this one.

When I setup Fabric, I insert the url to Ollama and it says:
Enter your Ollama URL (as a reminder, it is usually http://localhost:11434) (leave empty to skip):
http://localhost:11434
[Ollama] configured

But at the end it says this: 
Ollama Get "https://localhost:11434/api/tags": http: server gave HTTP response to HTTPS client

Available vendor models:

[Default]

Enter the index the name of your default model (leave empty to skip):
1
You need to chose an available default model.

I have two models installed and they are not listed and I can't choose the default one.
Any suggestions/help? Thanks in advance!

**Comment by eugeis** [comment]
No it i s a different issue, 
It seems your Ollama server is not available at http://localhost:11434/

Just check with curl or a browser and you should get, Ollama is running:

❯ curl http://localhost:11434
Ollama is running

**Comment by helenagpt** [comment]
I did and it's running. That's why I dont understand why fabric doesn't see it.

**Comment by eugeis** [comment]
hmm, I see https instead of http in your output, please run setup again and check if "http://localhost:11434" or "https//localhost:11434" is configured

**Comment by helenagpt** [comment]
in setup if I insert https://localhost:11434, it replies Ollama configured as well. But then, I get the same result.

with curl  http://localhost:11434/
ollama is running

with curl https://localhost:11434/
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid

**Comment by eugeis** [comment]
then insert http://localhost:11434

**Comment by helenagpt** [comment]
I did, but it returns the same message at fabric setup. no models are recognised. 
And I have these installed:

 ollama list
NAME               ID              SIZE      MODIFIED
llama2:latest      78e26419b446    3.8 GB    11 hours ago
llama3.2:latest    a80c4f17acd5    2.0 GB    12 hours ago
phi3.5:latest      61819fb370a3    2.2 GB    12 hours ago

**Comment by eugeis** [comment]
Hi, 
there was a bug in setup functionality, 
please update fabric to https://github.com/danielmiessler/fabric/releases/tag/v1.4.68 release, do 
`fabric --setup`
, use 
`http://localhost:11434`
as Ollama URL and try again.

**Comment by helenagpt** [comment]
Thanks for your help @eugeis 
It finally works!  👍 :) :) :)

**Comment by cipolino85** [comment]
i have installed fabric version v1.4.130 and i made to work with openAI but because it si not free I wan to use it with ollama. Can you tell me how to configure it . I don't see the ollama models and the fabric is stucked to OpenAI vendor. I cannot see the ollama models. The ollama si running. Ollama is installled for windows.
