### ISSUE TITLE
[Question]: Model hosting

### ISSUE THREAD

**Issue by phifuh** [danielmiessler/fabric#1041]
### What is your question?

If i host my own model, would it be possible to setup a `--host` / `--endpoint` or something similiar option? The usecase is pretty simple, co-workers dont need to setup the model locally.

In my case i was  considering doing an endpoint with FastAPI/Flask to acces the model

**Comment by danielmiessler** [comment]
Yes, you can use it with Ollama and set your Ollama URL using --setup.
