### ISSUE TITLE
Issue running poetry in macos

### ISSUE THREAD

**Issue by prbreezy** [danielmiessler/fabric#105]
Hi I'm facing the below issue (See log output part)

macos config:
- System Version: macOS 14.1.1 (23B81)
- Secure Virtual Memory: Enabled
- Memory: 16 GB

Python:
- Python 3.12.1

pip list | grep fabric return : 

Package            Version  Editable project location
#########################################
fabric             0.1.0    /Users/xxxx/Documents/git/fabric/fabric/client

See log output part
---------------
_(fabric-py3.12) (base) XXXX@XXXX % poetry shell                                                                                       
The currently activated Python version 3.9.2 is not supported by the project (^3.10).
Trying to find and use a compatible version. 
Using python3 (3.12.1)
Virtual environment already activated: /Users/xxx/Library/Caches/pypoetry/virtualenvs/fabric-MBJlZ2wn-py3.12
(fabric-py3.12) (base) XXXX@XXXX  % fabric -h   
Traceback (most recent call last):
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/fabric-MBJlZ2wn-py3.12/bin/fabric", line 3, in <module>
    from fabric import main
  File "/Users/xxx/Documents/git/fabric/fabric/client/fabric/__init__.py", line 1, in <module>
    from .fabric import main
  File "/Users/xxx/Documents/git/fabric/fabric/client/fabric/fabric.py", line 1, in <module>
    from utils import Standalone, Update, Setup
ModuleNotFoundError: No module named 'utils'
(fabric-py3.12) (base) XXXX@XXXX  %_ 
-----------------

**Comment by danielmiessler** [comment]
This will be solved with a PR being implemented very soon! Thank you!
