### ISSUE TITLE
[Feature request]: Clipboard instructions for Windows and Linux

### ISSUE THREAD

**Issue by rprouse** [danielmiessler/fabric#1063]
### What do you need?

The examples all use the Mac `pbpaste`. I suggest adding a short section to the `Readme.md` explaining the alternatives for Windows and Mac so that users don't have to search for the information.

I will submit a PR. Feel free to reject if it isn't what you want. No hard feelings.

**Comment by shpati** [comment]
@rprouse , I made pbcopy and pbpaste programs in c using the windows API that has the same functionality as on the the Mac. Maybe windows users can be pointed to the github repository to obtain the binaries: [](https://github.com/shpati/pbcopy_pbpaste_win)
