### ISSUE TITLE
[Question]: How to Pass Additional Questions with YouTube Transcript / Any Text in Command?

### ISSUE THREAD

**Issue by phj6688** [danielmiessler/fabric#1066]
### What is your question?

Is there a way to pass one or more questions along with the YouTube transcript using the yt --transcript command? For example, I’d like to append a question like "is X mentioned in this video?" to the transcript output and pipe it into fabric.

How can this be done? Could you provide guidance or implement support for combining the transcript with custom questions in the output?
I believe it should be feasible with "ai" pattern but don't know how!
Thanks!

**Comment by eugeis** [comment]
You can use all features of fabric in addition to YouTube support, e.g.

- fabric -y "youtube video url" -p <pattern name>
- fabric -y "youtube video url" "your question"

**Comment by phj6688** [comment]
> You can use all features of fabric in addition to YouTube support, e.g.
> 
> * fabric -y "youtube video url" -p
> * fabric -y "youtube video url" "your question"

I tried the command but its not supported like that. "unrecognized arguments"
could you please check it yourself?

**Comment by eugeis** [comment]
❯ fabric -y "https://www.youtube.com/watch?v=ozyFiFzQPe8" -p extract_wisdom
# SUMMARY
The speaker discusses recent upgrades to the AER tool, including improved file handling, new config file syntax, and enhancements in architect mode.

# IDEAS:
- AER now supports shell-style autocomplete for the full file system in the readon option.
- You can add files outside of the current repo to readon in AER.
- AER supports globs to prevent writing to entire directories or specific file types.
- The yes operator in AER has been renamed to yes always for automatic approvals.
- Config files in AER now support standard YAML list syntax for easier item listing.
- AER performs sanity checks on the editor model at launch for improved reliability.
- Skip sanity check option for large repos speeds up AER usage.
- Architect mode in AER now handles control C properly for better user experience.
- Repo map in AER is now deterministic with improved caching logic.
- Improved commit message prompts in AER for better commit messages.
- Full support for Sonnet added in AER for enhanced functionality.
- AER better formats added and read-only files above the chat prompt.
- Improved parsing of non-conforming code edit replies for 01 models.
- A new corrected diff edit format prompt replaces only the first match.
- Stronger whole edit format prompt asks for clean file names.
- AER offers to add EnV files to G ignore to avoid API key leaks.
- Small model metadata JSON file ships with AER for handling not yet updated models.
- Model settings for 01 models on Azure have been added to AER.
- Minor release added image support for new Sonnet in AER.
- AER config file setup can specify architect and editor models for better performance.
- Basic prompt chaining or Chain of Thought can significantly improve free API performance.
- Prompt chaining can create better landing pages using architect mode in AER.
- AER allows defining multiple files or values in config files using lists.
- Yes always option in AER config files replaces the yes option for automatic approvals.
- Adding prompt files in AER config can guide models to think step-by-step.
- Improved results with free tools like Mistral API using prompt chaining in AER.
- Users can donate or become members to support the speaker's channel.

# INSIGHTS:
- Shell-style autocomplete in AER's readon option enhances file referencing efficiency.
- The addition of globs in AER prevents unwanted file modifications in bulk.
- Skip sanity checks for large repos significantly improves AER performance.
- Improved commit message prompts enhance code management practices in AER.
- Prompt chaining in AER leads to significantly better results with free APIs.
- Config files in AER now support easier and more readable list syntax.
- Architect mode's new handling of control C improves the user experience.
- Deterministic repo maps with improved caching logic boost AER's reliability.
- Adding EnV files to G ignore in AER prevents accidental API key leaks.
- Improved parsing of 01 models' non-conforming code boosts code reliability in AER.

# QUOTES:
- "AER now supports shell-style autocomplete for the full file system in the readon option."
- "The yes operator has also been renamed to yes always."
- "Config files in AER now support standard YAML list syntax."
- "Skip sanity check for large repos speeds up AER usage."
- "Repo map is now deterministic with improved caching logic."
- "Improved commit message prompts in AER for better commit messages."
- "Full support for Sonnet added in AER for enhanced functionality."
- "A new corrected diff edit format prompt replaces only the first match."
- "AER offers to add EnV files to G ignore to avoid API key leaks."
- "Model settings for 01 models on Azure have been added to AER."
- "Prompt chaining can create better landing pages using architect mode in AER."
- "Adding prompt files in AER config can guide models to think step-by-step."
- "Improved results with free tools like Mistral API using prompt chaining in AER."
- "Users can donate or become members to support the speaker's channel."
- "Improved formatting of added and read-only files above the chat prompt."

# HABITS:
- Upgrade AER installation using pip install upgrade.
- Use readon operator for full file system autocomplete suggestions.
- Add files to readon with wild card characters.
- Define similar items in AER config YAML file.
- Use lists in the AER config file for defining multiple values.
- Set architect mode to true in the AER config file.
- Create and use a basic prompt file for step-by-step guidance.
- Experiment with prompt chaining to improve API performance.
- Change yes option to yes always in AER config files.
- Add EnV files to G ignore to prevent API key leaks.
- Specify architect and editor models in AER config for better performance.
- Use prompt chaining to create better landing pages.
- Use skip sanity check for large repos to speed up AER.
- Enable deterministic repo maps with improved caching logic.
- Incorporate improved commit message prompts for better code management.

# FACTS:
- AER now supports shell-style autocomplete for the entire file system.
- Globs in AER can prevent writing to entire directories or specific file types.
- The yes operator in AER has been renamed to yes always.
- Config files in AER now support standard YAML list syntax.
- AER performs sanity checks on the editor model at launch.
- Skip sanity check option for large repos speeds up AER usage.
- Architect mode in AER now handles control C properly.
- Repo map in AER is now deterministic with improved caching logic.
- Improved commit message prompts in AER for better commit messages.
- Full support for Sonnet added in AER for enhanced functionality.
- AER better formats added and read-only files above the chat prompt.
- Improved parsing of non-conforming code edit replies for 01 models.
- A new corrected diff edit format prompt replaces only the first match.
- Stronger whole edit format prompt asks for clean file names.
- AER offers to add EnV files to G ignore to avoid API key leaks.
- Small model metadata JSON file ships with AER for handling not yet updated models.
- Model settings for 01 models on Azure have been added to AER.
- Minor release added image support for new Sonnet in AER.
- Basic prompt chaining can significantly improve free API performance.
- Users can donate or become members to support the speaker's channel.

# REFERENCES:
- Mistral API
- Cod strol model
- CLAE 3.5 Sonet
- Azure
- G ignore file
- YAML

# ONE-SENTENCE TAKEAWAY
Recent AER updates enhance file handling, config syntax, and architect mode, significantly improving usability and performance.

# RECOMMENDATIONS:
- Use readon operator for full file system autocomplete suggestions.
- Add files to readon with wild card characters.
- Define similar items in AER config YAML file.
- Use lists in the AER config file for defining multiple values.
- Set architect mode to true in the AER config file.
- Create and use a basic prompt file for step-by-step guidance.
- Experiment with prompt chaining to improve API performance.
- Change yes option to yes always in AER config files.
- Add EnV files to G ignore to prevent API key leaks.
- Specify architect and editor models in AER config for better performance.
- Use prompt chaining to create better landing pages.
- Use skip sanity check for large repos to speed up AER.
- Enable deterministic repo maps with improved caching logic.
- Incorporate improved commit message prompts for better code management.
- Upgrade AER installation using pip install upgrade.
- Reference something from outside the project directory with readon.
- Add multiple files or values in config files using lists.
- Ensure yes always is used for automatic approvals in AER.
- Guide models to think step-by-step using prompt files in AER.
- Achieve better results with free tools using prompt chaining.

**Comment by phj6688** [comment]
hank you for your help! The issue was that Fabric was not updated on my computer and didn’t support the -y option. I updated Fabric, and now it works seamlessly.
