### ISSUE TITLE
raycast bash script

### ISSUE THREAD

**Issue by lexilexikon** [danielmiessler/fabric#1075]
### Discussed in https://github.com/danielmiessler/fabric/discussions/1032

<div type='discussions-op-text'>

<sup>Originally posted by **lexilexikon** October  7, 2024</sup>
I've installed fabric and tried to use the Raycast script command to get the transcript of a YouTube video. The bash script is breaking and it keeps saying 'invalid YouTube URL, can't get video ID'. That was the URL I retrieved: https://youtu.be/7Inkwc23U1M. I've also installed a YouTube API.
I don't have this issue using the terminal instead of Raycast.

Can anyone help me figure out what's going wrong?"</div>

**Comment by polyglotdev** [comment]
Hey @lexilexikon! I was able to to get the following script to work in Raycast:

```bash
#!/bin/zsh

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Fabric YouTube Summary Generation
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖
# @raycast.argument1 { "type": "text", "placeholder": "YouTube URL" }
# @raycast.packageName fabric-aliased-commands

# Documentation:
# @raycast.description Using fabric to generate YouTube Video summary
# @raycast.author dom_hallan
# @raycast.authorURL https://raycast.com/dom_hallan

# Source zsh configuration to get access to your PATH and aliases
source ~/.zshrc

# Validate input
if [ -z "$1" ]; then
    echo "Error: Please provide a YouTube URL"
    exit 1
fi

# Set Obsidian vault path
obsidian_base="/Users/domhallan/domhallan-obsidian-notes/notes/"

# Generate timestamp and filename
date_stamp=$(date +'%Y-%m-%d')
video_id=$(echo "$1" | grep -o '[^/]*$')
output_file="${obsidian_base}${date_stamp}-youtube-summary-${video_id}.md"

# Execute the command and save output
echo "# YouTube Summary: $1" > "$output_file"
echo "Date: $date_stamp" >> "$output_file"
echo "URL: $1" >> "$output_file"
echo "\n---\n" >> "$output_file"

# Debug: First get the transcript and save it
echo "Fetching transcript..."
transcript=$(fabric -y "$1" --transcript)
echo "Transcript length: ${#transcript}"

if [ -n "$transcript" ]; then
    echo "Processing transcript with fabric..."
    echo "$transcript" | fabric -sp extract_wisdom | tee -a "$output_file"
else
    echo "Error: No transcript was fetched" | tee -a "$output_file"
fi

echo "\nSummary saved to: $output_file"
```

## Few note worthy things

1. I changed the shebang to `zsh`, and then sourced my `~/.zshrc` file in the script just in case I was missing something not included in my `~/.bashrc`
2. I will attach the bits I added to my `~/.zshrc` file to get the output to push to Obsidian vault.

### Obsidian bits in my `~/.zshrc` file

```bash
# fabric
# Define the base directory for Obsidian notes
obsidian_base="/Users/domhallan/domhallan-obsidian-notes/notes/"

# Loop through all files in the ~/.config/fabric/patterns directory
for pattern_file in ~/.config/fabric/patterns/*; do
    # Get the base name of the file (i.e., remove the directory path)
    pattern_name=$(basename "$pattern_file")

    # Unalias any existing alias with the same name
    unalias "$pattern_name" 2>/dev/null

    # Define a function dynamically for each pattern
    eval "
    $pattern_name() {
        local title=\$1
        local date_stamp=\$(date +'%Y-%m-%d')
        local output_path=\"\$obsidian_base/\${date_stamp}-\${title}.md\"

        # Check if a title was provided
        if [ -n \"\$title\" ]; then
            # If a title is provided, use the output path
            fabric --pattern \"$pattern_name\" -o \"\$output_path\"
        else
            # If no title is provided, use --stream
            fabric --pattern \"$pattern_name\" --stream
        fi
    }
    "
done

yt() {
    local video_link="$1"
    fabric -y "$video_link" --transcript
}
```

![2024-11-08-youtube-summary-nTQIYWgn-lQ - notes - Obsidian v1 7 5 2024-11-08 at 1 19 35 PM](https://github.com/user-attachments/assets/dc5774d3-d800-4928-ac01-bc4a8f5b03c9)


I hope this is helpful!

**Comment by polyglotdev** [comment]
@lexilexikon did this answer your question?

**Comment by lexilexikon** [comment]
Hi @polyglotdev Thank you for your help! Unfortunately I'm still not able to get it running. Im using the script which is in the github repository. But I'm always getting the error message 'invalid YouTube URL, can't get video ID'. When I'm working with the terminal on my mac it works like a charm.

`#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Get YouTube Transcript
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🧠
# @raycast.argument1 { "type": "text", "placeholder": "Input text", "optional": false, "percentEncoded": true}

# Documentation:
# @raycast.description Run fabric -y on the input text of a YouTube video to get the transcript from.
# @raycast.author Daniel Miessler
# @raycast.authorURL https://github.com/danielmiessler

# Set PATH to include common locations and $HOME/go/bin
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/go/bin:$PATH"

# Use the PATH to find and execute fabric
if command -v fabric >/dev/null 2>&1; then
    fabric -y "${1}"
else
    echo "Error: fabric command not found in PATH"
    echo "Current PATH: $PATH"
    exit 1
fi`

I'm new to coding, so I hardly understand what the bash script is doing.

**Comment by lexilexikon** [comment]
I tried different ways. Right-click on the youtube video and clicking on the "copy video-url". I also tried to fetch it from the browser window (search bar). I know that the "www.yout.be..." URL seams to be problematic.

**Comment by lexilexikon** [comment]
You have to chance the argument to:

# @raycast.argument1 { "type": "text", "placeholder": "Input text", "optional": false, "percentEncoded": false}

**Comment by rube-de** [comment]
you should have made an PR instead of just closing it ;)
