### ISSUE TITLE
[Bug]: pawel@Pawels-MacBook-Pro-2 ~ % go install github.com/danielmiessler/fabric/to_pdf@latest go: github.com/danielmiessler/fabric/to_pdf@latest: module github.com/danielmiessler/fabric@latest found (v1.4.88), but does not contain package github.com/danielmiessler/fabric/to_pdf

### ISSUE THREAD

**Issue by pawsaw** [danielmiessler/fabric#1103]
### What happened?

pawel@Pawels-MacBook-Pro-2 ~ % go install github.com/danielmiessler/fabric/to_pdf@latest
go: github.com/danielmiessler/fabric/to_pdf@latest: module github.com/danielmiessler/fabric@latest found (v1.4.88), but does not contain package github.com/danielmiessler/fabric/to_pdf

### Version check

- [X] Yes I was.

**Comment by eugeis** [comment]
Readme updated,

please use

`go install github.com/danielmiessler/fabric/plugins/tools/to_pdf@latest`
