### ISSUE TITLE
[Question]: Xclip / Pbpaste Not Working

### ISSUE THREAD

**Issue by FastWReX** [danielmiessler/fabric#1113]
### What is your question?

After reading the documentation, I am still not clear how to get the PBPaste function working. The end goal is to be able to copy and paste large amounts of text and use the summarization / extract_wisdom patterns.

I have done...

1) sudo apt update && sudo apt install xclip -y

2) sudo nano ~/.bashrc

- Pasted "alias pbpaste='xclip -selection clipboard -o'" in I believe the correct section.

- There is a mention of adding this stuff to "~/.bash_aliases" in the regular ~/.bashrc file, but I'm not 100% sure what the difference is or if adding it there would make it work.

3) source ~/.bashrc

4) Exit SSH session

5) Exit Terminal app (aka Warp)

6) Relaunched Warp and reconnected via SSH

Desktop: 2019 iMac (3.6 GHz Quad-Core Intel Core i3) running macOS Sequoia 15.1 and it's the "main" computer I use.

Raspberry Pi 5: Running only Fabric and Ollama (128 Gb microSD card) connected via eth0. No other config files on Raspberry Pi OS (64-bit Headless) have been tampered or altered to my knowledge.

<img width="769" alt="Screenshot 2024-11-05 at 4 54 26 PM" src="https://github.com/user-attachments/assets/864b21b7-17ac-4e46-89f2-5c4b626acaf4">

**Comment by cdavidb82** [comment]
I'm having somewhat the same issue, other than I'm 'xsel' in Linux.  It seems like the augmentation pattern isn't getting the correct paste from the clipboard, because the AI is reporting from a totally different topic. 

![Screenshot from 2024-11-08 20-55-32](https://github.com/user-attachments/assets/c1a7ae68-64be-4980-a69f-f93c483819d5)

**Comment by FastWReX** [comment]
Got it working! Thank you!

Please close thread if needed.
