### ISSUE TITLE
[Bug]: Binary installation duplicated for ARM

### ISSUE THREAD

**Issue by jmbenedetto** [danielmiessler/fabric#1128]
### What happened?

I was looking for the instalation guide on readme and saw that the ARM line is duplicated for both MacOS and Linux.

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/feb2b073-b20d-4818-80b3-7d89820fa075">

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/502b8628-cae0-4b6d-b235-08d43fd508c8">

**Comment by mrtnrdl** [comment]
I'm pretty sure you're mistaken - The lines you are referring to are `-arm64` and `-amd64`. There are no duplicate lines in this section. 

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/5e189589-e445-41d7-8776-aec3cca00d7f">

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/cfc82627-2e06-4e9c-8cd4-b9714c233b2f">

**Comment by jmbenedetto** [comment]
Sorry, Martin!
