### ISSUE TITLE
[Question]: After setting up fabric with my openai gpt api key it looks like the model is still trying to use a differnet api key ending with "92xm". Are there setup instructions I can follow to run my own client/server/mill functions with my own api keys?

### ISSUE THREAD

**Issue by 0xsalt** [danielmiessler/fabric#113]
### What is your question?

After reading the documentation, I am still not clear how to get my own fabric Mill ecosystem setup. After running `$ fabric --setup` and entering my personal api key and downloading current patterns I am unable to successfully run any patterns. This is an example of trying one particular pattern: 
`$ echo "This is  brokentext text, ." | fabric --stream --pattern clean_text`

I get the following error: 
`Error: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-a9HhR***************************************92xm. You can find your API k
ey at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-a9HhR***************************************92xm. You can find your API key at h
ttps://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

This is not my api key and I do have a valid subscription.

Here are some of my system specs in case this helps: 
`$ cat /var/log/installer/media-info ; echo $XDG_CURRENT_DESKTOP ; echo ; lsb_release -a ; echo ; uname -r ; echo ; pyt
hon --version ; echo ; poetry --version`

Ubuntu-Server 22.04.3 LTS "Jammy Jellyfish" - Release amd64 (20230810)

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

5.15.0-94-generic

Python 3.10.12

Poetry (version 1.7.1)

I know it is early on in the project and I'm thrilled you've chosen to release it! I am happy to contribute patterns & documentation. I just can't figure out getting to the successful starting point yet! 

Thank you kindly -- @0xsalt.

**Comment by xssdoctor** [comment]
That error message suggests that you entered your api key incorrectly. Run —setup again and re enter or go into ~/config/fabric/.env and edit the api key there. If it is correct, there is a chance that you don’t have enough credits for gpt-turbo, which this project uses. In that case, Add credits to your openai account.

**Comment by 0xsalt** [comment]
Thank you for such a quick response. Apparently continuing to code past 3am gets blurry. 

This was in fact an incorrect api key issue in my config.  

After running `$ fabric --setup` I did need to manually enter my api key into `~/.config/fabric/.env` however that is not this issue and if that persists for me I'll dive into that troubleshooting separately. 

Thank you. Brilliant project, all -- @0xsalt

**Comment by aa-ahmed-aa** [comment]
after a fresh install i can still get the same issue wondering if someone had the same one as this 
<img width="1184" alt="Screenshot 2024-03-14 at 8 19 21 AM" src="https://github.com/danielmiessler/fabric/assets/9592546/ab53ba45-de77-4f5f-94e7-e1f62131de61">

**Comment by 0xsalt** [comment]
IIRC I deployed on Ubuntu 22.04 LTS server and I found that I had to manually set my API key env variable as well as edit it into another file. I think was in my profile .config dir for Fabric. I destroyed the vm and haven't rebuilt it yet or I'd give the specifics.
