### ISSUE TITLE
[Bug]: Antropic fail conection 404

### ISSUE THREAD

**Issue by OscarMauricio666** [danielmiessler/fabric#1140]
### What happened?

I have an Anthropic token, I made the connection and every time I ask a question it throws a 404 error, I think the API has changed, I appreciate your help, it's a fantastic tool

### Version check

- [X] Yes I was.

### Relevant log output

```shell
Messages stream error, type: not_found_error, message: Not Founderror, status code: 404, message: anthropic api error type: not_found_error, message: Not Found
```

**Comment by eugeis** [comment]
Ok, I can reproduce it and will check it out.

**Comment by eugeis** [comment]
Please check out the latest release
