### ISSUE TITLE
[Question]: Should running a pattern with a YouTube playlist URL run the pattern against each video?

### ISSUE THREAD

**Issue by jreina** [danielmiessler/fabric#1153]
### What is your question?

I'm not quite sure how to run a pattern like `extract_wisdom` against each video in a playlist with fabric alone. When I run `fabric -y <playlist_url> -p extract_wisdom -o playlist_title.md`, I just get a CSV of the titles and URLs. For now, I've just written a little wrapper to loop over the CSV but I'm wondering what the intended behavior is here and if perhaps I just missed the documentation.

**Comment by eugeis** [comment]
Currently, you can save the transcript of each video in a playlist as separate files. If a pattern, session, or context is defined, all transcripts are combined into a single message and sent to the AI vendor.

You are welcome to provide a PR with extended impl.

Here is the code:

`if currentFlags.YouTube != "" {
		if registry.YouTube.IsConfigured() == false {
			err = fmt.Errorf("YouTube is not configured, please run the setup procedure")
			return
		}

		var videoId string
		var playlistId string
		if videoId, playlistId, err = registry.YouTube.GetVideoOrPlaylistId(currentFlags.YouTube); err != nil {
			return
		} else if (videoId == "" || currentFlags.YouTubePlaylist) && playlistId != "" {
			if currentFlags.Output != "" {
				err = registry.YouTube.FetchAndSavePlaylist(playlistId, currentFlags.Output)
			} else {
				var videos []*youtube.VideoMeta
				if videos, err = registry.YouTube.FetchPlaylistVideos(playlistId); err != nil {
					err = fmt.Errorf("error fetching playlist videos: %v", err)
					return
				}

				for _, video := range videos {
					var message string
					if message, err = processYoutubeVideo(currentFlags, registry, video.Id); err != nil {
						return
					}

					if !currentFlags.IsChatRequest() {
						if err = WriteOutput(message, fmt.Sprintf("%v.md", video.TitleNormalized)); err != nil {
							return
						}
					} else {
						messageTools = AppendMessage(messageTools, message)
					}
				}
			}
			return
		}

		messageTools, err = processYoutubeVideo(currentFlags, registry, videoId)
		if !currentFlags.IsChatRequest() {
			err = currentFlags.WriteOutput(messageTools)
			return
		}
	}`
