### ISSUE TITLE
[Question]: Properly using the -o --output switch (Permissions Error)

### ISSUE THREAD

**Issue by jnuts74** [danielmiessler/fabric#1161]
### What is your question?

Is there any sort of permissions or something I am missing that would cause the -output function to not work. No matter what I try it throws permissions error on writing file. Here is an example command I am running:

sudo echo "extract high and critical items from aquasecurity container vulnerability scanning results and present in a clean easy to read format with short executive summary in less than 10 words for each high and critical item" | fabric --pattern create_pattern -o system.md && sudo mv container_vulnerabilities/system.md ../.config/fabric/patterns && cat ../results.txt | fabric --stream --pattern container_vulnerabilities
(error creating file: open system.md: permission denied)

No rush and thanks a TON!

**Comment by butterflyx** [comment]
Works for me beside the pattern container_vulnerabilities does not exists. What is current working directory? Maybe a permission problem, as in my understanding sudo only works for echo not for fabric in your command.

**Comment by jnuts74** [comment]
Running from /home/jnuts74

So I broke this down a bit to continue testing to get the output function working before trying to string together execution of other commands. Here is where I am today:

echo "ability to perform network analysis to identify both security and network performance issues based on examining packet captures" | fabric --pattern create_pattern -o system.md

Error: error creating file: open system.md: permission denied

I even did the unthinkable and 777 my home directory where Fabric is writing the output to and still get permissions error. 

Definitely strange.

**Comment by mattjoyce** [comment]
Does the following work?

echo "test" | ./fabric > foo.txt

**Comment by jnuts74** [comment]
> Does the following work?
> 
> echo "test" | ./fabric > foo.txt

This does work.

**Comment by mattjoyce** [comment]
ok, well you have a workaround, but I'm still interested in figuring out what is occurring.
what about the following test?

> echo "test" | ./fabric -o foo.txt

**Comment by jnuts74** [comment]
> ok, well you have a workaround, but I'm still interested in figuring out what is occurring. what about the following test?
> 
> > echo "test" | ./fabric -o foo.txt

So that also works:
echo "test" | fabric -o foo.txt 
Of course! If you have any questions or need assistance with something, feel free to let me know.
... written to foo.txt


I messed with it a bit more and was able to get this absurd command to work:

sudo mkdir -m 777 summarize_container_vulnerabilities && echo "extract high and critical items from aquasecurity container vulnerability scanning results and present in a clean easy to read format with short executive summary in less than 10 words for each high and critical item" | fabric --pattern create_pattern -o summarize_container_vulnerabilities/system.md && sudo mv summarize_container_vulnerabilities .config/fabric/patterns && sudo chmod -R 755 .config/fabric/patterns/summarize_container_vulnerabilities

It appears that fabric doesnt have the ability to output to directory/file (pattern_name/system.md), so the only option is to create the directory upfront. Issue then is that since you created the directory manually, fabric <user> doesnt have permissions to write to it. 

I am wondering if its worth putting in feature request to make fabric output to create directory and file :

fabric -o directory/system.md

Thoughts?

**Comment by mattjoyce** [comment]
That's unusual use case, to use software to write to it's own folders.
Unless you're making a lot of patterns in this way, I would think manually positioning it after testing would be the way to go.
During testing save to a file somewhere like this


foo | ./fabric --patter foo -o /mytestfolder/summarize_container_vulnerabilities.md

the test using the adhoc pattern method (pattern file can be anywhere)

foo | fabric --pattern  /mytestfolder/summarize_container_vulnerabilities.md

as long as the pattern name begins with ~/ or ./ or ../ or /  it will treat it as a adhoc pattern filename.

**Comment by jnuts74** [comment]
Found slight work around but decision made to manually move newly created patterns to appropriate location as suggested by @mattjoyce 

Thank you
