### ISSUE TITLE
[Bug]: Configured patterns do not follow symlinks

### ISSUE THREAD

**Issue by osheari1** [danielmiessler/fabric#1169]
### What happened?

I am using GNU Stow to manage the pattern files for fabric. Stow creates a symlink in the config dir to the location of my patterns repo. 

It can be reproduced by:
- Create $HOME/.config/fabric/patterns/test/system.md
- Symlink from other dir to $HOME/.config/fabric/patterns/test-2/system.md

Now running `fabric -l` will give `test` as a pattern, but not `test-2`. 

Expected behavior: Symlinks should be followed when collecting the available patterns

### Version check

- [X] Yes I was.

**Comment by mattjoyce** [comment]
@eugeis, I'm happy to look at this.
I think we might need a common utils go, to handle file, path, absolute path, relative path...

**Comment by eugeis** [comment]
@mattjoyce great, thank you.

**Comment by mattjoyce** [comment]
Fixed in PR
https://github.com/danielmiessler/fabric/pull/1181
