### ISSUE TITLE
[Bug]: jinja2 syntax in input text causes errors

### ISSUE THREAD

**Issue by ksylvan** [danielmiessler/fabric#1184]
### What happened?

When passing a text that contains Jinja2 syntax to the AI, it looks like it tried to be interpolated, resulting in an error.

This makes it impossible to use, for example, diffs when working with Go templates or Ansible playbooks as input to `summarize_git_diffs`

### Version check

- [X] Yes I was.

### Relevant log output

```shell
fabric --version
v1.4.119


Here is a simple use case:

```text
$ ai '{{ foo.bar }}'
missing required variable:  foo.bar 
```

**Comment by ksylvan** [comment]
This is likely due to https://github.com/danielmiessler/fabric/pull/1157

@mattjoyce We need a new command-line flag to enable the new variable substitution behavior so that people who work with diffs or text files that contain go template or Jinja2 syntax can still use fabric patterns.

**Comment by mattjoyce** [comment]
@ksylvan yep, I totally missed this use case.

@eugeis , I think we should perhaps implement --inputvars, which will do substitution on input content, default to not.

**Comment by ksylvan** [comment]
@mattjoyce Thanks, that's perfect.

**Comment by ksylvan** [comment]
There's still a slight bug, @mattjoyce 

```text
$ git diff | summarize_git_diff
could not get pattern summarize_git_diff: missing required variable:  domain 

$ fabric --version             
v1.4.120

$ fabric --help | grep input-has
      --input-has-vars      Apply variables to user input
```

Fixed with this patch, @mattjoyce 

```diff
diff --git a/plugins/db/fsdb/patterns.go b/plugins/db/fsdb/patterns.go
index 968b08d..6fedb72 100644
--- a/plugins/db/fsdb/patterns.go
+++ b/plugins/db/fsdb/patterns.go
@@ -68,7 +68,7 @@ func (o *PatternsEntity) applyVariables(
        }
 
        var result string
-       if result, err = template.ApplyTemplate(pattern.Pattern, variables, input); err != nil {
+       if result, err = template.ApplyTemplate(pattern.Pattern, variables, ""); err != nil {
                return
        }
        pattern.Pattern = result
```

**Comment by mattjoyce** [comment]
I'm not sure that's right.  With out that the user input will not be appended or inserted in to the final context.
I think I'll have to hardcode something for that specific var {{input}}, and now I think of it, input is a bit generic, and plausible a diff or other template will use it.  will probably change it fabric_user_input.

**Comment by ksylvan** [comment]
Yes, it's not right. Fails the tests, but it pinpointed the issue. ;-) 

In terms of naming, I favor something like `__fabric_user_input` as a built-in variable that's unlikely to be used in other use cases, with the idea that any variable in the new templating system that is builtin to fabric would by convention start with the `__fabric_` prefix.

**Comment by mattjoyce** [comment]
Well not sure about that, the template system was designed to be used by
people.   The internal plugin is {{plugin:
And the externals are proposed for {{ext:

I regularly type those into my input content so not supportive of making
them obscure, long or complex.

**Comment by eugeis** [comment]
Hi all, what is the status of the PR?

**Comment by mattjoyce** [comment]
Do not proceed.  We'll resubmit.

**Comment by ksylvan** [comment]
> I regularly type those into my input content so not supportive of making them obscure, long or complex.

So what do you propose instead of '{{input}}' which seems too generic?

`{{fabric_input}}` seems fine, but still, thinking about edge cases, if you were using fabric to look at some diffs, for example, that contained that text, you still run into the same issue.

**Comment by mattjoyce** [comment]
New PR : https://github.com/danielmiessler/fabric/pull/1200

**Comment by mattjoyce** [comment]
> > I regularly type those into my input content so not supportive of making them obscure, long or complex.
> 
> So what do you propose instead of '{{input}}' which seems too generic?
> 
> `{{fabric_input}}` seems fine, but still, thinking about edge cases, if you were using fabric to look at some diffs, for example, that contained that text, you still run into the same issue.

yeah, I think we can either always try and get out of the way of every imagined use case, or we can be opinionated and say that token is special.

{{fabric_user_input}}

?

**Comment by ksylvan** [comment]
Yeah, I like `{{fabric_user_input}}`

With VSCode and other IDEs with AI-enhanced auto-complete, you won't feel the extra keystrokes versus the original `{{input}}`

**Comment by ksylvan** [comment]
#1200 works for me. Thanks.
