### ISSUE TITLE
[Question]: model that could manage longer inputs/outputs? Im getting generic responce

### ISSUE THREAD

**Issue by ronacek** [danielmiessler/fabric#1188]
### Is there a free model that could manage long inputs?

I love this program! But sadly for my most uses i need extract wisdom or label and rate pattern after i use transcript of a hour or two long podcast and my llama3.2 or free gpt3.5turbo can not process it and it gives me generic responce withou any use of pattern. Tried llama3.3 70b but my laptop turned into rocket (4060rtx). 

Is there a free model (great would be locally used with ollama) that could manage long inputs? 

Now i use a workaround using | -p summary | -p wisdom but i dont know how precise the wisdom is after it is squashed into summary version.

**Comment by mattjoyce** [comment]
the context window for Ollama is quite small, I think about 2048, but it can be changed by creating a new model file, and setting it there.   To learn more you should ask in Ollama's discord server.
However, the real limit will be your GPU ram, and there not much getting around that.

**Comment by ronacek** [comment]
> the context window for Ollama is quite small, I think about 2048, but it can be changed by creating a new model file, and setting it there. To learn more you should ask in Ollama's discord server. However, the real limit will be your GPU ram, and there not much getting around that.

Tried to play with ollama´s setting but could not figure it out. Im not that skilled in technical stuff :/ 

Is there any other model that is free and working or should i invest into gpt pro?

**Comment by ronacek** [comment]
update: managed to create modelfile with parameter num_ctx set to 32768 and it still was not enough because i still got the generic response like nothing has changed

**Comment by ronacek** [comment]
solved! installed Nvidia CUDA, then my llama started using gpu instead of cpu, but also i had to change manually my main model in .env to the modelfile i made with higher parameters.
