### ISSUE TITLE
[Feature request]: YAML Configuration Support

### ISSUE THREAD

**Issue by mattjoyce** [danielmiessler/fabric#1190]
### What do you need?

# Feature Proposal: # Feature Proposal: YAML Configuration Support

## Overview
Add support for YAML configuration files to Fabric, allowing users to persist commonly used settings and share configurations. This would complement the existing CLI flags system, with CLI arguments taking precedence over config file values.

## Benefits
- Reduce repetitive CLI flag usage for common configurations
- Simplify complex interactions by storing frequently used combinations
- Future extensibility for configuration in pattern front matter of patterns

### Phase 1: Core LLM Configuration
Initially focus on the most commonly used LLM and pattern-related options:

```yaml
# Example config.yaml
model: gpt-4
model_context_length: 4096
pattern: analyze_article
context: ~/aboutme.md
temperature: 0.7
top_p: 0.9
presence_penalty: 0.0
frequency_penalty: 0.0
stream: true
raw: false
```

Configuration precedence would be:
1. CLI flags (highest)
2. Config file
3. Default values (lowest)

### Configuration Locations
Search for config files in this order:
1. Explicitly specified path (`--config path/to/config.yaml`)
2. Current directory (`./fabric.yaml`)
3. User config directory (`~/.config/fabric/config.yaml`)

### Technical Details
- Add new `ConfigOptions` struct for YAML parsing
- Enhance `Flags` struct to track CLI-set values
- Implement config file loading and merging logic
- Maintain backward compatibility
- Add appropriate tests for config loading and precedence

### Future Extensions (Phase 2+)
- Support for multiple config profiles
- Environment variable overrides
- Configuration in pattern front matter
- Configuration in user input front matter
- More configurable options as needed

## Implementation Plan
1. Create basic config loading infrastructure
2. Add core LLM options support
3. Add tests for config loading and precedence
4. Add documentation
5. Gradually expand supported options

## Migration/Compatibility
- No breaking changes to existing CLI usage
- Config files are optional
- Default values remain unchanged
- Existing scripts and workflows continue to work

**Comment by mattjoyce** [comment]
@eugeis Naturally, I'm happy to implement.

**Comment by eugeis** [comment]
@mattjoyce Yes, thank you, great.

**Comment by matmilbury** [comment]
@mattjoyce @eugeis why is this closed? This is not documented anywhere, nor does it work by creating a file at `~/.config/fabric/config.yaml`
