### ISSUE TITLE
[Question]: Fabric not found in the current Poetry environment

### ISSUE THREAD

**Issue by tb-1212** [danielmiessler/fabric#122]
### What is your question?

Hi I followed the Quickstart but when I tried to run ./setup.sh

it gives this error
Command fabric not found in the current Poetry environment.
Command fabric-api not found in the current Poetry environment.
Command fabric-webui not found in the current Poetry environment.

Did I install it wrong? Can you provide some steps to solve this?

**Comment by davidrobinsonau** [comment]
See step 7. Restart your shell to reload everything.
Close your shell terminal window and open again. This makes sure your updated .bashrc or .zshrc files are processed with the new information. Including the location of Poetry files.

**Comment by AndrewClaes** [comment]
Well, the error occurs before step 7...
I had the same problem, but I found the solution:
just do 'pip install poetry' inside your fabric directory.
Having done this, everything worked for me.

**Comment by bdx-asn** [comment]
@AndrewClaes, thx a lot! It's work +1
