### ISSUE TITLE
Can someone explain about this project?

### ISSUE THREAD

**Issue by muthanii** [danielmiessler/fabric#13]
I looks like a very promising project but I don't understand what kind of framework it is. There aren't any examples included or anything. I'm taking courses in machine learning and would like to contribute to this project given I understand the basic gist of it.

**Comment by hunordori** [comment]
[This video](https://www.youtube.com/watch?v=vF-MQmVxnCs) might explain it better.
But imagine every system.md file as a pre-written prompt. You can test it by copy one of them into ChatGPT and filling out the  "INPUT:" section.
Of course, it is more efficient if you use it in a script.

**Comment by danielmiessler** [comment]
Yes, as hunordori said, and another way to say it is that it's a set of discrete AI components that people can stack together to enhance their lives. So basically you figure out what you're trying to accomplish, you break that into components, and then you use Fabric to apply AI to those components.

**Comment by linzhonglang007** [comment]
他们看起来似乎是一些可行性非常高的人工智能脚手架，但是并没有发布一系列使其运行起来的操作步骤和部署细则，但是我看到作者已经留有部署模块和文件仓库模块，后续应该会慢慢补充，我觉得应该是开创历史先河：将人工智能搭建成脚手架然后来应用到一般项目中。我还看到所收费用，费用初步评价：太高
