### ISSUE TITLE
Server and client parts are missing

### ISSUE THREAD

**Issue by fishhead108** [danielmiessler/fabric#130]
### What happened?

`Server` and `client` parts are missing
```
To get started, head over to the [/server/](https://github.com/danielmiessler/fabric/tree/main/server) directory and set up your own Fabric Mill with your own Patterns running! You can then use the [/client/standalone_client_examples](https://github.com/danielmiessler/fabric/tree/main/client/standalone_client_examples) to connect to it.
```
![image](https://github.com/danielmiessler/fabric/assets/2705977/7f705ea6-d104-4dcc-93ad-ee69856b2213)
![image](https://github.com/danielmiessler/fabric/assets/2705977/f3b642c1-a53f-4839-a452-1d3122876c6a)

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
Fixed the documentation. You just run ./setup and it'll tell you how to run them.
