### ISSUE TITLE
[Feature request]: helpers vm set transcript language

### ISSUE THREAD

**Issue by ben0815** [danielmiessler/fabric#134]
### What do you need?

Is it possible to set the language for the transcript in helpers/vm?
Idea: 
parser.add_argument('-l', '--language', help='Set transcript language (en)', default='en')
transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=[options.language])

**Comment by danielmiessler** [comment]
Thank you for this. Can you submit as a feature request?
