### ISSUE TITLE
[Question]: helpers vm dependencies

### ISSUE THREAD

**Issue by ben0815** [danielmiessler/fabric#135]
### What is your question?

I'm using debian and try to get helpers/vm to run. youtube-transcript-api is missing and not in the debian apt package.
Is it possible to add youtube-transcript-api, googleapi and isodate to pyproject.toml?
With "poetry shell" in a terminal, it's now possible to run helpers/vm. Or is there an other way?

**Comment by danielmiessler** [comment]
This is fixed now with the new installer. Rerun setup.sh and --update afterwards and restart your shell.
