### ISSUE TITLE
[Feature request]: Update ReadMe to replace pbpaste in examples 

### ISSUE THREAD

**Issue by vpzed** [danielmiessler/fabric#143]
### What do you need?

Suggestion:  "pbpaste" is a Mac only command.  Therefore, 95% of people viewing the README.md will not immediately understand the examples in "Example commands".  Using a more common command like "cat input.txt ..." could improve understanding on first read for a larger audience.  Thinking about reducing friction for new users.

**Comment by ptsiampas** [comment]
You can simulate pbpaste on Linux with the following aliased commands:
```
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
```
You must, of course, install `xclip`.

**Comment by danielmiessler** [comment]
Good recommendation on how to address this by @ptsiampas .
