### ISSUE TITLE
Install process: check for non-existent .bashrc / .zshrc files & prompt user to create them if they aren't there.

### ISSUE THREAD

**Issue by mcauthorn** [danielmiessler/fabric#144]
### What do you need?

**Overview**
When going through the `setup.sh` process, I noticed that the script told me that no configuration files had been touched, so there was nothing to source. I went ahead and ran `touch ~/.zshrc` so it would setup all of my aliases for me, which worked well. 

**Enhancement**
It may be a nice convenience for people who aren't shell-comfortable to prompt them with an option to create the associated `.rc` file if one doesn't exist (after checking their current `$SHELL`). If they answer "yes" to create, create the file, add the aliases, and then to source it for them so they don't have to close / reopen their shell. 

Just a convenience suggestion for the install process, excited to dive deeper with the project!

**Comment by danielmiessler** [comment]
This should be properly handled now with the new setup.
