### ISSUE TITLE
[Feature request]: setup option to not fill the shell rc files with aliases

### ISSUE THREAD

**Issue by xntrik** [danielmiessler/fabric#154]
### What do you need?

I think it may be nice to support an optional env var/flag optional flag that didn't perform the Alias functionality. Adding 50+ aliases into my `.zshrc` felt like a bit of an unexpected outcome.

**alternatively**, use a separate .sh that you can simply "source" into your `.zshrc` < this may reduce all the required changes in your zshrc down to something as little as:

```
if [ -f '/Users/name/.config/fabric/fabric-bootstrap.inc' ]; then . '/Users/name/.config/fabric/fabric-bootstrap.inc'; fi
```

^ this is the same pattern used by other cli tools, such as `gcloud`

**Comment by invisiblethreat** [comment]
I keep by `.zshrc` versioned in `git`- and also use a similar pattern as above. Fully support this approach for the installer.

**Comment by xssdoctor** [comment]
This is now done. Just git pull and run .setup.sh and the .zshrc will be cleaned up, the /Users/name/.config/fabric/fabric-bootstrap.inc will be automatically made. You also need to fabric --update to get the pattern aliases back
