### ISSUE TITLE
[Feature request]: persistent custom patterns

### ISSUE THREAD

**Issue by Argandov** [danielmiessler/fabric#159]
### What do you need?

I created a custom pattern in `$HOME/.config/fabric/patterns` but when I updated fabric (`fabric --update`) I lost my custom pattern. It's no problem to create my own workflow of backing up > updating fabric > copying again my custom patterns to fabric's pattern directory, but I think it might be a good addition to allow for persistent custom patterns

**Comment by xssdoctor** [comment]
done. Enjoy!
