### ISSUE TITLE
Naming confusion with fabric

### ISSUE THREAD

**Issue by offbyone** [danielmiessler/fabric#16]
"fabric" is the name of an existing Python library: https://github.com/fabric

I'm not sure what to suggest here, but I think you may find that this generates some confusion.

**Comment by danielmiessler** [comment]
Thanks for the comment, but I don't think I'm going to do anything about that. I think it's ok that there are some naming collisions; it's just inevitable.

**Comment by deeplook** [comment]
I suggested Faibrick here: https://github.com/danielmiessler/fabric/discussions/62. ;-)
