### ISSUE TITLE
[Question]: Any way to supply a PDF file as input?

### ISSUE THREAD

**Issue by justintime** [danielmiessler/fabric#171]
### What is your question?

I'm attempting to use extract_wisdom on a set of PDF's that I have access to.  I don't see any way to supply the PDF file to fabric, is there a way that I'm missing?

I tested using pdftotext and that works, but I realized that I lose hyperlinks in the conversion that would typically be included in the REFERENCES section of the output.

**Comment by nic0711** [comment]
https://useanything.com/ might be a solution... sounds promising

**Comment by garthoid** [comment]
Its janky but I load the pdf in a browser and copy all to the clipboard. Then its pbpaste or paste it into a text file and pipe it to fabric. Its not idea but it works in a pinch.

**Comment by asemarafa** [comment]
Easiest way is to install `poppler` and use the included `pdftotext` command.

Example:

```bash
pdftotext /path/to/pdf - | fabric --stream  -m llama3:latest -p summarize
```

**Comment by tfriedel** [comment]
you can prepend https://r.jina.ai/ to an URL to a pdf. It will convert it to txt.

Example:
```sh
curl -s "https://r.jina.ai/https://openaccess.thecvf.com/content/CVPR2023/papers/Bucarelli_Leveraging_Inter-Rater_Agreement_for_Classification_in_the_Presence_of_Noisy_CVPR_2023_paper.pdf" | fabric --stream --pattern analyze_paper
```

**Comment by wmahfoudh** [comment]
Hi all,

I created a [pull request](https://github.com/danielmiessler/fabric/pull/1270) that fixes this.
