### ISSUE TITLE
[Bug]: PowerShell VS Code - Fabric SetUP

### ISSUE THREAD

**Issue by agathaaaaa** [danielmiessler/fabric#175]
### What happened?

I followed the instructions given in the Readme. When I reached to step 6 by "bash setup.sh" (as I want to install this project in PowerShell VS code), it shown that /c/Users/xxx/.bashrc, zshrc and bash_profile does not exist. Then, I restart the shell to reload everything. I got an issue when running "fabric --setup". The error is shown as below. Got any ways to solve this issue other than using WSL? Thank you. 
![error](https://github.com/danielmiessler/fabric/assets/143473563/c7745363-5516-411d-a56e-3f57172d7c18)

### Version check

- [X] Yes I was.

**Comment by agathaaaaa** [comment]
I solve the above problem by running the Fabric code in Virtual environment. Hope this helps!

**Comment by danielmiessler** [comment]
Thank you!
