### ISSUE TITLE
[Bug]: Failed to fetch models: HTTP 401

### ISSUE THREAD

**Issue by agathaaaaa** [danielmiessler/fabric#177]
### What happened?

I was try to run the patterns. But, the error "Failed to fetch models: HTTP 401" shown. How to solve this?

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
Make sure you do a git pull, ./setup, restart your shell, and try again.

**Comment by phalexo** [comment]
(Fabric) developer@ai:~/fabric$ fabric --pattern summarize --model mistral-7b-instruct-v0.2.Q6_K:latest
Failed to fetch models: HTTP 401

**Comment by xssdoctor** [comment]
I just fixed this. Git pull then list models again.

**Comment by albeorla** [comment]
Thank you, working for me 🙏

**Comment by phalexo** [comment]
Even though it works now to list models, and appears to be able to take a
file from stdin and process it, it still does

Failed to fetch models: HTTP 401
No OpenAI API key found. Please run fabric --setup and add the key if you
wish to interact with openai

It might be doing this because I am not using Anthrop\c model, and don't
have it locally.

**Comment by agathaaaaa** [comment]
Same issue here. After I did a git pull, ./setup, and restart my shell, it stated:

Failed to fetch models: HTTP 401
No OpenAI API key found. Please run fabric --setup and add the key if you wish to interact with openai

However, I can find my entered API key in the fabric configuration file ...

**Comment by phalexo** [comment]
I looked at the code. This message comes from the section where one is
supposed to set the key for Anthrop\c's Claude. The message
incorrectly mentions OpenAI instead.

In any case, if one does not want to use Claude, there should be no error
message at all.
