### ISSUE TITLE
[Feature request]: support for azure hosted openai models?

### ISSUE THREAD

**Issue by mariusgarmhausen** [danielmiessler/fabric#179]
### What do you need?

I was wondering if Azure hosted endpoints are already implemented?

**Comment by streichsbaer** [comment]
I was also looking for the Azure OpenAI option, but it's not yet supported.

@danielmiessler, I'd be happy to create a PR for that feature.

Let me know.

**Comment by GuizzyQC** [comment]
Try adding a OPENAI_BASE_URL= line in ~/.config/fabric/.env

It does complain about "Unable to fetch models" and "No OpenAI API key found" (despite having an API key too), as elsewhere in the code it does fetch a list of models from a hardcoded OpenAI URL, but outside of that it does work for me on a different OpenAI API compatible endpoint.

**Comment by bjcbusiness** [comment]
> Try adding a OPENAI_BASE_URL= line in ~/.config/fabric/.env
> 
> It does complain about "Unable to fetch models" and "No OpenAI API key found" (despite having an API key too), as elsewhere in the code it does fetch a list of models from a hardcoded OpenAI URL, but outside of that it does work for me on a different OpenAI API compatible endpoint.

This doesn't work at all for me. Looking forward to proper support for Azure.

**Comment by vfarcic** [comment]
👍 for Azure OpenAI support

**Comment by AtheeSouhait** [comment]
Made it working with my Azure openai deployment, you can test:
[https://github.com/AtheeSouhait/fabric/tree/AtheeSouhait-AzureOpenAIonCLI](https://github.com/AtheeSouhait/fabric/tree/AtheeSouhait-AzureOpenAIonCLI)

New environment variables must contain:
AZURE_OPENAI_API_KEY
AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_API_VERSION
AZURE_OPENAI_MODEL
for example:
export AZURE_OPENAI_API_VERSION=2024-02-15-preview
export AZURE_OPENAI_ENDPOINT=https://yourdeploymentendpoint.openai.azure.com/
export AZURE_OPENAI_MODEL=myGPT4-32k
export AZURE_OPENAI_API_KEY=yourazureopenaideploymentapikey

**Comment by bjcbusiness** [comment]
Works for me.  I set the required environment variables in the .env file. Able to list models and use a pattern.

Thank you very much.

**Comment by AtheeSouhait** [comment]
Hi @stefanstranger , indeed the update don't modify output of --listmodel so it is not included in the list. But your setting automaticaly uses your AZURE open ai model. By the way, if you want to use OPENAI model and not the Azure; comment the AZURE_OPENAI_API_KEY line of your .env so it is not taken as default.
I should have also adapted this "listmodel" part  of the code. I'll do if I have the time but as the project will move to "go" language implementation, I'm not sure it worth the effort, what do you think?

**Comment by stefanstranger** [comment]
Hi @AtheeSouhait,

Thanks for your quick response 🙏. 

I've commented out the OPENAI_API_KEY for now to be sure it will use the AZURE_OPENAI_API_KEY.

When I now try use Fabric I get the following error.

```bash
echo "What is the Capital of the Netherlands?" | fabric --stream --pattern ai
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'
```

When running the following curl I just get a response:
```bash
curl "https://<instancename>.openai.azure.com/openai/deployments/chatdemo/chat/completions?api-version=2024-02-15-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: <enter api key>" \
  -d "{
  \"messages\": [{\"role\":\"system\",\"content\":\"What is the capital of the Netherlands?\"}],
  \"max_tokens\": 800,
  \"temperature\": 0.7,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
```

![image](https://github.com/danielmiessler/fabric/assets/2125385/768cf900-c90e-4d1b-ab85-eb1cb391ef03)

Something still is not configured correctly.

What am I missing?

**Comment by AtheeSouhait** [comment]
@stefanstranger did you get [my repo's code](https://github.com/AtheeSouhait/fabric/tree/main)? because I can"t see my changes any more in the official version. Or you can see what I changed in the utils.py file and report in the repo you cloned.

**Comment by stefanstranger** [comment]
Yes I copied the raw content from 'your' utils.py file to my local repo.

**Comment by AtheeSouhait** [comment]
Not working when I use --stream but working without.
![image](https://github.com/danielmiessler/fabric/assets/54096539/b7fe4908-e4bf-41ec-9fad-a92c866bdcdd)
Is it working when you use openai and not azure Open ai (comment the AZURE_OPENAI_API_KEY of env) ?

**Comment by MrPewPewLaser** [comment]
@stefanstranger I got it to work for me. The problem seems to be that his Code is far behind the original repo that requires newer package version. So I cloned his entire repo and forced a new install of fabric using pipx install . --force

Hope it helps. :)

**Comment by stefanstranger** [comment]
Hi @MrPewPewLaser thanks for your help.

Will try your suggestions and let you know if that works.

Regards,
Stefan

**Comment by AtheeSouhait** [comment]
Thanks @MrPewPewLaser, @stefanstranger : I also re-tested : resinstallation of fabric from https://github.com/danielmiessler/fabric (cloned, put my utils.py, and continue all installation steps + add Azure environment variables). And after the installation it worked (with gpt4 model in Azure , I didn't try 3.5 or other models yet). I know it is not perfect as --stream seams not to be supported. I hope it will work for you.

**Comment by AtheeSouhait** [comment]
@stefanstranger @MrPewPewLaser Great, I'm working on a dockerfile to ease the installation, setup, and the usage. I let you know.

**Comment by eugeis** [comment]
Azure Open AI provider is supported now.

**Comment by josearias210** [comment]
@stefanstranger   @MrPewPewLaser  @AtheeSouhait  I'm trying to implement Azure OpenIA as a vendor, and I'm using the docker version.

Is there any progress on this? Is there a branch where there is a development?

**Comment by AtheeSouhait** [comment]
Hi, @josearias210 
If you have the "go" version of fabric, test with those environment variable & names, that are not the same as yours:
DEFAULT_VENDOR=Azure
DEFAULT_MODEL=gpt-4o
PATTERNS_LOADER_GIT_REPO_URL=https://github.com/danielmiessler/fabric.git
PATTERNS_LOADER_GIT_REPO_PATTERNS_FOLDER=patterns
AZURE_API_KEY=xxxx
AZURE_API_BASE_URL=https://xxx.openai.azure.com/
AZURE_DEPLOYMENTS=gpt-4o
YOUTUBE_API_KEY=xxx

**Comment by josearias210** [comment]
@AtheeSouhait Thanks for your reply, I made the change and I think I made some progress because now I am facing this error.

![image](https://github.com/user-attachments/assets/e9777ebc-72dd-4e11-970b-264d12c34da9)

I don't have any pattern. It seems like a bug in Dockerfile trying to copy the patterns?

**Comment by josearias210** [comment]
@AtheeSouhait @stefanstranger 

I manually copied the files that are created /patterns into root/.config/fabric/patterns and this fixed that problem, but now I have the following

![image](https://github.com/user-attachments/assets/805fdc7f-2d02-48e4-8756-b58360271c20)
