### ISSUE TITLE
Wisdom Input?

### ISSUE THREAD

**Issue by rovo79** [danielmiessler/fabric#18]
Looking through the Patterns to try and understand how to make use of them, I'm confused why the _Wisdom_ one doesn't have an Input section in the [system.md](../blob/81c5bff22f6933297080c32823a46b54ffbd8d7f/patterns/extract_wisdom/system.md)? 

```
# INPUT:

INPUT:
```

**Comment by danielmiessler** [comment]
It's not strictly necessary, but I'll add it. Thank you.
