### ISSUE TITLE
[Bug]: Fabric's setup adds/updates a large number of alises in wrong shell config file

### ISSUE THREAD

**Issue by sammcj** [danielmiessler/fabric#181]
### What happened?

When running Fabric's `./setup.sh` - and `--setup` Fabric (without warning) updated the wrong config file that I use for my shell aliases.

To keep my zsh config tidy I keep all my aliases in a file like `~/.zsh/alises` which is included in (sourced from) my zshrc profile (~/.zshrc).

I expected Fabric's setup commands to either:

1) Output any aliases that can be added for the user to add them.

or

2) Detect where existing aliases are defined and prompt if the user wants to add/update them.

Instead it added a large number of aliases to my top level ~/.zshrc file which I manage in version control elsewhere.

---

What I would suggest:

Instead of generating and maintaining a large list of shell alias commands - Fabric could instead provide a single shell _function_.

This function could take any number of arguments for commands (aliases/whatever) that are managed by Fabric rather than constantly updating the users main shell aliases.

This could be added either added automatically or output for the user to add.

This approach would be cleaner, and easier to maintain / separate from the users environmental configuration.

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

<img width="1053" alt="image" src="https://github.com/danielmiessler/fabric/assets/862951/628e001a-135f-47b8-8356-d5bf4263a27d">

**Comment by xssdoctor** [comment]
OK this is fixed. just pull the latest commit and run setup.sh and your .zshrc will be cleaned up and there will be a new config file made in the .config/fabric folder which is sourced from you .zshrc or .bashrc. Try it out and let me know if everything is working

**Comment by sammcj** [comment]
nice! that seemed to work.

Thanks for the very fast response too :)
