### ISSUE TITLE
[Bug]: alias is not defined

### ISSUE THREAD

**Issue by zestysoft** [danielmiessler/fabric#190]
### What happened?

I caught this while looking through the code

### Version check

- [X] Yes I was.

### Relevant log output

```shell
https://github.com/danielmiessler/fabric/blame/24e161686489935a68891c269912fd5d8581b035/installer/client/cli/utils.py#L396
```

**Comment by xssdoctor** [comment]
I'm sorry, im not understanding. What error are you getting? what did you find in the code?

**Comment by zestysoft** [comment]
where is 'alias' defined in its use in the fstring here:

```
def find_line(self, name):
        for file in self.config_files:
            with open(file, "r") as f:
                lines = f.readlines()
            for line in lines:
                if line.strip("\n") == f"alias ${name}='{alias}'":
                    return line
```

find_line only takes two parameters: self and name?
