### ISSUE TITLE
[Feature request]: allow edit of base_url

### ISSUE THREAD

**Issue by junmagic-ai** [danielmiessler/fabric#191]
### What do you need?

i want to be able to change the base url to another endpoint e.g. the Azure OpenAI endpoint instead of default OpenAI

**Comment by GuizzyQC** [comment]
I've managed to get it working on a different OpenAI API-compatible endpoint (Oobabooga) by adding a OPENAI_BASE_URL= line in ~/.config/fabric/.env

It does complain about "Unable to fetch models" and "No OpenAI API key found" (despite having an API key too), but it does work other than that.

**Comment by meirm** [comment]
I fixed this on an upcoming pull request where we deal with OpenAI baseURL.

**Comment by maaft** [comment]
@meirm  which one? When will it be merged?

**Comment by meirm** [comment]
https://github.com/danielmiessler/fabric/pull/189

**Comment by eugeis** [comment]
It is available in the current release.
