### ISSUE TITLE
[Bug]: YOUTUBE_API_KEY not found - Different key names 

### ISSUE THREAD

**Issue by gregorh1** [danielmiessler/fabric#193]
### What happened?

I had a problem using YT Helper because there's a mix-up in the names. YT is trying to find `YOUTUBE_API_KEY`, but the `utils.py` writes `CLOUD_API_KEY` in the configuration file. Also when using `fabric --setup`, it doesn't put a new line after `OPENAI_API_KEY=someKey`.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
`yt 'https://www.youtube.com/watch?v=someId'                            
Error: YOUTUBE_API_KEY not found in ~/.config/fabric/.env`
```

**Comment by danielmiessler** [comment]
We're working on this one, thank you.
