### ISSUE TITLE
[Bug]: --copy parameter throwing an error

### ISSUE THREAD

**Issue by arcaneum** [danielmiessler/fabric#197]
### What happened?

when I try to use the --copy parameter to pipe the output to the clipboard, I am getting the following error. I am running this on an Apple Silicon Mac with M3 Max chip.

The exact command I used on the Mac terminal was:

> yt 'https://www.youtube.com/watch?v=lEXd6TXPw7E' | extract_wisdom --copy

### Error Message
```
Traceback (most recent call last):
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/fabric-xqnZk2pv-py3.11/bin/fabric", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/<username>/fabric/installer/client/cli/fabric.py", line 146, in main
    standalone.sendMessage(text)
  File "/Users/<username>/fabric/installer/client/cli/utils.py", line 246, in sendMessage
    pyperclip.copy(response.choices[0].message.content)
                   ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
```

### Version check

- [X] Yes I was.

**Comment by meirm** [comment]
The code needs some cleanup. 
In the meantime I posted a pull request https://github.com/danielmiessler/fabric/pull/203

**Comment by xssdoctor** [comment]
OK, i added --copy for local models and for claude

**Comment by arcaneum** [comment]
Thank you, @xssdoctor
