### ISSUE TITLE
[Bug]: sed:  in-place editing only works for regular files

### ISSUE THREAD

**Issue by zestysoft** [danielmiessler/fabric#198]
### What happened?

./setup.sh assumes that the dot files to be edited are regular files when they could be symlinked.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
sed: /Users/username/.zshrc: in-place editing only works for regular files
sed: /Users/username/.zshrc: in-place editing only works for regular files
```

**Comment by meirm** [comment]
I found the bug and will  send a pull request soon

**Comment by danielmiessler** [comment]
Please resubmit PR
