### ISSUE TITLE
[Feature request]: No setup.bat for us mortals working with windows?

### ISSUE THREAD

**Issue by IVTore** [danielmiessler/fabric#208]
### What do you need?

Is fabric linux and mac only?

**Comment by Gerkinfeltser** [comment]
Not a complete and/or official solution but I got it working on windows using pipx using the steps outlined here: https://github.com/danielmiessler/fabric/issues/183#issuecomment-1992999166

I'm just getting started with it but so far so good.

**Comment by danielmiessler** [comment]
Yeah, best to use with WSL.
