### ISSUE TITLE
[Bug]: the Matthew Berman video is incorrect for installation

### ISSUE THREAD

**Issue by cleesmith** [danielmiessler/fabric#212]
### What happened?

The youtube shows how to setup poetry and use a ./setup.sh script which has benn deleted.
This is confusing, especially since the new pipx install does not work ... dotenv is missing.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
No log because the video setup can no longer be followed with missing files.
```

**Comment by xssdoctor** [comment]
It should be fixed. Try again

**Comment by cleesmith** [comment]
I meant the instructions in Berman's youtube video is old and will not work, because ./setup.sh is deleted.  

So why refer to a misleading video, as you have to skip over his installation instructions.

Thanks again for the quick update.

**Comment by danielmiessler** [comment]
Yes, it's true. But the new process is now better and we have the note at the top of the install.
