### ISSUE TITLE
[Question]: My executable is 0KB please help ive been trying for hours

### ISSUE THREAD

**Issue by 6351** [danielmiessler/fabric#220]
### What is your question?

After reading the documentation, I am still not clear how to get the executable working working. I have tried countless different solutions uninstalling and reinstalling countless times but when I execute "pipx install ." all the files that get downloaded into C:\Users\****\.local\bin are 0kb and when I try to use fabric it just says "fabric: command not found" please help! Thanks.

**Comment by zestysoft** [comment]
I had trouble too.  See if this fixes it since it did for me:

From the repo's root directory:
`pipx uninstall-all`
`pipx -vvv install .`

**Comment by BryanKerrEdTech** [comment]
That worked for me on my Mac, though I didn't need to run `pipx ensurepath`. Thanks!

**Comment by danielmiessler** [comment]
Awesome!
