### ISSUE TITLE
[Bug]: Error code 400 - You must provide a model parameter

### ISSUE THREAD

**Issue by schmuecker** [danielmiessler/fabric#239]
### What happened?

I was executing my first fabric pattern after installing and setting up, when the Error Code "400 - You must provide a model parameter" happened. I was expecting the API request to return a response to happen instead.
I setup fabric with an OpenAI Key and tried it with ollama as well (changing the default model to openhermes2.5-mistral:latest).

### Version check

- [X] Yes I was.

### Relevant log output

```shell
❯ pbpaste | fabric --pattern summarize
Error: Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by xssdoctor** [comment]
Check out .config/fabric/.env and see what it looks like. Maybe there’s a typo somewhere

**Comment by danielmiessler** [comment]
TY
