### ISSUE TITLE
General help please

### ISSUE THREAD

**Issue by bongonations** [danielmiessler/fabric#24]
Hey Daniel a belated happy new year to you sir. Thank you for your wonderful work. I love your AI Fabric open source idea. I am just learning AI and wondered how you managed to create those GPTs as you demonstrated via your Linux on prem box?

I want to try out the extractwisdom but not too sure how to start. I know you mentioned flask and some other technologies. But wondered if you had an idiots guide as to how to setup a GPT like extractwisdom 

![image](https://github.com/danielmiessler/fabric/assets/31993539/a04609a6-0999-4dc6-b08b-fef2cdca103c)

Any dummies guide help would be gratefully appreciated 

Thank you sir
AJ

**Comment by omrija1** [comment]
i would love to know this. Also, I have other question, Sorry for asking here, Hopefully you don't mind [bongonations]
Is fabric useful for ethical hacker students who're learning? to sort things out like that for their things instead of just using notes, like replacement for notes or addition to notes for enchanted experience.

**Comment by manojgowda5** [comment]
.

**Comment by manojgowda5** [comment]
..

**Comment by tasnuva1** [comment]
If you can upload those Unix scripts that would be awesome.

**Comment by chrissonntag** [comment]
Those "Unix script" are nothing more than i.e. python scripts without the extension ".py", but with an appropriate [Shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)). There is already one presented in https://github.com/danielmiessler/fabric/blob/main/client/fabric
The only thing you have to do is, to create aliases to that executable file `fabric`. No need to have separate files and whatnot.

So make sure that `fabric` can be interpreted correctly. Either install python3 onto your system directly or rather install python3 via [Conda](https://conda.io/projects/conda/en/latest/index.html) - or in my case [Miniconda](https://docs.conda.io/projects/miniconda/en/latest/).
In case you were to install Miniconda the shebang would look something like this:
```shell
#!/home/username/miniconda3/envs/fabricenv/bin/python
```
Assuming your home directory lies in `/home/username/` and the Conda environment you have created is called `fabricenv`.

An alias to the executable `fabric` would i.e. be stored in `~/.bashrc` and could look like this:
```shell
alias extractwisdom="/path/to/fabric -p extract_wisdom -t"
```

Then you would be called like this:
```shell
extractwisdom "Believe that life is worth living and your belief will help create the fact."
```

**Comment by danielmiessler** [comment]
Yes, exactly like Chris said. Good stuff. Thank you for the question and thanks to Chris for the explanation.

**Comment by tasnuva1** [comment]
> Those "Unix script" are nothing more than i.e. python scripts without the extension ".py", but with an appropriate 

Thanks for sharing.  I was behind on the latest commits.

Here is the Arch Linux setup if anyone needs it:
1. First Note: All commands should be run in this folder: `fabric/client`.
2. For installing extra packages: `pacman -S yay`
3. For installing python's virtual environment: `yay -S python-virtualenv`
4. For creating the virtual environment: `virtualenv --python=/usr/bin/python3.11 --python=python3.11 ./` 
5. For activating the environment: `source ./bin/activate`. Side Note For deactivate: `deactivate`
6. For installing all the packages: `pip install -r requirements.txt`
7. For seeing all the command options: `./fabric --help`
8. For setting up the openAI key: `./fabric --setup`
9. It's needs chatGPT-4 paid version: `./fabric -p extract_wisdom -t "Believe that life is worth living and your belief will help create the fact."`
