### ISSUE TITLE
[Bug]: Issue after installation

### ISSUE THREAD

**Issue by bogdanshuliar** [danielmiessler/fabric#240]
### What happened?

I've installed fabric, closed the terminal and now the out I have when I'm trying to put any fabric command

fabric --help
bash: fabric: command not found

pipx and poetry are installed.

I used 
--model MODEL, -m MODEL
and after it fabric stopped working

### Version check

- [X] Yes I was.

**Comment by PMuszalski** [comment]
Seems as the issue with new version [v1.2.0]. 
running setup results in following message in bash: 
$ fabric --setup
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\fabric-9S8r0sw6-py3.11\Scripts\fabric", line 3, in <module>
    from installer import cli
ModuleNotFoundError: No module named 'installer'

**Comment by xssdoctor** [comment]
did you follow the pipx instructions? if so, run pipx install . --force again in the fabric folder and try again

**Comment by xssdoctor** [comment]
I just pushed another commit that should fix everything. It was my fault

**Comment by danielmiessler** [comment]
TY
