### ISSUE TITLE
[Bug]: Unable to change the default model

### ISSUE THREAD

**Issue by PMuszalski** [danielmiessler/fabric#243]
### What happened?

In the new version command
fabric --changeDefaultModel is no longer accepted.

Message:
$ fabric --changeDefaultModel gpt-3.5-turbo
usage: fabric [-h] [--text TEXT] [--copy] [--output [OUTPUT]] [--stream] [--list] [--update] [--pattern PATTERN] [--setup] [--model MODEL] [--listmodels] [--context] {agents} ...
fabric: error: argument command: invalid choice: 'gpt-3.5-turbo' (choose from 'agents')

### Version check

- [X] Yes I was.

**Comment by xssdoctor** [comment]
are you sure you're on the latest commit? that was an error I was getting last night but then fixed

**Comment by danielmiessler** [comment]
TY
