### ISSUE TITLE
[Bug]: Errors after latest update: "you must provide a model parameter" & for YT command: "ModuleNotFoundError: No module named 'helpers.yt'"

### ISSUE THREAD

**Issue by arcaneum** [danielmiessler/fabric#244]
### What happened?

I updated fabric with pipx and it has basically stopped working for me, where as it was mostly functional for me before that, except for the --copy parameter, which I reported in a separate bug report. 

pbpaste is functional, but when you pipe it to a fabric pattern, I'm getting the following error : **Error 1**

Also, not sure what else is broken now, but YT command was working well earlier, where as it is not now: **Error 2**

### Error 1: "you must provide a model parameter"

pbpaste | fabric --pattern summarize               
Error: Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Error 2: "No module named 'helpers.yt"

yt 'https://www.youtube.com/watch?v=lEXd6TXPw7E'             
Traceback (most recent call last):
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/fabric-xqnZk2pv-py3.11/bin/yt", line 3, in <module>
    from helpers.yt import main
ModuleNotFoundError: No module named 'helpers.yt'

### Version check

- [X] Yes I was.

**Comment by xssdoctor** [comment]
fixed that last night. pull the latest commit

**Comment by xssdoctor** [comment]
every time you do a pull and you are using pipx you need to pipx upgrade fabric. this is true for anything in pipx

**Comment by natv** [comment]
I don't think I am:

(.venv) user@Nathalie-AI:~/ai/fabric$ pipx upgrade fabric
Package is not installed. Expected to find /home/user/.local/pipx/venvs/fabric, but it does not exist.

**Comment by xssdoctor** [comment]
when you installed this, did you use pipx install .?

**Comment by natv** [comment]
I don't think so, I would have used whatever instructions at the time, but there were iterations since then I believe. Should I just re-install?

**Comment by arcaneum** [comment]
> fixed that last night. pull the latest commit

@xssdoctor I had git pulled, pipx upgraded and updated fabric earlier and that's when I started getting these errors, it was working fine prior to that as I mentioned. Just to be sure, I re-did all the steps once again just to be sure and I'm still getting the same errors. Please see a screenshot of my terminal window for your reference.

Please let me know if I'm missing something here or need to additionally do something to get this to work? I'm on an Apple Silicon M3 Max machine.

![image](https://github.com/danielmiessler/fabric/assets/38038031/3b1381ea-0746-4b02-a4cd-fcc9cd29f661)

**Comment by natv** [comment]
I'm on linux, just to rule out a OS specific issue

**Comment by xssdoctor** [comment]
I'll look at the yt think, a pull request from yesterday kind of messed that up. As far as the other thing, do fabric --changeDefaultModel gpt-4-turbo-preview and that should fix it. maybe there's like a space in the config or something

**Comment by arcaneum** [comment]
> I don't think I am:
> 
> (.venv) user@Nathalie-AI:~/ai/fabric$ pipx upgrade fabric Package is not installed. Expected to find /home/user/.local/pipx/venvs/fabric, but it does not exist.

@natv I had the same error message initially when I tried to upgrade via pipx. I then had to install pipx on my machine first (via brew install for Mac), and then I was able to upgrade

**Comment by xssdoctor** [comment]
the error messages I'm seeing dont make sense. There is no reference to "helpers" anymore anywhere in the code. I changed the name to helper_files, so that MUST be an old version of fabric. Are you sure that there is not an alias somewhere to another version of fabric on your system?

**Comment by arcaneum** [comment]
I have this file called 'yt' in the path **$HOME/Library/Caches/pypoetry/virtualenvs/fabric-xqnZk2pv-py3.11/bin/yt** on my Mac, presumably placed there as part of the Poetry installation. It is a system executable file which opens only in the terminal and inside that file I see this error message on helpers.yt - not sure whether that's some sort of a log file? 

![image](https://github.com/danielmiessler/fabric/assets/38038031/0b29b3bd-524c-4a5e-a3ec-82462fe07790)

**Comment by natv** [comment]
I checked for mentions of fabric in my .bashrc file, and the paths all seem correct. If there's somewhere else I should check please let me know.

`
$ cat /home/user/.bashrc | grep -i fabric
export PATH=/home/user/ai/fabric/client/venv/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/ai/fabric/client
export PATH=/home/user/ai/fabric/.venv/bin:/home/user/ai/fabric/client/venv/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/ai/fabric/client:/home/user/.local/bin:/home/user/ai/fabric/client
alias fabric='/home/user/ai/fabric/.venv/bin/fabric'
alias fabric-api='/home/user/ai/fabric/.venv/bin/fabric-api'
alias fabric-webui='/home/user/ai/fabric/.venv/bin/fabric-webui'
alias yt='/home/user/ai/fabric/.venv/bin/yt'
alias write_semgrep_rule='fabric --pattern write_semgrep_rule'
...etc

`

**Comment by arcaneum** [comment]
> I'll look at the yt think, a pull request from yesterday kind of messed that up. As far as the other thing, do fabric --changeDefaultModel gpt-4-turbo-preview and that should fix it. maybe there's like a space in the config or something

Changing the default model does not seem to help:

![image](https://github.com/danielmiessler/fabric/assets/38038031/c1b6ae70-9006-4630-9ded-fce4f659d819)

![image](https://github.com/danielmiessler/fabric/assets/38038031/42e747fa-35b6-42bf-866a-37feaec5672d)

**Comment by xssdoctor** [comment]
OK I fixed the problem with the models just now. I'm still working on the helpers

**Comment by arcaneum** [comment]
@xssdoctor, Thank you for continuing to investigate this issue.
II completely deleted the cloned Fabric repository, uninstalled Poetry and did the cloning and setup from scratch again via pipx, but I am still getting the same errors as earlier for the models and yt:

```
(base) <<>> ~ % pbpaste | extract_wisdom                       
Error: Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

```
(base) <<>>@MacBook-Pro ~ % yt 'https://www.youtube.com/watch?v=wPEyyigh10g'
Traceback (most recent call last):
  File "/Users/<<>>/.local/bin/yt", line 7, in <module>
    from helper_files import main_yt
ModuleNotFoundError: No module named 'helper_files'
```

**Comment by natv** [comment]
Confirming all good!  I just did "git pull" (only) and it's working now :)   THANKS!!

**Comment by xssdoctor** [comment]
> @xssdoctor, Thank you for continuing to investigate this issue. I completely deleted the cloned Fabric repository, uninstalled Poetry and did the cloning and setup from scratch again via pipx, but I am still getting the same errors as earlier for the models and yt:
> 
> ```
> (base) <<>> ~ % pbpaste | extract_wisdom                       
> Error: Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
> Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
> ```
> 
>  ```
> (base) <<>>@MacBook-Pro ~ % yt 'https://www.youtube.com/watch?v=wPEyyigh10g'
> Traceback (most recent call last):
>   File "/Users/<<>>/.local/bin/yt", line 7, in <module>
>     from helper_files import main_yt
> ModuleNotFoundError: No module named 'helper_files'
> ```

can you try again now? just git pull then pipx upgrade fabric and see if yt works. I pushed some commits that will probably fix it

**Comment by arcaneum** [comment]
@xssdoctor It is partially working for me now,: **pbpaste | 'pattern'** works fine, but it's throwing errors for pretty much everything else from what I can see.


### 1. Not able to change model with  --changeDefaultModel. I am getting the following error:

**fabric --changeDefaultModel gpt-4-turbo-preview**

```
Traceback (most recent call last):
  File "/Users/<<>>/.local/bin/fabric", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/<<>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/fabric.py", line 80, in main
    Setup().default_model(args.changeDefaultModel)
  File "/Users/<<>>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 537, in default_model
    standalone = Standalone(args=[], pattern="")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<<>>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 49, in __init__
    if args.model:
       ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'
```

### 2. 'fabric --clear'  throws an error

`fabric: error: unrecognized arguments: --clear`

### 3. yt command does not throw an error anymore, but it does not seem to be extracting the transcript anymore either

**yt 'https://www.youtube.com/watch?v=lEXd6TXPw7E' | summarize**

`It seems there was an error in your request. Could you please provide the content you'd like summarized?`

**Comment by danielmiessler** [comment]
This should all be fixed now. Reinstall with --force and try again.

**Comment by danielmiessler** [comment]
Try now and submit again if it doesn't work. Should be all fixed!

**Comment by arcaneum** [comment]
@danielmiessler / @xssdoctor, Thank you very much for your help and patience. I can confirm YT command is working now.

However, --clear and --changeDefaultModel are still throwing errors. Will open a separate issue for this as you suggested 👍
