### ISSUE TITLE
[Bug]: Error doing pipx install

### ISSUE THREAD

**Issue by paulswail** [danielmiessler/fabric#246]
### What happened?

When I run the `pipx install .` step in the README install instructions, I get the below error related to pyperclip installation.

A few weeks ago, I had successfully installed an older version of fabric using the `setup.sh` file, which seems to be gone now. 
I'm on MacOS and installed `pipx` from brew just before attempting this. 
(I'm not a Python guy and the dev environment setup for it can be very confusing!)

### Version check

- [X] Yes I was.

### Relevant log output

```sh
pip seemed to fail to build package:
    pyperclip<2.0.0,>=1.8.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
    error: metadata-generation-failed
```

**Comment by xssdoctor** [comment]
OK I just changed the poetry config a little. Can you try again and tell me if you get the error? git pull then pipx upgrade fabric

**Comment by paulswail** [comment]
> OK I just changed the poetry config a little. Can you try again and tell me if you get the error? git pull then pipx upgrade fabric

Thanks @xssdoctor , but I'm still getting the same error after running `git pull && pipx install .` in the root of this repo. 

Running `pipx upgrade fabric` gives the following error, which I guess is expected since I haven't yet been able to install fabric via `pipx`: `Package is not installed. Expected to find /Users/paulswail/.local/pipx/venvs/fabric, but it does not exist.`

I'm wondering if there's some Python runtime version requirement for the install to work? I didn't see anything specific in the README, or if Poetry/pipx will automatically install/use the correct Python. I have `python@3.12` installed via Brew.

**Comment by paulswail** [comment]
Adding the verbose output if that helps:
```
pipx install . --verbose     
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/usr/local/opt/python@3.12/libexec/bin/python'
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /Users/paulswail/Code/Play/fabric
creating virtual environment...
pipx >(run_subprocess:168): running /usr/local/opt/python@3.12/libexec/bin/python -m venv --without-pip /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/paulswail/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw/bin/python --version
determining package name from '/Users/paulswail/Code/Play/fabric'...
pipx >(run_subprocess:168): running /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw/bin/python -m pip list --format=json
pipx >(run_subprocess:168): running /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw/bin/python -m pip --no-input install --no-dependencies /Users/paulswail/Code/Play/fabric
pipx >(run_subprocess:168): running /var/folders/ww/_989dvyx20g0k4pw3cnbdcs40000gn/T/tmpq5zrsbmw/bin/python -m pip list --format=json
pipx >(install_package_no_deps:323): Determined package name: fabric
pipx >(package_name_from_spec:382): Package name determined in 4.3s
creating virtual environment...
pipx >(run_subprocess:168): running /usr/local/opt/python@3.12/libexec/bin/python -m venv --without-pip /Users/paulswail/.local/pipx/venvs/fabric
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /Users/paulswail/.local/pipx/venvs/fabric/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/paulswail/.local/pipx/venvs/fabric/bin/python --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: /Users/paulswail/Code/Play/fabric
installing fabric from spec '/Users/paulswail/Code/Play/fabric'...
pipx >(run_subprocess:168): running /Users/paulswail/.local/pipx/venvs/fabric/bin/python -m pip --no-input install /Users/paulswail/Code/Play/fabric
pipx >(subprocess_post_check_handle_pip_error:327): '/Users/paulswail/.local/pipx/venvs/fabric/bin/python -m pip --no-input install /Users/paulswail/Code/Play/fabric' failed
pipx >(subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
    /Users/paulswail/.local/pipx/logs/cmd_2024-03-14_17.09.53_pip_errors.log

pipx >(analyze_pip_output:306): pip seemed to fail to build package:
    pyperclip<2.0.0,>=1.8.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
    error: metadata-generation-failed

pipx >(rmdir:55): removing directory /Users/paulswail/.local/pipx/venvs/fabric
Error installing fabric from spec
'/Users/paulswail/Code/Play/fabric'.
```

**Comment by xssdoctor** [comment]
ok try this pipx uninstall fabric then delete the fabric folder. then git clone it again. then go in and pipx install .

**Comment by paulswail** [comment]
> ok try this pipx uninstall fabric then delete the fabric folder. then git clone it again. then go in and pipx install .

That didn't work unfortunately.
I just discovered [this known issue](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) with Python 3.12 which affects pip. I'll try the suggested SO answer and report back.

**Comment by paulswail** [comment]
> > ok try this pipx uninstall fabric then delete the fabric folder. then git clone it again. then go in and pipx install .
> 
> That didn't work unfortunately. I just discovered [this known issue](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) with Python 3.12 which affects pip. I'll try the suggested SO answer and report back.

I couldn't get any of these suggested answers to work either (they either failed or had no effect).
For those of you running Fabric on MacOS, what version of Python are you using and did you install it via Homebrew or some other way?

**Comment by danielmiessler** [comment]
This should all be fixed in the latest update. Reinstall clean and you should be good.

**Comment by paulswail** [comment]
So I have now got the install working after trying several things (but I'm not sure exactly which one was the fix as I didn't re-attempt the pipx install after each, sorry! 🙈). These are the commands I tried:

```bash
brew update && brew upgrade pipx 

pip3 install . # install from pip3 instead of pipx

pip3 install --upgrade pip  
```

**Comment by s-smits** [comment]
@paulswail worked for me on 13.6, thank you!
