### ISSUE TITLE
[Bug]: yt.py not working on v1.2.0

### ISSUE THREAD

**Issue by Koesn** [danielmiessler/fabric#248]
### What happened?

I was doing pull transcript using `yt.py`, but nothing happened, even `yt.py -h` no output at all, but `ts.py` still works. The script on v1.1.3 works fine, back to this version for now. Also adding shebang line to have pt symbollic link like your tutorial on youtube.

### Version check

- [X] Yes I was.

**Comment by xssdoctor** [comment]
if you're using pipx everything should be in your path already yt, ts, whatever

**Comment by danielmiessler** [comment]
This is fixed now HT @xssdoctor
