### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by azukaar** [danielmiessler/fabric#25]
Hello! You should consider a docker file to allow people to easily deploy the server to theirs

**Comment by danielmiessler** [comment]
Yes, agreed. On the roadmap. Thank you!

**Comment by ab-in** [comment]
docker pull danielmiessler/fabric
Using default tag: latest
Error response from daemon: pull access denied for danielmiessler/fabric, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
