### ISSUE TITLE
[Bug]: Error When Trying to Run Anything: Windows 

### ISSUE THREAD

**Issue by Evilander** [danielmiessler/fabric#254]
### What happened?

Trying to use Fabric at all. Sorry - kind of new to all of it. 

Error: Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}
Error code: 400 - {'error': {'message': 'you must provide a model parameter', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Version check

- [X] Yes I was.

**Comment by fail-open** [comment]
Cant help if you dont show what you are running or how you are running it, your configs (with sensitive stuff removed) etc

**Comment by Evilander** [comment]
I am running windows 11, 12.1 cuda, anaconda.

I have all of my api keys setup. I haven't messed with any other configurations. 

pipx has been installed and updated.

**Comment by Gerkinfeltser** [comment]
Curious if its actually getting your config stuff. Windows doesn't function like mac/linux so the default ~/.config stuff doesn't work over there afaik.

**Comment by Evilander** [comment]
Alright, I'll test now using Ubuntu.

**Comment by hingsli** [comment]
<img width="854" alt="Screenshot 2024-03-16 at 23 25 16" src="https://github.com/danielmiessler/fabric/assets/87373132/1d828be5-0fc4-48d9-bcd5-a39b37475c0e">
I am using a Mac, and the same issue arises.
I can see my openai API key in my ~/.config

**Comment by xssdoctor** [comment]
i'll fix it in a little, but in the meantime you can just setDefaultModel and you won't get that error

**Comment by xssdoctor** [comment]
ok it should be fixed now. Can you try it and make sure it works?
