### ISSUE TITLE
[Question]: How to change the default model in powershell?

### ISSUE THREAD

**Issue by agathaaaaa** [danielmiessler/fabric#260]
### What is your question?

I did change the default model by the --changeDefaultModel and restart my terminal. However, it still will use the default model which is "gpt-4-turbo-preview". I also use the command --model. It required me to enter question: , but with this, it cannot recognize "Get-clipboard" the paste command in Powershell. How to solve this?
![image](https://github.com/danielmiessler/fabric/assets/143473563/b2922f59-f0fd-4ef3-8aa6-f426e6b0c18f)

**Comment by xssdoctor** [comment]
Ok I pushed a fix. Try now

**Comment by agathaaaaa** [comment]
> Ok I pushed a fix. Try now

Hi, I did the git pull and encounter the below error...
![image](https://github.com/danielmiessler/fabric/assets/143473563/af996a44-8dd5-48a1-b57d-dcdafa5c7dc7)

**Comment by xssdoctor** [comment]
the first error has to do with yt. you need to install ffmpeg. i dont know how to do it on windows. the second error only happens when your api key is not correctly entered. I see that you are on windows, and I cant test on windows. But I would check your api key in the .env file and see whats going on. Theres a chance something I did made a problem for windows users, but i cant really know what that is...sorry

**Comment by agathaaaaa** [comment]
Okiee~ But the main problem for the --changeDefaultModel and the "Get-clipboard" both now work for me. Thank you！

**Comment by xssdoctor** [comment]
oh its fixed! great!

**Comment by YorkyPoo** [comment]
I don't understand why I have those 2 issues and more.

PS C:\Program Files\Code\fabric> fabric --changeDefaultModel
usage: fabric [-h] [--text TEXT] [--copy] [--agents {trip_planner,ApiKeys}] [--output [OUTPUT]] [--stream] [--list]
              [--update] [--pattern PATTERN] [--setup] [--changeDefaultModel CHANGEDEFAULTMODEL] [--model MODEL]
              [--listmodels] [--remoteOllamaServer REMOTEOLLAMASERVER] [--context]
fabric: error: argument --changeDefaultModel: expected one argument
PS C:\Program Files\Code\fabric> fabric --model mistral:latest
Enter Question: Get-Clipboard | fabric --pattern extract_wisdom
 I'm sorry for the confusion, but it seems like you are trying to combine two different tools or commands - `Get-Clipboard` from PowerShell and `fabric` from the FabricJS library.

`Get-Clipboard` is a PowerShell cmdlet used to read the contents of the clipboard. On the other hand, `fabric` is a popular HTML5/JavaScript canvas library for working with text, images, and interactivity in the browser. The `extract_wisdom` pattern you mentioned doesn't seem to be related to either PowerShell or FabricJS.
