### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by codyburleson** [danielmiessler/fabric#267]
### What is your question?

After reading the documentation, I am still not clear how to install successfully. On the step, `pipx install .`, I get the following output. It seems to suggest that I am not using a high enough version of python. However, when I type `python --version` it says that I have Python version 3.12 (which I just upgraded to, in attempt to resolve this error...but clearly, that did not work). Any ideas? 

```
dev@LT0345762:~/repos/fabric$ pipx install .
ERROR: Ignored the following versions that require a different python version: 0.1.14 Requires-Python >=3.9,<4.0; 0.1.15 Requires-Python >=3.9,<4.0; 0.1.16 Requires-Python >=3.9,<4.0; 0.1.17 Requires-Python >=3.9,<4.0; 0.1.23 Requires-Python >=3.9,<4.0; 0.1.24 Requires-Python >=3.9,<4.0; 0.1.32 Requires-Python >=3.9,<4.0; 0.10.0 Requires-Python >=3.10,<4.0; 0.11.0 Requires-Python >=3.10,<4.0; 0.11.1 Requires-Python >=3.10,<4.0; 0.11.2 Requires-Python >=3.10,<4.0; 0.14.0 Requires-Python >=3.10,<=3.13; 0.14.0rc0 Requires-Python >=3.10,<3.12; 0.14.0rc1 Requires-Python >=3.10,<=3.13; 0.14.1 Requires-Python >=3.10,<=3.13; 0.14.3 Requires-Python >=3.10,<=3.13; 0.14.4 Requires-Python >=3.10,<=3.13; 0.16.0 Requires-Python >=3.10,<=3.13; 0.16.1 Requires-Python >=3.10,<=3.13; 0.16.2 Requires-Python >=3.10,<=3.13; 0.16.3 Requires-Python >=3.10,<=3.13; 0.17.0 Requires-Python >=3.10,<=3.13; 0.17.0rc0 Requires-Python >=3.10,<=3.13; 0.17.0rc1 Requires-Python >=3.10,<=3.13; 0.17.0rc2 Requires-Python >=3.10,<=3.13; 0.19.0 Requires-Python >=3.10,<=3.13; 0.22.0 Requires-Python >=3.10,<=3.13; 0.22.2 Requires-Python >=3.10,<=3.13; 0.22.3 Requires-Python >=3.10,<=3.13; 0.22.4 Requires-Python >=3.10,<=3.13; 0.22.5 Requires-Python >=3.10,<=3.13; 0.5.0 Requires-Python >=3.9,<4.0; 0.5.2 Requires-Python >=3.10,<4.0; 0.5.3 Requires-Python >=3.10,<4.0; 0.5.5 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement crewai<0.12.0,>=0.11.0 (from fabric) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for crewai<0.12.0,>=0.11.0
```

**Comment by Gaurav0203Shetty** [comment]
I think there might be a discrepancy between the Python version reported by `pipx` and the version reported by the `python --version` command. This can happen if `pipx` is not using the expected Python executable.

**Maybe try out these steps to resolve the issue:**

1) **Verify Python Version:** Run the following command to verify the Python version being used by `pipx`:
    `pipx --version`
    This command should provide information about the Python version being used by `pipx`. Make sure it matches the 
    version you expect.

2) **Check Python Installation:** Ensure that Python 3.12 is properly installed on your system and that it's accessible via the 
    python command. You can verify this by running:
    `python --version`
    
3) **Check pipx Configuration:** If `pipx` is configured to use a specific Python version, you might need to update its 
    configuration to point to Python 3.12. You can do this by running:
    `pipx upgrade pipx`
     This command will upgrade `pipx` and prompt you to select the Python version to use.

4) **Reinstall pipx:** If the above steps don't resolve the issue, you can try reinstalling `pipx` to ensure it's using the correct 
     Python version. You can do this by following the installation instructions for `pipx` for Python 3.12 from the official 
     documentation.

5) **Check Environment Variables:** Ensure that your system's PATH environment variable is correctly configured to point to 
     the directory containing Python 3.12. This ensures that the correct Python executable is used when invoking commands.
     
6) **Consult pipx Documentation:** If you're still encountering issues, consult the documentation or community forums for 
     pipx for additional troubleshooting steps or guidance.

By following these steps, you should be able to resolve the discrepancy between Python versions reported by `pipx` and the python command and successfully install the fabric package.

**Comment by codyburleson** [comment]
Thank you so much for you thoughtful answer. I will take these tips and get to work!

**Comment by Gaurav0203Shetty** [comment]
let me know if it helped you :)
