### ISSUE TITLE
[Feature request]: Add Ollama as a default question

### ISSUE THREAD

**Issue by iplayfast** [danielmiessler/fabric#268]
### What do you need?

I don't like using api keys, (just one more hurdle to jump) so I'd rather just use local models as much as possible. It's not clear from the readme how to use ollama, So two enhancements I guess.
1. when running fabric --setup as the question, using local model first. If [Y]es then narrow in on the popular choices (Ollama being #1 on my list. 
2. Update the readme to explain how to use ollama

**Comment by blade1981m** [comment]
I 100% agree that the readme needs to be updated with this information. I consider myself somewhat tech-savvy and am more than willing to watch some youtube videos or read some guides online, but even then I struggled to get this working with ollama. I did eventually get there though so will share my steps here in case it helps others:

Step 1: Install ollama - I did this with `sudo curl -fsSL https://ollama.com/install.sh | sh`
Step 2: Run ollama with a model specified - I did this with `ollama run mixtral` then ctrl+C to exit ollama 
Step 3 (optional): Verify fabric can see the model - `fabric --listmodels` This gave me the following output:-
```
GPT Models:

Local Models:
mixtral:latest

Claude Models:

Google Models:
```
Step 4: Set fabric to use that model as the default - `fabric --changeDefaultModel mixtral:latest`

Alternatively to Step 4, you could just pass that model name into any fabric command you run with `-m mixtral:latest` if you just want to use ollama in some cases.

**Comment by eugeis** [comment]
In the current Go variant of fabric, just run fabric --setup, configure the Ollama URL (e.g. copy/paste the example values), skip all other vendors and select the default model.
