### ISSUE TITLE
Use python poetry for managing dependencies in a deterministic fashion

### ISSUE THREAD

**Issue by agu3rra** [danielmiessler/fabric#27]
I noticed the repo contains a collection of `requirements.txt` file without pinned dependencies. This translates to every time a "build" (dependencies pull in the case of python) happens, a new set of dependencies will be resolved (time dependent), which could lead to issues reproducing the same exact dev environment on multiple machines.

I suggest using https://python-poetry.org/ to manage dependencies as it is really efficient and makes it clear which dependencies you rely on.

I volunteer to submit a PR if you're up for it. Just let me know @danielmiessler.

Cheers! \o/

PS: I assume you wish to manage the `client` and `server` dependencies separately. Please confirm if that's the case.

**Comment by AvikantSrivastava** [comment]
@agu3rra @danielmiessler 
can I work on this?

I have experience in setting up poetry from scratch on a codebase

**Comment by danielmiessler** [comment]
This sounds good but it's a bit beyond my Python dependency skills. Can you describe what all changes this would entail?

The prime directive of the project's codebase is simplicity. So if we can do this without adding complexity I'm happy to hear about it.

**Comment by agu3rra** [comment]
Hello @danielmiessler 
I've submitted the above PR #32 to show you what it will look like. I have a hunch the `sources` folder may not be required, but that was just a hunch. Let me know if not.

The PR has a screenshot of how the install and CLI command will look like.

I strive for simplicity and good laziness :)

**Comment by martin-luecke** [comment]
Why not simply pin the versions in `requirements.txt`?

**Comment by danielmiessler** [comment]
Thank you, we'll check out the PR!
