### ISSUE TITLE
[Question]: What is the source of information for Fabric LLM

### ISSUE THREAD

**Issue by agathaaaaa** [danielmiessler/fabric#270]
### The information source?

For example, in [create_network_threat_landscape], given the open ports and services, how can Fabric generate the description, risk, recommendation, One-Sentence-Summary, Trends, and Quotes without any extra information provided in the input? The same question applies to patterns such as analyze_threat_report, analyze_threat_report_trends, and create_threat_model. How does Fabric obtain the information necessary to generate the output?

**Comment by blade1981m** [comment]
Unless I am misunderstanding your question (or even the Fabric project itself), Fabric is not an LLM. It instead connects to other LLMs and it's patterns (such as create_network_threat_landscape) are just prompts fed to those LLMs. So the source of information would be whichever LLM you are using (and by extension the data sources of that LLM). So if you are using OpenAI API key then Open AI's GPT model (currently at time of this response GPT 4o) is the source of information.
