### ISSUE TITLE
[Bug]:  Error when running Fabric Setup - ModuleNotFoundError: No module named 'googleapiclient'

### ISSUE THREAD

**Issue by twelsh37** [danielmiessler/fabric#280]
### What happened?

I am running **Windows 11**, and I am running fabric from **WSL2** - **Ubuntu 22.04**
```text
Linux David 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
I had a working instal of a previous itteration of Fabric from a few months back.
I deleted this old version and the .git directories that were laying around. 

I then followed the readme file for the initial  install instructions 

All ran well. I closed the WSL terminal and then reopened it. I moved to the fabric directory and executed;
```text
fabric --setup
```
When I run this command I get the following Error/Traceback

```Python
twelsh@David:~/fabric$ fabric --setup
Traceback (most recent call last):
  File "/home/twelsh/.cache/pypoetry/virtualenvs/fabric-9ISSuZkT-py3.10/bin/fabric", line 3, in <module>
    from installer import cli
  File "/home/twelsh/fabric/installer/__init__.py", line 1, in <module>
    from .client.cli import main as cli, main_save, main_ts, main_yt
  File "/home/twelsh/fabric/installer/client/cli/__init__.py", line 2, in <module>
    from .yt import main as main_yt
  File "/home/twelsh/fabric/installer/client/cli/yt.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/twelsh/.cache/pypoetry/virtualenvs/fabric-9ISSuZkT-py3.10/bin/fabric", line 3, in <module>
    from installer import cli
  File "/home/twelsh/fabric/installer/__init__.py", line 1, in <module>
    from .client.cli import main as cli, main_save, main_ts, main_yt
  File "/home/twelsh/fabric/installer/client/cli/__init__.py", line 2, in <module>
    from .yt import main as main_yt
  File "/home/twelsh/fabric/installer/client/cli/yt.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
```

**Comment by lyddonb** [comment]
I hit the same on a mac after trying to do an update.

**Comment by hdavidviloria** [comment]
Same thing happened for me as well, deleted my old fabric folder and re-installed it using set up instructions to update (on a Mac) and it hits out with this error

**Comment by hdavidviloria** [comment]
Oh I was able to fix it after tinkering with it for a bit. I'm really not sure why it's like this, and why exactly it works but poetry seems to install the missing dependency?

Here are the exact commands I used:

1. I first deleted all the fabric executables (find where your executable is using commands: `which fabric`, `which fabric-api`, which fabric-webui and use `rm` to delete these executables), deleted the folder of which it was stored too, something like "fabric-BCnFkGJ9-py3.12/bin/fabric"


2. Unaliased all fabric commands (`unalias fabric` `unalias fabric-api` `unalias fabric-webui`)

3. Deleted the fabric folder that was cloned by git and re-cloned it, then `cd` into the newly-cloned directory

4. `pipx uninstall fabric` and then `pipx install .`       (inside the newly cloned fabric folder directory). 


5. and then use the command `poetry install` (inside the newly cloned fabric folder directory)

6. Install again, using `pipx install . --force` (inside the newly cloned fabric folder directory)

Then run 
`fabric -h`

See if it works and let me know! @lyddonb @twelsh37 

Maybe, in the future if ever, for the maintainers, official documentation on updating / re-installing fabric would be a great!

**Comment by xssdoctor** [comment]
You could have also just ran pipx upgrade fabric

**Comment by twelsh37** [comment]
> You could have also just ran pipx upgrade fabric

I tried this as it was the easiest to start with but it did not work for me.

```py
twelsh@David:~/fabric$ pipx upgrade fabric
fabric is already at latest version 1.2.0 (location: /home/twelsh/.local/pipx/venvs/fabric)
twelsh@David:~/fabric$ fabric -h
Traceback (most recent call last):
  File "/home/twelsh/.cache/pypoetry/virtualenvs/fabric-9ISSuZkT-py3.10/bin/fabric", line 3, in <module>
    from installer import cli
  File "/home/twelsh/fabric/installer/__init__.py", line 1, in <module>
    from .client.cli import main as cli, main_save, main_ts, main_yt
  File "/home/twelsh/fabric/installer/client/cli/__init__.py", line 2, in <module>
    from .yt import main as main_yt
  File "/home/twelsh/fabric/installer/client/cli/yt.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
```

**Comment by twelsh37** [comment]
> Oh I was able to fix it after tinkering with it for a bit. I'm really not sure why it's like this, and why exactly it works but poetry seems to install the missing dependency?
> 
> Here are the exact commands I used:
> 
> 1. I first deleted all the fabric executables (find where your executable is using commands: `which fabric`, `which fabric-api`, which fabric-webui and use `rm` to delete these executables), deleted the folder of which it was stored too, something like "fabric-BCnFkGJ9-py3.12/bin/fabric"
> 2. Unaliased all fabric commands (`unalias fabric` `unalias fabric-api` `unalias fabric-webui`)
> 3. Deleted the fabric folder that was cloned by git and re-cloned it, then `cd` into the newly-cloned directory
> 4. `pipx uninstall fabric` and then `pipx install .`       (inside the newly cloned fabric folder directory).
> 5. and then use the command `poetry install` (inside the newly cloned fabric folder directory)
> 6. Install again, using `pipx install . --force` (inside the newly cloned fabric folder directory)
> 
> Then run `fabric -h`
> 
> See if it works and let me know! @lyddonb @twelsh37
> 
> Maybe, in the future if ever, for the maintainers, official documentation on updating / re-installing fabric would be a great!

This worked almost perfectly. I had to carry out one cli command after pipx install .. That was to do
```
pipx lock --no-update
```
Having done this everything worked as expected.
