### ISSUE TITLE
[Bug]: yt transcript doesn't work

### ISSUE THREAD

**Issue by samuelgecik** [danielmiessler/fabric#294]
### What happened?

Hello, I've encountered this bug. When calling a yt command I'm getting this error: 

Traceback (most recent call last):
  File "/home/acc/.cache/pypoetry/virtualenvs/fabric-L4raEQJt-py3.11/bin/yt", line 3, in <module>
    from helpers.yt import main
ModuleNotFoundError: No module named 'helpers'

I've tried to find helpers file, but had no luck.
Thank you

### Version check

- [X] Yes I was.

**Comment by Gerkinfeltser** [comment]
Are you on windows? You may need to enable Developer Mode (Start > Developer Settings > Developer Mode) as I believe these are run via symlinks. I could be wrong (& have been many times in the past :P )

**Comment by samuelgecik** [comment]
No, I'm on Debian in WSL, however It probably had to do something with the update because I had an old version without pipx and when I updated this problem occurred. I made a clean install and now everything's working. Sorry for spamming.
