### ISSUE TITLE
[Bug]: pipx install . - yt does not resolve

### ISSUE THREAD

**Issue by c0def0x01** [danielmiessler/fabric#296]
### What happened?

I followed install instruction with pipx: `pipx install .` from within the fabric directory.  

Then I tried to use `yt` 'shortcut', however getting error:  
zsh: no such file or directory: `</path/to/>fabric/.venv/bin/ytalias` --> there is no `ytalias` in this directory.  

pipx also seems correctly setup (done through brew)
Running on macOS on intel MacBook Pro. 

`ts` works .... `save` and `fabric` as well. Issue seems limited to `yt`.

### Version check

- [X] Yes I was.

### Relevant log output

Updated today (26-Mar-2024): 

call `yt`
produces: 
Traceback (most recent call last):
  File "</path/to/>/fabric/.venv/bin/yt", line 3, in <module>
    from helpers.yt import main
ModuleNotFoundError: No module named 'helpers.yt'

### Relevant screenshots (optional)

n/a

**Comment by c0def0x01** [comment]
Identified malconfiguration - cleaned everything and have redone install… 
now everything works.

**Comment by vibora** [comment]
> Identified malconfiguration - cleaned everything and have redone install… now everything works.

Hi,
may I ask what you did to get rid of the problem? just because I have the very same problem.
