### ISSUE TITLE
Remove Virtual Environment Folder from "client" Directory

### ISSUE THREAD

**Issue by supunnadeera** [danielmiessler/fabric#30]
**Description:**
The "client" directory currently includes a "source" folder containing a virtual environment.

**Proposed Solution:**
1) Add "source/" to the .gitignore file to exclude the virtual environment folder from version control.
or
2) When creating virtual environments, let's adhere to the existing naming conventions in the .gitignore file, such as "env," "venv," and "ENV."

**Comment by danielmiessler** [comment]
Can you submit a PR for this?

**Comment by danielmiessler** [comment]
Closing to wait for PR.
