### ISSUE TITLE
[Question]: How do I change the OpenAI api key?

### ISSUE THREAD

**Issue by bgitit** [danielmiessler/fabric#309]
### What is your question?

I've searched discussions.  How do I change the OpenAI api key on windows11 device?

**Comment by xssdoctor** [comment]
Run --setup again

**Comment by bgitit** [comment]
ran setup and i'm getting this warning:  RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

**Comment by bgitit** [comment]
thanks for your help, this has been difficult for me as i am not able to do any of this but trying to fail fast and pick up just enough to get this installed somehow.  

So, i was able to add api keys for openai, claude, youtube and then run fabric --help, which shows me the options but also shows me this warning...which I'm sure I need to correct before moving forward:  RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
  
  instructions tell me to goto here: https://www.ffmpeg.org/download.html#build-windows
  
  I can download sourcecode or download the windows exe files build, I got both just in case.  SHould i add one of these to the fabric folder on my computer?

**Comment by kieferland** [comment]
I'm facing the fame issue currently on an M1 Pro w/ Sonoma 14.3.1

**Comment by ryankupk** [comment]
> So, i was able to add api keys for openai, claude, youtube and then run fabric --help, which shows me the options but also shows me this warning...which I'm sure I need to correct before moving forward: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

Are you running this in wsl? I just installed ffmpeg (and its dependencies) with `sudo apt install ffmpeg` and that resolved that error. I can't imagine what it actually would use ffmpeg for though, I would guess that regular usage of fabric wouldn't run into any potential issues that not having ffmpeg would cause. 

If you're not using wsl, then you would just need to install ffmpeg however you want and ensure that the directory that the executable is in is on your path.

**Comment by grayerbeard** [comment]
I downloaded ffmpeg to a folder and then added the location to the PATH in environmental values the restarted the terminal, (in my case also restarted Visual Studio) However I still cannot get the connection to OpenAI to work see my Issue Post. 

Editing Path  
<img width="502" alt="apic2" src="https://github.com/danielmiessler/fabric/assets/15215377/161710f6-2d18-4acd-9c41-400459c724b3">

Where I put ffmpeg
<img width="404" alt="apic1" src="https://github.com/danielmiessler/fabric/assets/15215377/8748e6c1-87c8-4dba-aee4-30e029069b15">
