### ISSUE TITLE
[Bug]: Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models' (Setup without openai api)

### ISSUE THREAD

**Issue by antonsapt4** [danielmiessler/fabric#311]
### What happened?

Fresh gitclone and installed following from the documentations using pipx using mac M2
- Do `fabric --setup` 
- OpenAI API Key: keep it blank as I dont have one 
- Claude API Key: add a valid and working claude API
- Youtube API Key: add valid and working youtube API

```
Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
```

but if try to do `--listmodels` it asking for OpenAI API with 401
```
(base) user@MacBook-Pro fabric % fabric --listmodels
/Users/aldi/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
(base) user@MacBook-Pro fabric % 
```

Really appreciate what went wrong and how to fix it I'm missing something

Thank you

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
This should be fixed now. Thank you for the submission!
