### ISSUE TITLE
[Bug]: Quickstart Step 5: pipx install: error: the following arguments are required: package_spec, Step 6, 7: zsh: command not found: fabric

### ISSUE THREAD

**Issue by CPAtoCybersecurity** [danielmiessler/fabric#316]
### What happened?

In following the quick start just now in a fresh Mac environment, I'm not sure what to try next after getting 

This error message on step 5 pipx install "pipx install: error: the following arguments are required: package_spec"
I try proceeding to step 6 and step 7 in the comment below and get "zsh: command not found: fabric" error messages.

Is there more I should be typing than "pipx install" in step 5, or anything else I can do to update this environment?  Thanks.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
sandbox@Mac0 week5 % # Clone Fabric to your computer
git clone https://github.com/danielmiessler/fabric.git
zsh: command not found: #
Cloning into 'fabric'...
remote: Enumerating objects: 6824, done.
remote: Counting objects: 100% (1003/1003), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 6824 (delta 872), reused 859 (delta 806), pack-reused 5821
Receiving objects: 100% (6824/6824), 150.48 MiB | 5.77 MiB/s, done.
Resolving deltas: 100% (3134/3134), done.
sandbox@Mac0 week5 % cd fabric
sandbox@Mac0 fabric % brew install pipx
==> Downloading https://formulae.brew.sh/api/formula.jws.json
###################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: pipx 1.5.0 is already installed and up-to-date.
To reinstall 1.5.0, run:
  brew reinstall pipx
sandbox@Mac0 fabric % pipx install
usage: pipx install [-h] [--quiet] [--verbose] [--include-deps] [--force] [--suffix SUFFIX]
                    [--python PYTHON] [--fetch-missing-python] [--preinstall PREINSTALL]
                    [--system-site-packages] [--index-url INDEX_URL] [--editable]
                    [--pip-args PIP_ARGS]
                    package_spec [package_spec ...]
pipx install: error: the following arguments are required: package_spec
```

**Comment by CPAtoCybersecurity** [comment]
Since the above says pipx is already installed, so perhaps that's not the issue, here are next steps where I get stuck:
sandbox@Mac0 fabric % fabric --setup
zsh: command not found: fabric
sandbox@Mac0 fabric % ls
LICENSE.txt     images          patterns        poetry.lock.bak setup.sh
README.md       installer       poetry.lock     pyproject.toml
sandbox@Mac0 fabric % fabric -h
zsh: command not found: fabric

**Comment by danielmiessler** [comment]
I would install zsh, oh-my-zsh, and homebrew. Make sure your python environment is healthy, and try again fresh. This is definitely some deep level core stuff with your env.

**Comment by CPAtoCybersecurity** [comment]
It worked!  Realized I was missing the “.” In step 5! 
“pipx install .”

Oh-my-zsh is a cool upgrade for me.
Many thanks.
