### ISSUE TITLE
[Feature request]: Use crewAI agents with a praisonAI simplification

### ISSUE THREAD

**Issue by AndresRojoInteracso** [danielmiessler/fabric#323]
### What do you need?

Checkout this [project](https://github.com/MervinPraison/PraisonAI) and this [issue](https://github.com/MervinPraison/PraisonAI/issues/17) to include in just one command an autogenerated crew from [CrewAI](https://github.com/joaomdmoura/crewAI) for a piped task 

Love your project and it values

**Comment by xssdoctor** [comment]
This is phenomenal! I'm going to look into this. Thank you!

**Comment by xssdoctor** [comment]
OK, so I just pushed a commit which uses praisonAI to create and utilize agents. its the --agents flag. Thank you so much for the recommendation. Please try it out and let me know if it can be better in any way, or if it's not working. It should work with the -m flag. all openai and ollama models but NOT claude.

**Comment by AndresRojoInteracso** [comment]
I could check earltier, but I leave a few comments at this [commit](https://github.com/danielmiessler/fabric/commit/eafc2df48c288d6a985e8fbee20c8c93b66ebe02#r140712125).

I see future in having a agent_patterns.yamls files to be able to refine the agents teams selecting models for each and tool for each agent and having mini teams for some tasks.

PS: I dont know why is not groq allready added to the model list, but for now there is a free API and praisonAI supported due to the openai schema
