### ISSUE TITLE
[Bug]: Cannot install on Ubuntu 20.04.6 LTS python 3.10.8

### ISSUE THREAD

**Issue by eugene-so** [danielmiessler/fabric#338]
### What happened?

I was unable to install the package using pipx

### Version check

- [X] Yes I was.

### Relevant log output

```shell
~/build/fabric$ pipx install .
ERROR: Ignored the following versions that require a different python version: 0.1.14 Requires-Python >=3.9,<4.0; 0.1.15 Requires-Python >=3.9,<4.0; 0.1.16 Requires-Python >=3.9,<4.0; 0.1.17 Requires-Python >=3.9,<4.0; 0.1.23 Requires-Python >=3.9,<4.0; 0.1.24 Requires-Python >=3.9,<4.0; 0.1.32 Requires-Python >=3.9,<4.0; 0.10.0 Requires-Python >=3.10,<4.0; 0.11.0 Requires-Python >=3.10,<4.0; 0.11.1 Requires-Python >=3.10,<4.0; 0.11.2 Requires-Python >=3.10,<4.0; 0.14.0 Requires-Python >=3.10,<=3.13; 0.14.0rc0 Requires-Python >=3.10,<3.12; 0.14.0rc1 Requires-Python >=3.10,<=3.13; 0.14.1 Requires-Python >=3.10,<=3.13; 0.14.3 Requires-Python >=3.10,<=3.13; 0.14.4 Requires-Python >=3.10,<=3.13; 0.16.0 Requires-Python >=3.10,<=3.13; 0.16.1 Requires-Python >=3.10,<=3.13; 0.16.2 Requires-Python >=3.10,<=3.13; 0.16.3 Requires-Python >=3.10,<=3.13; 0.17.0 Requires-Python >=3.10,<=3.13; 0.17.0rc0 Requires-Python >=3.10,<=3.13; 0.17.0rc1 Requires-Python >=3.10,<=3.13; 0.17.0rc2 Requires-Python >=3.10,<=3.13; 0.19.0 Requires-Python >=3.10,<=3.13; 0.22.0 Requires-Python >=3.10,<=3.13; 0.22.2 Requires-Python >=3.10,<=3.13; 0.22.3 Requires-Python >=3.10,<=3.13; 0.22.4 Requires-Python >=3.10,<=3.13; 0.22.5 Requires-Python >=3.10,<=3.13; 0.27.0 Requires-Python <=3.13,>=3.10; 0.27.0rc0 Requires-Python <=3.13,>=3.10; 0.27.0rc1 Requires-Python <=3.13,>=3.10; 0.27.0rc2 Requires-Python <=3.13,>=3.10; 0.27.0rc3 Requires-Python <=3.13,>=3.10; 0.27.1 Requires-Python <=3.13,>=3.10; 0.27.2 Requires-Python <=3.13,>=3.10; 0.28.0 Requires-Python <=3.13,>=3.10; 0.28.1 Requires-Python <=3.13,>=3.10; 0.28.2 Requires-Python <=3.13,>=3.10; 0.28.3 Requires-Python <=3.13,>=3.10; 0.28.4 Requires-Python <=3.13,>=3.10; 0.28.5 Requires-Python <=3.13,>=3.10; 0.28.6 Requires-Python <=3.13,>=3.10; 0.28.7 Requires-Python <=3.13,>=3.10; 0.28.8 Requires-Python <=3.13,>=3.10; 0.5.0 Requires-Python >=3.9,<4.0; 0.5.2 Requires-Python >=3.10,<4.0; 0.5.3 Requires-Python >=3.10,<4.0; 0.5.5 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement crewai<0.23.0,>=0.22.5 (from fabric) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for crewai<0.23.0,>=0.22.5
```

**Comment by eugene-so** [comment]
Verbose log:
pipx install . --verbose
pipx (mkdir:35): creating directory /home/eso/.local/pipx/venvs
pipx (run_pipx_command:125): Virtual Environment location is /home/eso/.local/pipx/venvs
pipx (_run:124): running /usr/bin/python3 -m venv /home/eso/.local/pipx/venvs
pipx (_run:124): running /home/eso/.local/pipx/venvs/bin/python -m pip install --upgrade pip
Collecting pip
  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-24.0
pipx (_run:124): running /home/eso/.local/pipx/venvs/bin/python -m pip install .
Processing /home/eso/build/fabric
donestalling build dependencies ... -
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting anthropic<0.19.0,>=0.18.1 (from fabric==1.2.0)
  Using cached anthropic-0.18.1-py3-none-any.whl.metadata (15 kB)
INFO: pip is looking at multiple versions of fabric to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.1.14 Requires-Python >=3.9,<4.0; 0.1.15 Requires-Python >=3.9,<4.0; 0.1.16 Requires-Python >=3.9,<4.0; 0.1.17 Requires-Python >=3.9,<4.0; 0.1.23 Requires-Python >=3.9,<4.0; 0.1.24 Requires-Python >=3.9,<4.0; 0.1.32 Requires-Python >=3.9,<4.0; 0.10.0 Requires-Python >=3.10,<4.0; 0.11.0 Requires-Python >=3.10,<4.0; 0.11.1 Requires-Python >=3.10,<4.0; 0.11.2 Requires-Python >=3.10,<4.0; 0.14.0 Requires-Python >=3.10,<=3.13; 0.14.0rc0 Requires-Python >=3.10,<3.12; 0.14.0rc1 Requires-Python >=3.10,<=3.13; 0.14.1 Requires-Python >=3.10,<=3.13; 0.14.3 Requires-Python >=3.10,<=3.13; 0.14.4 Requires-Python >=3.10,<=3.13; 0.16.0 Requires-Python >=3.10,<=3.13; 0.16.1 Requires-Python >=3.10,<=3.13; 0.16.2 Requires-Python >=3.10,<=3.13; 0.16.3 Requires-Python >=3.10,<=3.13; 0.17.0 Requires-Python >=3.10,<=3.13; 0.17.0rc0 Requires-Python >=3.10,<=3.13; 0.17.0rc1 Requires-Python >=3.10,<=3.13; 0.17.0rc2 Requires-Python >=3.10,<=3.13; 0.19.0 Requires-Python >=3.10,<=3.13; 0.22.0 Requires-Python >=3.10,<=3.13; 0.22.2 Requires-Python >=3.10,<=3.13; 0.22.3 Requires-Python >=3.10,<=3.13; 0.22.4 Requires-Python >=3.10,<=3.13; 0.22.5 Requires-Python >=3.10,<=3.13; 0.27.0 Requires-Python <=3.13,>=3.10; 0.27.0rc0 Requires-Python <=3.13,>=3.10; 0.27.0rc1 Requires-Python <=3.13,>=3.10; 0.27.0rc2 Requires-Python <=3.13,>=3.10; 0.27.0rc3 Requires-Python <=3.13,>=3.10; 0.27.1 Requires-Python <=3.13,>=3.10; 0.27.2 Requires-Python <=3.13,>=3.10; 0.28.0 Requires-Python <=3.13,>=3.10; 0.28.1 Requires-Python <=3.13,>=3.10; 0.28.2 Requires-Python <=3.13,>=3.10; 0.28.3 Requires-Python <=3.13,>=3.10; 0.28.4 Requires-Python <=3.13,>=3.10; 0.28.5 Requires-Python <=3.13,>=3.10; 0.28.6 Requires-Python <=3.13,>=3.10; 0.28.7 Requires-Python <=3.13,>=3.10; 0.28.8 Requires-Python <=3.13,>=3.10; 0.5.0 Requires-Python >=3.9,<4.0; 0.5.2 Requires-Python >=3.10,<4.0; 0.5.3 Requires-Python >=3.10,<4.0; 0.5.5 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement crewai<0.23.0,>=0.22.5 (from fabric) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for crewai<0.23.0,>=0.22.5
pipx (rmdir:25): removing directory /home/eso/.local/pipx/venvs
'/home/eso/.local/pipx/venvs/bin/python -m pip install .' failed

**Comment by xssdoctor** [comment]
The error message suggests that the problem is your python version. Which version of python are you running?

**Comment by eugene-so** [comment]
> The error message suggests that the problem is your python version. Which version of python are you running?

Python 3.10.8

**Comment by xssdoctor** [comment]
ok, so I can't reproduce this error. Is there a chance that your python environment includes another instance running < python 3.9? because this is the main error that you are getting 'ERROR: Ignored the following versions that require a different python version: 0.1.14 Requires-Python >=3.9'

**Comment by tibbon** [comment]
I'm seeing similar with Python 3.9.12 and running `pip install .`

**Comment by tibbon** [comment]
I was able to get it working on MacOS 14.4.1 with these steps:

```
virtualenv .venv
. .venv/bin/activate
pip3 install .
python --version
```

Using Python 3.12.2 from this. Python isn't my main language, so I know how to debug it and get it working, but can't quite rationalize why it wasn't working as expected before. I didn't use pipx on this, but I anticipate it would work similarly.

**Comment by eugene-so** [comment]
This still does not work for me.  Tried this command which should make sure the pipx virtual environment is also using the appropriate python version.

pipx install --python=$(which python) .

It seems to get past the original error msgs, but still does not install.

eso@eso-OptiPlex-7080:~/build/fabric$ python --version
Python 3.12.0
eso@eso-OptiPlex-7080:~/build/fabric$ pipx install --python=$(which python) .
Installing to existing directory '/home/eso/.local/pipx/venvs'
WARNING: typer 0.12.3 does not provide the extra 'all'
WARNING: typer 0.12.2 does not provide the extra 'all'
WARNING: typer 0.12.1 does not provide the extra 'all'
WARNING: typer 0.12.0 does not provide the extra 'all'
<string>:30: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Could not find package .. Is the name correct?
eso@eso-OptiPlex-7080:~/build/fabric$ fabric --setup
fabric: command not found
