### ISSUE TITLE
Misbehaviour with Claude Models or just User Error?

### ISSUE THREAD

**Issue by randoassuser** [danielmiessler/fabric#342]
### What happened?

Might need to reopen this issue, see my comment for details:
https://github.com/danielmiessler/fabric/issues/295#issuecomment-2052026266

I would appreciate help on this & thanks for the amazing work all of you pulled of already!

### Version check

- [X] Yes I was.

### Relevant log output

```shell
pt https://www.youtube.com/watch?v=8MIIeIa25tE&t=13s | fabric --stream --pattern extract_wisdom --output 'claudeOpusOutput.md' 
[1] 92815 Error: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.0: all messages must have non-empty content except for the optional final assistant message'}} Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.0: all messages must have non-empty content except for the optional final assistant message'}}
```

**Comment by xssdoctor** [comment]
hey so walk me through the issue. you cant pipe yt output to fabric if fabric is using claude?

**Comment by xssdoctor** [comment]
also, you cant use --stream with --output.

**Comment by randoassuser** [comment]
Exactly, also I'm not sure whether the prompt gets injected in the first place since the output does not seem to follow the system.md prompt, or am I wrong there? 

Also, did I use the --output flag in a wrong way? It saves an empty file even when there is a response from claude, works as expected with gpt-4

**Comment by randoassuser** [comment]
Following questions remain open for me:
- Why does fabric not complete the request to claude unless using additional --text input? And when doing it with --text, why does the response not refer to the transcript at all?
- Why does the --output save work with the same command when using gpt-4 but does not when using a claude model?

**Comment by xssdoctor** [comment]
I validated the --output problem with claude. I'll fix it soon. But I don't understand your other point. You can't use claude when you pipe into fabric?

**Comment by randoassuser** [comment]
> I validated the --output problem with claude. I'll fix it soon. But I don't understand your other point. You can't use claude when you pipe into fabric?

Yes, I can't pipe to fabric when using Claude. When I do that, it wants me to provide --text and does not include the piped in transcript

**Comment by xssdoctor** [comment]
Do me a favor. Show me the output of echo hello | fabric -s when your default model is a claude model

**Comment by xssdoctor** [comment]
btw i just fixed the --output and --copy with local models and with claude, but i'm still not understanding your other issue. When i pipe something to fabric it is working with claude and with local models just fine.
