### ISSUE TITLE
How to enable clip / pbpaste like functionality on Ubuntu server? 

### ISSUE THREAD

**Issue by legaltextai** [danielmiessler/fabric#344]
### What is your question?

I keep getting a display error with xclip. If anyone managed to get it run on the server , I would appreciate you advice. Thank you!

**Comment by ksylvan** [comment]
If you are seeing display errors (as in X display errors), you'll have to ensure that you can use X11 forwarding and use `ssh -X` when you login to that Ubuntu server.

If you have no X11, you can probably use `tmux`. https://github.com/tmux/tmux/wiki/Clipboard
