### ISSUE TITLE
[Feature request]: Support for Gemini

### ISSUE THREAD

**Issue by madchap** [danielmiessler/fabric#348]
### What do you need?

I'd like to use Gemini as the backend LLM.

**Comment by xssdoctor** [comment]
i'll be honest, I have gemini and I tried to use the api and literally could not figure out how to do it. I made an API key and could not use it. The api docs for gemini are very difficult. I'll try again and if i can figure it out i'll add to fabric

**Comment by xssdoctor** [comment]
I added gemini support. just add GOOGLE_API_KEY to your .env and you should be good to go

**Comment by caio-vinicius** [comment]
Hello! Here's the commit that added the GOOGLE_API_KEY support:

https://github.com/danielmiessler/fabric/commit/e2231b3504266bf143c8ec7094719372dad64889

Then, after install fabric, in the `fabric --setup` command it will ask for the Google API Key:

```bash
➜  fabric git:(main) fabric --setup
Welcome to Fabric. Let's get started.
Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter.

Please enter your claude API key. If you do not have one, or if you have already entered it, press enter.

Please enter your Google API key. If you do not have one, or if you have already entered it, press enter.

Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter.

Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
Creating empty environment file...
Environment file created.
```

Thanks @xssdoctor !
