### ISSUE TITLE
[Question]: The model `gpt-4-turbo-preview` does not exist

### ISSUE THREAD

**Issue by madchap** [danielmiessler/fabric#350]
### What is your question?

Hi,

I was under the impression gpt-4 should work? I understand that `-u` fabric resets the default model, not sure why that one in particular `gpt-4-turbo-preview`. I updated today.

When I `listmodels`, I only get gpt3 models and using them often results in `Error code: 429 - {'error': {'message': 'You exceeded your current quota...`. Nothing under Claude (which I believe may be right, given the very recent support for it).

I tried to pass `--model gpt-4-turbo` or `--model gpt-4` to no avail.

I may be missing something. Thanks for your pointers.

**Comment by xssdoctor** [comment]
From the error message, it seems as though You don't have enough money in your OpenAi account

**Comment by madchap** [comment]
OK, interesting, since I am subscribed to their "Plus" plan.

**Comment by xssdoctor** [comment]
That's only for the web service. You need to put money into your account to use the api

**Comment by madchap** [comment]
Thanks, what a cheap bastard I am. I'll try that again when I get that python module issue resolved on this other laptop.
I put $10 on it :)
