### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Deon588** [danielmiessler/fabric#358]
### What happened?

On Mac OS after installing Fabric when I run fabric -h or any pattern added to aliases e.g. pbpaste | analyze_claims --stream
I get this output:  

➜  github fabric -h
usage: fabric [-h] [--text TEXT] [--copy] [--agents] [--output [OUTPUT]]
              [--session [SESSION]] [--clearsession CLEARSESSION]
              [--sessionlog SESSIONLOG] [--listsessions] [--gui] [--stream]
              [--list] [--temp TEMP] [--top_p TOP_P]
              [--frequency_penalty FREQUENCY_PENALTY]
              [--presence_penalty PRESENCE_PENALTY] [--update]
              [--pattern PATTERN] [--setup]
              [--changeDefaultModel CHANGEDEFAULTMODEL] [--model MODEL]
              [--listmodels] [--remoteOllamaServer REMOTEOLLAMASERVER]
              [--context]
fabric: error: argument --model/-m: expected one argument
➜  github 

What is missing / what does this error mean?  fabric: error: argument --model/-m: expected one argument

I have setup API keys etc...

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
When you do --model you have to follow it with one of the models from `fabric --listmodels`.
