### ISSUE TITLE
[Bug]: pipx installation issues

### ISSUE THREAD

**Issue by gwpl** [danielmiessler/fabric#359]
### What happened?

form: https://github.com/danielmiessler/fabric/issues/272#issuecomment-2028275846

> Our installation issues have dropped massively since switching to pipx

Still does not install on ArchLinux:

### Version check

- [X] Yes I was.

### Relevant log output

```shell
$ pipx install https://github.com/danielmiessler/fabric.git
  ERROR: Cannot unpack file /tmp/pip-unpack-4mbdoai4/fabric.git (downloaded from /tmp/pip-req-build-969i88q9, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-969i88q9
Cannot determine package name from spec 'https://github.com/danielmiessler/fabric.git'. Check package
spec for errors.
```
```


### Relevant screenshots (optional)

_No response_

**Comment by xssdoctor** [comment]
Git clone first. Then go into the directory and type "pipx install ."

**Comment by gwpl** [comment]
I've found the problem!

I've forgotten that  `pipx install` will not recognize git repo URL automatically and one **needs to prefix** with `git+` , thereore:

```
# DOES NOT WORK:
# pipx install https://github.com/danielmiessler/fabric.git
# THIS WORKS:
pipx install git+https://github.com/danielmiessler/fabric.git
```
