### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by scaruslooner** [danielmiessler/fabric#360]
### What happened?

I was trying to use fabric with groq, when i ranned into "Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401". I was expecting it to work. I use my groq key when it asked for open ai key on fabric --setup.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
(fabric) C:\Users\camer\Documents\fabric>set OPENAI_MODEL_NAME=llama3-70b-8192

(fabric) C:\Users\camer\Documents\fabric>fabric --pattern summarize
Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

(fabric) C:\Users\camer\Documents\fabric>export OPENAI_API_BASE=https://api.groq.com/openai/v1
'export' is not recognized as an internal or external command,
operable program or batch file.

(fabric) C:\Users\camer\Documents\fabric>
(fabric) C:\Users\camer\Documents\fabric>export OPENAI_API_BASE=https://api.groq.com/openai/v1
'export' is not recognized as an internal or external command,
operable program or batch file.

(fabric) C:\Users\camer\Documents\fabric>
(fabric) C:\Users\camer\Documents\fabric>set OPENAI_API_BASE_URL=https://api.groq.com/openai/v1

(fabric) C:\Users\camer\Documents\fabric>
(fabric) C:\Users\camer\Documents\fabric>fabric --pattern summarize
Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

(fabric) C:\Users\camer\Documents\fabric>fabric --pattern summarize --model llama3-70b-8192
Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

### Relevant screenshots (optional)

![image](https://github.com/danielmiessler/fabric/assets/39450507/52b9f98e-6811-421c-be27-c8b926677def)

**Comment by xssdoctor** [comment]
It doesn't support groq. Do --listmodels toser what's supported

**Comment by scaruslooner** [comment]
Groq is not a model it hosts open source models. I'm pretty sure you can use groq thru OpenAI endpoints but I don't know how to do it. It has OpenAI compatibility [](https://console.groq.com/docs/openai)

![image](https://github.com/danielmiessler/fabric/assets/39450507/50106a59-ee8c-4459-851a-0cefc8ae081a)

**Comment by xssdoctor** [comment]
Fabric does not currently support groq, which is an llm created by x (formerly twitter). I'll probably add support in the future

**Comment by scaruslooner** [comment]
No the thing you are thinking about is grok is from x and im talking about groq are completely different!!

**Comment by MrAkber** [comment]
How can one change the OpenAI Base Url or at least add a second one to also add Groq's API key?
