### ISSUE TITLE
[Bug]:  broken link on github? quick start section

### ISSUE THREAD

**Issue by profetik-777** [danielmiessler/fabric#366]
### What happened?

On quickstart page, there was a hyperlink to the fabric client then got this: 

![image](https://github.com/danielmiessler/fabric/assets/112424307/b2ef65e1-7cca-4541-bebd-45769b57b3a9)

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

![image](https://github.com/danielmiessler/fabric/assets/112424307/5f77f680-e3c3-486e-a461-278a0c598900)

**Comment by danielmiessler** [comment]
We fixed this one in the Readme, thank you.
