### ISSUE TITLE
[Bug]: not recognizing key or chatgpt 4 a requirement? 

### ISSUE THREAD

**Issue by profetik-777** [danielmiessler/fabric#367]
### What happened?

Using ubuntu machine, trying to run this command: 

fabric pbpaste | analyze_claims

(I copied text from an article). 

Got the following output: 

usage: fabric [-h] [--text TEXT] [--copy] [--agents] [--output [OUTPUT]]
              [--session [SESSION]] [--clearsession CLEARSESSION]
              [--sessionlog SESSIONLOG] [--listsessions] [--gui] [--stream]
              [--list] [--temp TEMP] [--top_p TOP_P]
              [--frequency_penalty FREQUENCY_PENALTY]
              [--presence_penalty PRESENCE_PENALTY] [--update]
              [--pattern PATTERN] [--setup]
              [--changeDefaultModel CHANGEDEFAULTMODEL] [--model MODEL]
              [--listmodels] [--remoteOllamaServer REMOTEOLLAMASERVER]
              [--context]
fabric: error: unrecognized arguments: pbpaste
Error: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

### Version check

- [X] Yes I was.

**Comment by snafu4** [comment]
`pbpaste` is a MacOS thing.  You need to install xclip in ubuntu and set up an alias 
```
alias pbpaste='xclip -selection clipboard -o'
```
Also,

command should be 
```
pbpaste | analyze_claims
```

**Comment by xssdoctor** [comment]
Make sure you have money in your OpenAI api account l. If not you won't have access to gpt-4 preview

**Comment by profetik-777** [comment]
Thanks - should we include this in the "Quick Start" guide of the documentation @xssdoctor @danielmiessler , I can throw something in there if you want.

**Comment by profetik-777** [comment]
Closing until i verify. if something else comes up ill submit a new bug.
