### ISSUE TITLE
Token limit?

### ISSUE THREAD

**Issue by nexuslux** [danielmiessler/fabric#37]
How does this handle really long documents? 

(fabric) xxx@xxxx-MBA client % cat /Users/xxxx/Downloads/xxx\ xxx\ Story\ Building\ Contents/Synthesis_Report.md | fabric --pattern write_essay

Error: Error code: 429 - {'error': {'message': 'Request too large for gpt-4 in organization org-xVSxxxxxbU on tokens per min (TPM): Limit 40000, Requested 40939. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Error code: 429 - {'error': {'message': 'Request too large for gpt-4 in organization org-xVxxxxxxxxxxx on tokens per min (TPM): Limit 40000, Requested 40939. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by danielmiessler** [comment]
The curent max is 128,000, so you will need to summarize it or break it into pieces to get it below that.
