### ISSUE TITLE
[Bug]: when use yt to fetch the transcript of a video with non-latin languages like Chinese or Japanese, it will generate gibberish

### ISSUE THREAD

**Issue by CaeChao** [danielmiessler/fabric#370]
### What happened?

I was doing 
`yt --transcript --lang 'zh-Hant' $(youtube_url)`, 
 I was expecting to get the Chinese transcript from that video,
Instead I got gibberish generated:
![image](https://github.com/danielmiessler/fabric/assets/47220170/19acc708-7a62-44f4-86f9-16805d79c253)

I think it is related to this line(yt.py line 106):
`print(transcript_text.encode('utf-8').decode('unicode-escape'))`

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
We're fixing this in the next version of yt which is Go.
