### ISSUE TITLE
[Bug]: yt transcript broken?

### ISSUE THREAD

**Issue by nic0711** [danielmiessler/fabric#372]
### What happened?

I want fabric to summarize a YT Video with `"yt --transcript "https://www.youtube.com/watch?v=CbhoKt14qrE" | fabric -sp create_summary"`.

Actuall fabric (29.04.24)
local OLLAMA with dolphin-llama3:latest

The output looks like this:
```
# ONE SENTENCE SUMMARY:
Google's Gemma 2B, an 8-bit quantization model, has been tested for its performance using LM Studio. The model was evaluated based on six (%   "
```

Multiple times the same outcome - it stops after the first line.

Copying the transcript to clipboard gives this result:
```
pbpaste | fabric -sp create_summary
# One Sentence Summary:
The LM Studio's Google Gemma 2B model has been tested for its performance, accuracy, and usability. It scored a 2 out of 6 in responding six-c% 
```
or this:

```
pbpaste | fabric -sp summarize 
# ONE SENTENCE SUMMARY:
Google's Gemma 2B model shows potential for low-end machines, but falls short compared to higher-parameter models.

# MAIN POINTS:
1. Tested Google (%  
```     

Using OLLAMA directly (CLI) is working correctly.

Is this a bug in yt or fabric or ollama?

Thank you!

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
I think that's an LM studio issue...or Ollama.
