### ISSUE TITLE
Volunteer opportunities? 

### ISSUE THREAD

**Issue by profetik-777** [danielmiessler/fabric#38]
Hello, 

I have 3+ years of software project management experience. While I use openSUSE as my daily driver, I'm not a programmer or dev, so only limited technical experience. 

I am fascinated with your take on AI tools, and wanted to see if there are opportunities to volunteer and help the project out.

**Comment by danielmiessler** [comment]
Would love the help, but I think we need people to be coders in most cases. What were you thinking you could help with? It's best if you say what you think you could do rather than having us try to figure that out.

**Comment by danielmiessler** [comment]
Let me know when you have an idea.

**Comment by fzoric8** [comment]
Hi, 

Are there any Contribution guidelines, where can coders jump in maybe? :) 

Best, 
Filip
