### ISSUE TITLE
[Bug]: Fabric Uses OPENAI_API_KEY from .zshrc regardless of fabric --setup

### ISSUE THREAD

**Issue by osmirog** [danielmiessler/fabric#385]
### What happened?

I installed fabric on Ubuntu and ran fabric --setup, inserting my newly generated OPENAI API key. Any usage of fabric gave 401 Client Error: Unauthorized

I spent some time trying to find the problem, and when I realized that fabric could be using the global OPENAI_API_KEY variable from my .zshrc file instead of the one inserted in fabric --setup, I replaced that global OPENAI_API_KEY in .zshrc with a new one (the problem was that I revoked the old one, but imagine a situation where this variable is used for different apps). 

I reinstalled fabric from scratch, NOT inserting the key during fabric  --setup, and it worked, using the global variable. 

However, once this global variable is imported, I was not able to change it to another one, by inserting my API key in fabric --setup. I had to change the global variable in .zshrc, run 'source ~/.zshrc' and then 'fabric --setup' with empty API key fields.    

I propose to:
1) Clearly state in the documentation that fabric uses OPENAI_API_KEY global variable by default, if such a feature is needed.
2) Make the API key inserted during fabric --setup override the global variable and the previously inserted keys.

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
We're moving to managing keys differently in the next version. Thank you!
