### ISSUE TITLE
[Question]: How to authenticate with OpenRouter model server when running Fabric commands

### ISSUE THREAD

**Issue by Gerkinfeltser** [danielmiessler/fabric#391]
### What is your question?

Hello, I'm attempting to use OpenRouter as the model server for the Fabric command-line tool. I have set the `OPENAI_BASE_URL` environment variable to point to `https://openrouter.ai/api/v1` and am able to successfully list models available from Openrouter using the `fabric --listmodels` command. However, when I try to execute a command that requires communication with the OpenRouter server, I encounter an authentication error.

### Steps to Reproduce:
1) Set the environment variable `OPENAI_BASE_URL` to `https://openrouter.ai/api/v1`.
2) Run `fabric --listmodels` to confirm connectivity and list available models.
3) Attempt to run a Fabric command that interacts with OpenRouter, e.g., `echo "I like turtles" | fabric -p write_essay -m llama-3-8b-instruct:free`.

### Expected Behavior:
The command should execute successfully, with Fabric using the provided API key to authenticate with OpenRouter and process the request.

### Actual Behavior:
I receive the following error message:

```
Error: Error code: 401 - {'error': {'message': 'Missing Authentication header or invalid API key', 'code': 401}}
Error code: 401 - {'error': {'message': 'Missing Authentication header or invalid API key', 'code': 401}}
```

### Troubleshooting Steps Taken:
1) I have added the appropriate OpenRouter API key to the ~/.config/fabric/.env file with both OPENAI_API_KEY and OPENROUTER_API_KEY assignments.
2) I have verified that the API key is correct and has the necessary permissions on the OpenRouter platform.
3) I have ensured that there are no typos or syntax errors in the environment variable settings or in the commands being executed.

**Environment:**
**Operating System:** Windows 10
**Python version:** 3.11

Could you please guide me on how to properly configure Fabric to authenticate with OpenRouter's API? Am I missing a step or is there a known issue with integrating Fabric and OpenRouter?

Thank you for your assistance.

**Comment by MonkeyAndres** [comment]
Hello! I just got Fabric working, and I'd like to help with it.
1. Set env variables in `.config/fabric/.env`. You have to set `OPENAI_BASE_URL=https://openrouter.ai/api/v1` and `OPENAI_API_KEY` to your generated OpenRouter token.
2. As for the model, copy the model name from OpenRouter website. The model names outputed from `fabric --listmodels` are missing the first segment. For example, I'm using `DEFAULT_MODEL=meta-llama/llama-3-8b-instruct:free`

With those couple of points, you should up and running in no time.

**Comment by Gerkinfeltser** [comment]
Thanks so much for the instructions @MonkeyAndres!

I actually had all that setup but I see the issue was that I also had environmental variables for `OPENAI_API_KEY` that were different than what I had in the .env file, interfering with my inference. 😆

I greatly appreciate your assistance! ❤️

Though perhaps self evident to those more skilled than myself, perhaps the fabric documentation would benefit from a version of @MonkeyAndres's information.
