### ISSUE TITLE
`Feature` Add a GUI for a better user experience

### ISSUE THREAD

**Issue by GunniBusch** [danielmiessler/fabric#40]
Would it possible, to make a GUI version of the client?
It could feature elements that could for example help the user create task plans. Or it could allow users to also add files so the ai could use them as reference.

**Comment by danielmiessler** [comment]
I'm interested. What kind of client are you thinking?

**Comment by danielmiessler** [comment]
Closing for now.

**Comment by GunniBusch** [comment]
> I'm interested. What kind of client are you thinking?

Sorry for the late reply, but a way, to type the text, easily select the desired template, and maybe, connecting multiple prompts together like piping in Linux. Also features like tts would be nice
