### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by y3-rawat** [danielmiessler/fabric#401]
### What happened?

 fabric --text "Essay about the dog"
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'

don't know what happened 

### Version check

- [X] Yes I was.

**Comment by erichschroeter** [comment]
I get the same error when  trying to pip `yt` to fabric.

```
yt --transcript "<some Youtube link>" | fabric -sp extract_wisdom
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'
```

Is there some way to enable verbose debugging to dig further into this?

**Comment by bamit99** [comment]
I had to use the export command again within WSL to set API base URL\Key etc. before it started working again.

**Comment by erichschroeter** [comment]
> I had to use the export command again within WSL to set API base URL\Key etc. before it started working again.

Is this the result of me trying to use a self-hosted ollama LLM?

```
$ export OPENAI_BASE_URL=https://127.0.0.1:11444/v1/
$ export DEFAULT_MODEL="llama3"
$ export YOUTUBE_API_KEY="my-key"
$ yt --transcript "<some Youtube link>" | fabric -sp extract_wisdom
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'
```

**Comment by bamit99** [comment]
I'm using a Google API key during fabric --setup command. I only provide Deepseek API information while setting environment. I haven't tried with Ollama yet even though I'm running it. Check Ollama log to see if Fabric is making any connection. Also try and run YT command only to see if it is pulling the transcript properly before piping it into Fabric.

**Comment by erichschroeter** [comment]
> I'm using a Google API key during fabric --setup command. I only provide Deepseek API information while setting environment. I haven't tried with Ollama yet even though I'm running it. Check Ollama log to see if Fabric is making any connection. Also try and run YT command only to see if it is pulling the transcript properly before piping it into Fabric.

If I put `OPENAI_API_KEY=ollama` in my `~/.config/fabric/.env` I'm able to get some feedback that something is hitting my local ollama instance, but the error is:

```
Error: Connection error.
Connection error.
```

I event tried changing the command to `yt --transcript "<some Youtube link>" | fabric -sp extract_wisdom --remoteOllamaServer='http://localhost:11444'` but that still gets the same error. The ollama logs show that `/api/tags` API is being hit.

**Comment by bamit99** [comment]
Only found this while ts..I tried with Ollama on my machine and yes, only got the API messge or connection error but never recieved a response.

h__ps://knasmueller.net/running-fabric-locally-with-ollama

**Comment by danielmiessler** [comment]
Pretty sure this is WSL/Windows related. Should be fixed in upcoming Go version.

**Comment by ChrisSwanson** [comment]
I ran into this same issue on my mac and an ollama server, and after debugging further found that the model I was referencing was not available. I referenced the list from `fabric --listmodels` and found references to models with tags, updated my model argument  i.e. went from `--model llama` to `--model llama3:latest`, and was able to get this working.

**Comment by kzi90** [comment]
> Pretty sure this is WSL/Windows related. Should be fixed in upcoming Go version.

Same problem here in Ubuntu 22.04 (no WSL) just now after a fresh install of fabric:
kzi@Jellyfish:~$ fabric --text "Essay about something"
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'

**Comment by erichschroeter** [comment]
> I ran into this same issue on my mac and an ollama server, and after debugging further found that the model I was referencing was not available. I referenced the list from `fabric --listmodels` and found references to models with tags, updated my model argument i.e. went from `--model llama` to `--model llama3:latest`, and was able to get this working.

This worked for me too. Thanks!

For future reference, I ran ollama with `OLLAMA_MODELS="/usr/share/ollama/.ollama/models" OLLAMA_HOST=127.0.0.1:11444 ollama serve` in WSL2.
My full command was `yt --transcript "<some Youtube link>" | fabric -sp extract_wisdom --remoteOllamaServer='http://localhost:11444' --model llama3:latest`

**Comment by CyRamos** [comment]
> > I'm using a Google API key during fabric --setup command. I only provide Deepseek API information while setting environment. I haven't tried with Ollama yet even though I'm running it. Check Ollama log to see if Fabric is making any connection. Also try and run YT command only to see if it is pulling the transcript properly before piping it into Fabric.
> 
> If I put `OPENAI_API_KEY=ollama` in my `~/.config/fabric/.env` I'm able to get some feedback that something is hitting my local ollama instance, but the error is:
> 
> ```
> Error: Connection error.
> Connection error.
> ```
> 
> I event tried changing the command to `yt --transcript "<some Youtube link>" | fabric -sp extract_wisdom --remoteOllamaServer='http://localhost:11444'` but that still gets the same error. The ollama logs show that `/api/tags` API is being hit.


Hey
I use WSL without any ollama model only Claude API, I had the same error below:
```
Error: Connection error.
Connection error.
```

When I checked my `.env` file I noticed I had another part of `OpenAI API =""` so I deleted it.
from then until now I get the error:
```
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'
```

**Comment by melloc01** [comment]
> I ran into this same issue on my mac and an ollama server, and after debugging further found that the model I was referencing was not available. I referenced the list from `fabric --listmodels` and found references to models with tags, updated my model argument i.e. went from `--model llama` to `--model llama3:latest`, and was able to get this working.

Bingo! Thank you so much! This fixed it for me. MacOS @ M3 Max

I think there's a lack of error handling when the model is not found in the ollama server, I met this project this week but am willing to contribute cc @danielmiessler
