### ISSUE TITLE
[Bug]: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

### ISSUE THREAD

**Issue by Morriz** [danielmiessler/fabric#403]
### What happened?

In step 8 of the setup, when running `fabric --help` I get the following error:
```
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
```

I am using python 3.12

### Version check

- [X] Yes I was.

**Comment by ideologysec** [comment]
Do you have ffmpeg installed and in your $PATH...?

**Comment by danielmiessler** [comment]
Yes, just path issues.

**Comment by christrille** [comment]
Got this error on Mac:

- _RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work_

I installed ffmpeg and it worked fine: 

- _brew install ffmpeg_

**Comment by jasonagutierrez** [comment]
I'm running fabric in fresh install of WSL and I needed to
1) Install Python 3
-  `sudo apt update && sudo apt install python3 python3-pip`
2) Add Python to my PATH 
-  edit your ~/.bashrc file and adding the following line: export PATH="$PATH:/usr/bin/python3"
3) Reset the terminal
- `source ~/.bashrc`
4) Install FFMPEG
- `sudo apt  install ffmpeg`  # version 7:4.4.2-0ubuntu0.22.04.1

After these steps, I no longer received the error.
