### ISSUE TITLE
CLI Option to Select GPT Model Version - Client CLI

### ISSUE THREAD

**Issue by Gilgamesh555** [danielmiessler/fabric#41]
Hello, first off great work, I love the idea.

I have a suggestion, Currently, to switch between different versions of the GPT model, one needs to modify the code directly within the client folder. It would be highly beneficial if users could select the GPT model version directly from the command line interface (CLI) without needing to alter the code. 

Proposed Solution:

- Add a command-line interface (CLI) option that allows users to specify the GPT model version directly. This could look something like   --model -m [MODEL_NAME] to setup the GPT that will be used, --modellist to show the available list of models.

I can submit a PR if you agree with this enhancement.

Thanks.

**Comment by danielmiessler** [comment]
Yes please.
