### ISSUE TITLE
pipx installation error

### ISSUE THREAD

**Issue by gamercoder153** [danielmiessler/fabric#411]
I am using windows 10 WSL Ubuntu 
I installed and upgraded Python and pip and later installed Pipx and ran this cmd `cd fabric` and ran `pipx install .` 
![4 (1)](https://github.com/danielmiessler/fabric/assets/168166085/28282388-c9fd-4d0c-aa72-2506df4c8f91)

**Comment by epeuu** [comment]
Hey there,

I encountered the same problem, and the steps below resolved it for me.
Give them a try; they might work for you too.
Before you begin, restart the shell and try executing `fabric --setup`.

If that doesn't work, follow these steps:

`apt-get update`
`apt-get install --reinstall build-essential`
`apt-get install python3.12-dev`
`apt install python3-full`
`pipx install numpy`
`python3 -m pipx install chroma-hnswlib --include-deps`
`pipx install .`
`fabric --setup`

**Comment by gamercoder153** [comment]
can u tell me the order to do all this 

> Hey there,
> 
> I encountered the same problem, and the steps below resolved it for me. Give them a try; they might work for you too. Before you begin, restart the shell and try executing `fabric --setup`.
> 
> If that doesn't work, follow these steps:
> 
> `apt-get update` `apt-get install --reinstall build-essential` `apt-get install python3.12-dev` `apt install python3-full` `pipx install numpy` `python3 -m pipx install chroma-hnswlib --include-deps` `pipx install .` `fabric --setup`

**Comment by gamercoder153** [comment]
I ran all the code it was stuck in installation and then suddenly blue screen appears out of nowhere @epeuu

**Comment by epeuu** [comment]
@gamercoder153, I executed them exactly as I posted them, without encountering any issues on my
end.
You can also achieve this by running them individually or by attempting to
execute them with elevated privileges (i.e., using root access).

btw, could you share the error that you got?

**Comment by gamercoder153** [comment]
@epeuu Iam getting a lot of errors, firstly I activated wsl feature and then downloaded ubuntu from Microsoft store 
I cloned the repo and followed the installation instructions I was getting no pipx error so I installed pipx and then later when I run `pipx install .` its stuck on installation for few mins and then suddenly blue screen appears 

Note: I can install other packages like numpy using pipx

**Comment by gamercoder153** [comment]
> @epeuu Iam getting a lot of errors, firstly I activated wsl feature and then downloaded ubuntu from Microsoft store I cloned the repo and followed the installation instructions I was getting no pipx error so I installed pipx and then later when I run `pipx install .` its stuck on installation for few mins and then suddenly blue screen appears
> 
> Note: I can install other packages like numpy using pipx

@danielmiessler hey can u solve this?

**Comment by epeuu** [comment]
> @epeuu Iam getting a lot of errors, firstly I activated wsl feature and then downloaded ubuntu from Microsoft store I cloned the repo and followed the installation instructions I was getting no pipx error so I installed pipx and then later when I run `pipx install .` its stuck on installation for few mins and then suddenly blue screen appears
> 
> Note: I can install other packages like numpy using pipx

Based on your description, I'm unable to fully understand the situation or provide a solution because I haven't experienced this issue myself.

I have successfully installed Fabric on both Windows and WSL Ubuntu 24.04 LTS. However, I used a different method than you. I installed Ubuntu via WSL using the terminal command `wsl --install -d Ubuntu-24.04`. After the system installation, I updated and upgraded all necessary packages.

When I encountered issues with Fabric installation, I ran the commands I previously mentioned, which resolved the problem for me. I haven't experienced a blue screen on WSL Ubuntu, so I can't offer a specific solution for that.

My suggestion is to wait for about 20 minutes, then force shut down the system. After restarting, navigate to the Fabric folder and run `fabric --setup` again. It’s possible that everything will install correctly despite the blue screen, and you can continue from there.

**Comment by gamercoder153** [comment]
@epeuu Thanks for the reply, I will reinstall ubuntu using cmd and then run all the previous cmds u said in ubuntu 24.04 and try it again..
lets hope this time it works

**Comment by gamercoder153** [comment]
@epeuu hey one more question, are u using root

**Comment by epeuu** [comment]
> @epeuu hey one more question, are u using root

Unless there are exceptional circumstances or a package requires installation by
an administrator, I usually execute tasks with standard user permissions. However,
when necessary, I can temporarily assume root privileges for the purposes of
installing specific packages.

By the way, if you're relying solely on WSL for running Fabric, I recommend considering an alternative approach. Installing Fabric directly on your Windows machine can be a more
efficient and straightforward solution, allowing you to bypass potential issues related to WSL and run Fabric without requiring elevated privileges.

To install Fabric directly on your Windows machine, follow these steps:

1. Ensure that you have both Git and Python installed on your system.
2. Run PowerShell as an administrator.
3. Navigate to the preferred location.
4. `python -m pip install --upgrade pipx`
5. `git clone https://github.com/danielmiessler/fabric.git`
6. `cd fabric`
7. `python -m pipx install chroma-hnswlib --include-deps`
8. `pipx install numpy`
9. `pipx install .`
10. `fabric --setup`
Once you've completed these steps, you can test it afterwards.

**Comment by gamercoder153** [comment]
@epeuu I just now faced blue screen again using ubuntu wsl
I'll try to install directly onto my windows machine

**Comment by epeuu** [comment]
> @epeuu I just now faced blue screen again using ubuntu wsl I'll try to install directly onto my windows machine

About blue screen issue, I recommend checking out this [Windows forum thread](https://answers.microsoft.com/en-us/windows/forum/all/installing-wsl-leads-to-a-blue-screen-loop-how-can/a4b3fa3e-5b47-4f3e-a5bf-4054f0b3e83a). 
You might stumble upon a solution or helpful tip that can aid in resolving your problem.

**Comment by gamercoder153** [comment]
@epeuu thanks alot dude, I installed it and its working fine

**Comment by CyRamos** [comment]
I didn't read the comments, however please notice there is another [fabric ](https://www.fabfile.org/) (I have issues yesterday because I accidentally installed it instead)

**Comment by berataydin** [comment]
Same issue with Mac M3, applied all installation steps without failure but when I run the fabric --setup I've got command not found error.

**Comment by gru3zi** [comment]
@berataydin add pipx to your path and it works

**Comment by Mulodji** [comment]
Hi all,
I'm running into an Error running the following on my Linux machine(Ubuntu 22.04):
$pipx install .

The error message says that(see picture attached):
"Error: Command '['/home.../bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
'/usr/bin/python3 -m venv --clear /home/.../pipx/shared' failed

I can't figure out a solution to this error message. Can anyone, please shade some light to solve it?
Thanks !
![FABRIC_PIPX_Install_Error_Screenshot from 2024-05-29 19-15-35](https://github.com/danielmiessler/fabric/assets/28108633/13ebc434-dcd6-4298-bd12-e15dd0179d92)

**Comment by gamercoder153** [comment]
> Hey there,
> 
> I encountered the same problem, and the steps below resolved it for me. Give them a try; they might work for you too. Before you begin, restart the shell and try executing `fabric --setup`.
> 
> If that doesn't work, follow these steps:
> 
> `apt-get update` `apt-get install --reinstall build-essential` `apt-get install python3.12-dev` `apt install python3-full` `pipx install numpy` `python3 -m pipx install chroma-hnswlib --include-deps` `pipx install .` `fabric --setup`

as @epeuu said run all this commands freshly and it should work

**Comment by eugeis** [comment]
Please consider to use current Go based release.
