### ISSUE TITLE
[Question]: How to Delete Unused API-Key?

### ISSUE THREAD

**Issue by CyRamos** [danielmiessler/fabric#425]
### What is your question?

Hey
I accidentally insert my Claude API key in OpenAI Key on the setup process. 
I can't find where to revoke this because whenever I re-setup the proceed when I 'Enter' Empty Value it doesn't delete the previous Key.
Now I'm stuck  and get
`Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401`

Tried to search where the API key is stored in the code, but If I understood correctly it stored as a custom variable.
I'd like for some guideness how to proccedd. 
Thanks ahead :)

**Comment by mrehanabbasi** [comment]
It's stored in the `~/.config/fabric/.env` file.

**Comment by CyRamos** [comment]
Thank you @mrehanabbasi

**Comment by Brandon5437** [comment]
> It's stored in the `~/.config/fabric/.env` file.

Where do I find this? I also have an api issue ( I pasted my YouTube API key into my Google API parameters.

(sorry, a bit of a noob to Fabric)

**Comment by CyRamos** [comment]
> > It's stored in the `~/.config/fabric/.env` file.
> 
> Where do I find this? I also have an api issue ( I pasted my YouTube API key into my Google API parameters.
> 
> (sorry, a bit of a noob to Fabric)

Hey :) 
Not familiar with your level experience so sorry if my explaining is gonna be to extra noob or something. 
do you use Linux Shell or WSL?
if you are you could go to home directory, then edit the file from there by navigate the directory location > file. 

`cd` - without any parameter - it will go to home directory
`cat ~/.config/fabric/.env` - this will only show you the file content.
`sudo nano ~/.config/fabric/.env` - will open editor inside the terminal that you could edit the file from there

incase you downloaded fabric in your regular cmd / PowerShell
I'll guess it will be familiar because I  see in my home folder another '.config' folder for another application.
`cd `- same command also works here to get to your home directory
`dir` - to list your current files in your current directory you're in.
`cd .config` - to navigate into config folder
`explorer .` - WITH THE DOT - to open the file explorer in the current folder you're in the PowerShell.
Then you could just open it with notepad or something..

and if you are still struggle to find it , maybe try to  download 'Everything' and locate the file from there
![image](https://github.com/user-attachments/assets/da34f9ff-a92f-40c0-959a-0ede71e68723)
