### ISSUE TITLE
[Bug]: Mac Issues with Remote Server

### ISSUE THREAD

**Issue by gru3zi** [danielmiessler/fabric#431]
### What happened?

Im getting an error on my mac and i'm not sure if its intended or not. Doing some testing and its not working fully...

Variations of errors I get. 

- Error: Client error '404 Not Found' for url 'http://192.168.10.86:11434/models 
- Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'

Setup commands in order

1. pipx install .
2. fabric --setup

3. export OPENAI_BASE_URL=https://192.168.10.86:11434/
4. export DEFAULT_MODEL="llama3"
5. export OPENAI_API_KEY="NULL"

I am able to list models and run commands only when specifying a remote server and model but the .env file has to be empty. 

![2024-05-28_23-23](https://github.com/danielmiessler/fabric/assets/44057919/c974e889-6f0a-4ca6-be47-5da9fe482f9b)

![2024-05-28_23-32](https://github.com/danielmiessler/fabric/assets/44057919/69e97257-ee8c-44ff-9b8f-a2e204d9da64)

Doesnt work when I dont specify a model either.

![2024-05-28_23-39](https://github.com/danielmiessler/fabric/assets/44057919/b6a4e635-b4a7-4141-baed-0aee1f1cd057)

if the .env file is populated with the following things I get a different error

I checked my env file and it was still empty despite running the export commands. I had to add these manually but it still does not work

![image](https://github.com/danielmiessler/fabric/assets/44057919/4cc7597c-1304-4c59-bad0-9e83000e7556)

![image](https://github.com/danielmiessler/fabric/assets/44057919/e5dbbdff-4fa3-4b1b-91d1-36b9bcbd18a9)

Is there a way to get it working without having to specify the remote server and model as its obviously troublesome to have to type that out each time.

Thanks in advance for any help.

### Version check

- [X] Yes I was.

**Comment by CyRamos** [comment]
Hey, I'm also get 
'NoneType' object has no attribute 'chat' error. 

OS: Windows 11 Pro
Running in WSL
just installed fabric.

thanks ahead

**Comment by kjpou1** [comment]
Am getting the error as well.  This seems to be caused when there is no OpenAI API key in the `.env` file after setup.

**Comment by gru3zi** [comment]
There also seems to be an issue with not being able to connect to Ollama via the gui.

![image](https://github.com/danielmiessler/fabric/assets/44057919/d8c39eed-2ad9-4ae7-95aa-0648beb33ab0)

**Comment by felipeumpierre** [comment]
I was able to "fix" the mentioned issue by adding the following content under `.config/fabric/.env`

```bash
OPENAI_API_KEY=NULL
CLAUDE_API_KEY=NULL
GOOGLE_API_KEY=NULL
```

Replacing the previous content that had just `#No API key set`.

**Comment by felipeumpierre** [comment]
@gru3zi I was able to execute the model from my ollama without specifying the address to the API.

<img width="168" alt="image" src="https://github.com/danielmiessler/fabric/assets/612696/aac65750-1da7-4f76-8a71-883479be4aca">

and I am able to run this for example:

<img width="847" alt="image" src="https://github.com/danielmiessler/fabric/assets/612696/06fb9a24-258f-48a7-83c4-7056bef2d9ba">

This is ollama's running models
<img width="607" alt="image" src="https://github.com/danielmiessler/fabric/assets/612696/73bc3f80-8e40-4132-b3a0-1f9d8ea379c0">

To mention that I am running from my local machine and not a remote machine. Maybe this is the difference between your issue and the way how I fixed the problem on my side.

**Comment by danielmiessler** [comment]
Thank you for this, and this will be much better in the new Go version in a couple of weeks!

**Comment by cl93a** [comment]
Anyone able to get this working with an actual remote Ollama server on Mac? Whatever I try, even using   --remoteOllamaServer, it keeps resulting into "Client error '404 Not Found' for url '.../v1/models'. The local server url works in other projects without issue, but not with Fabric. Ollama is also the latest version. No clue how to fix it.

**Comment by gru3zi** [comment]
> Anyone able to get this working with an actual remote Ollama server on Mac? Whatever I try, even using   --remoteOllamaServer, it keeps resulting into "Client error '404 Not Found' for url '.../v1/models'. The local server url works in other projects without issue, but not with Fabric. Ollama is also the latest version. No clue how to fix it.

@cl93a just have a blank env file and the command will work fine.

**Comment by DmacMcgreg** [comment]
I have done the above and I'm still getting 404

**Comment by DmacMcgreg** [comment]
Got it working.

1. vim ~/.config/fabric/.env
2. add the following: (Replacing the previous content that had just #No API key set.)
```
OPENAI_API_KEY="NULL"
OPENAI_BASE_URL=https://127.0.0.1:11434/v1/
CLAUDE_API_KEY="NULL"
GOOGLE_API_KEY="NULL"
```

Should work now.
The last one that worked for me was making sure OPENAI_BASE_URL was https not http even if it is localhost...

Make sure to unset your local variables in case you 'exported' them in one of the earlier steps so that it uses the .env file.
eg: `unset OPENAI_BASE_URL`

**Comment by gru3zi** [comment]
@DmacMcgreg This doesnt work on a remote server. Im getting a connection error.
