### ISSUE TITLE
[Question]: Recommended model to use

### ISSUE THREAD

**Issue by presidenten** [danielmiessler/fabric#432]
### What is your question?

I have tried with a few local models in ollama with varying results.

Which model is the highest recommended one? Is it gpt4o? Or any of the anthropic or google models with higher context length?

And if I run locally is it the instruct models that I should use, or the chat one?

**Comment by fabioyagui** [comment]
Hello, I think gpt4o is a good option as it is the newest version, and obviously, if you find it advantageous to pay for API usage. In my case, I use Llama3 8b [locally] and find it quite satisfactory if your graphics card can handle it. I can run Phi3 with 14b, but personally, I find that Llama3 provides better responses.
