### ISSUE TITLE
[Bug]: fabric --setup fails if .bashrc or .zshrc are links

### ISSUE THREAD

**Issue by 1984-mike** [danielmiessler/fabric#433]
### What happened?

I use nix home manager to manage dot files, so .bashrc and .zshrc are links

```
.bashrc ⇒ /nix/store/kqrgijykyspnqika7m4a3hvrijcss3vv-home-manager-files/.bashrc
.zshrc ⇒ /nix/store/kqrgijykyspnqika7m4a3hvrijcss3vv-home-manager-files/.zshrc
```
--setup is unable to write to these files and then fails, and .config/fabric/fabric-bootstrap.inc is not written

If unable to write either of these files could we display message saying please update .bashrc or .zshrc and add the following
```
if [ -f "~/.config/fabric/fabric-bootstrap.inc" ]; then . "~/.config/fabric/fabric-bootstrap.inc"; fi
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
fabric --setup
Welcome to Fabric. Let's get started.
Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter.

Please enter your claude API key. If you do not have one, or if you have already entered it, press enter.


Please enter your Google API key. If you do not have one, or if you have already entered it, press enter.


Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter.


Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
Traceback (most recent call last):
  File "/home/mike/.local/bin/fabric", line 8, in <module>
    sys.exit(cli())
  File "/home/mike/.local/pipx/venvs/fabric/lib/python3.10/site-packages/installer/client/cli/fabric.py", line 86, in main
    Setup().run()
  File "/home/mike/.local/pipx/venvs/fabric/lib/python3.10/site-packages/installer/client/cli/utils.py", line 803, in run
    self.update_shconfigs()
  File "/home/mike/.local/pipx/venvs/fabric/lib/python3.10/site-packages/installer/client/cli/utils.py", line 618, in update_shconfigs
    with open(config, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/mike/.zshrc'
```

**Comment by picografix** [comment]
Can you try running it with sudo access? I tried it with linked files (without nix) and it was working fine

**Comment by robupshon** [comment]
Yes using sudo works, need to specify fabric path

> ❯ sudo fabric --setup
sudo: fabric: command not found
❯ which fabric
/home/mike/.local/bin/fabric
❯ sudo /home/mike/.local/bin/fabric --setup
Welcome to Fabric. Let's get started.
Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter.
>
>Please enter your claude API key. If you do not have one, or if you have already entered it, press enter.
>
>
>Please enter your Google API key. If you do not have one, or if you have already entered it, press enter.
>
>
>Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter.
>
>
>Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
Creating empty environment file...
Environment file created.

**Comment by 1984-mike** [comment]
Yes using sudo works, but need to specify the path of fabric

❯ sudo fabric --setup
sudo: fabric: command not found
❯ which fabric
/home/mike/.local/bin/fabric
❯ sudo /home/mike/.local/bin/fabric --setup
Welcome to Fabric. Let's get started.
Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter.

Please enter your claude API key. If you do not have one, or if you have already entered it, press enter.


Please enter your Google API key. If you do not have one, or if you have already entered it, press enter.


Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter.


Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
Creating empty environment file...
Environment file created.

**Comment by danielmiessler** [comment]
Awesome, thank you.

**Comment by IslamInGitHub** [comment]
Gentlemen, I face access permission problem at the last step when it comes to downloading and populating Patterns .. 

_open /var/folders/3g/dl21wsgd46q6lrz8k3rwk3440000gn/T/patterns/agility_story/system.md: permission denied_

Some general online answers was suggesting to use SSH instead of HTTPS in cloning the project files.
