### ISSUE TITLE
Mac install issues

### ISSUE THREAD

**Issue by Tomas622** [danielmiessler/fabric#434]
### What is your question?

I'm trying to get Fabric set up on a Macbook, but it's not wanting to work at all. Whenever I try to run `fabric --setup`, ZSH just returns that the command doesn't exist. I've cloned the repo and done `pipx install .`, and I've tried to install it with regular pip too. Any advice?

**Comment by CyRamos** [comment]
I know it's a very generic question, but did you run `pipx install .` from the folder fabric is cloned? make sure you need to run it from the folder itself

**Comment by presidenten** [comment]
@Tomas622 not sure if its needed, but have you installed xcode cli tools with `xcode-select --install` and accepted the xcode eula?

**Comment by konstantinosbotonakis** [comment]
Same here
After `pipx install .`
![image](https://github.com/danielmiessler/fabric/assets/37538071/efc859f2-beef-4d89-85f4-85ece16d2cba)

xcode eula acceptance isn't an issue here
![image](https://github.com/danielmiessler/fabric/assets/37538071/81f7d2b4-b08c-409a-a52b-cfb937be04a0)

**Comment by konstantinosbotonakis** [comment]
ok found the solution here.

Tag @Tomas622 for visibility.

Run the command:
`pipx ensurepath`

then close the terminal window and re-open it.
Then run `fabric --setup` and it will work.

**Comment by andywoodruff6** [comment]
I was having the same issue as OP and `pipx ensurepath` solved the issue.
