### ISSUE TITLE
[Question]: Unable to install on Mac

### ISSUE THREAD

**Issue by AhsanT** [danielmiessler/fabric#439]
### What is your question?

I followed the instructions but unable to install fabric on Mac. 

"
Fatal error from pip prevented installation. Full pip output in file:
    /Users/.local/pipx/logs/cmd_----_pip_errors.log
pip failed to build package:
    chroma-hnswlib

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=14'
    RuntimeError: Unsupported compiler -- at least C++11 support is needed!

Error installing fabric from spec '/Users/git/fabric'. 
"

I checked C++ compiler and it is installed on my machine. 

Any suggestions ? thanks.

**Comment by presidenten** [comment]
@AhsanT Im on macos 14.5 and just installed it yesterday. 

Which os version are you on, and have you installed xcode cli tools with `xcode-select --install` and approved xcode eula?

**Comment by AhsanT** [comment]
Updated the Xcode and it worked, thanks for your help :)
