### ISSUE TITLE
[Question]: URLs

### ISSUE THREAD

**Issue by DustyPolk** [danielmiessler/fabric#442]
### What is your question?

Is there a way to scrape data from a website similar to using the yt --transcript command?

**Comment by MichaelCade** [comment]
Have you tried running a curl command? I have tried against markdown file url 

`curl --silent --show-error https://raw.githubusercontent.com/MichaelCade/90DaysOfDevOps/main/2022/Days/day01.md | fabric --pattern summarize --model mistral:instruct --stream`

**Comment by bowuguan** [comment]
动 know
