### ISSUE TITLE
[Bug]: Error: The `response.parts` quick accessor only works for a single candidate, but none were returned

### ISSUE THREAD

**Issue by superclarkk** [danielmiessler/fabric#445]
### What happened?

I'm not sure if this is a bug, or a user issue. If it's not a bug, then hopefully it will still help people who run into this issue.

Earlier today, fabric was working well on my system, using the Gemini API. Since then, I reinstalled ollama to update it to the latest version, and installed some models. I'm not sure if that's related. The ollama models work, using the `fabric -m` option.  I did not change the default fabric model from Gemini.

However, when using the summarize pattern now, it returns the following error:

```
Error: The `response.parts` quick accessor only works for a single candidate, but none were returned. Check the `response.prompt_feedback` to see if the prompt was blocked.
```

The problem I have is, despite searching the readme, issues and discussions, I don't know how to inspect response.prompt_feedback, check the log, debug a query, and I don't know what the terms, "candidate" or "quick accessor" mean.

Any help would be appreciated.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
Where can I find this (the log)?
```

**Comment by danielmiessler** [comment]
Yeah this is a strange quirk of the backend model. Not sure when that'll get fixed.

**Comment by superclarkk** [comment]
OK, but at the very least, there's a documentation issue. What are the definitions of the following?

What is a "candidate"?
What is a "quick accessor"
What is `prompt_feedback`? How do you inspect it within fabric?
How do you debug a request?
How do you enable and check the log?
Is this "quirk" only with Gemini?
Who's responsibility is it to fix it? Google's?
