### ISSUE TITLE
[Question]: I have ollama installed (locally and remotely) - still stuck - probably some dependence on API_KEY

### ISSUE THREAD

**Issue by fmotta** [danielmiessler/fabric#448]
### What is your question?

[Question]: I have ollama installed (locally and remotely) - 

After reading the documentation, I am still not clear how to get fabric working.

I tried this, this: pbpaste | fabric --stream  --remoteOllamaServer $OLLAMA_HOST --model llava  --pattern analyze_claims

And I got:
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'

echo $OLLAMA_HOST
192.168.1.178

~$ ollama list
NAME                            ID              SIZE    MODIFIED
llama2-uncensored:latest        44040b922233    3.8 GB  6 hours ago
llama3:latest                   365c0bd3c000    4.7 GB  2 days ago
llava:latest                    8dd30f6b0cb1    4.7 GB  3 days ago
dolphin-mistral:latest          5dc8c5a2be65    4.1 GB  3 days ago
nomic-embed-text:latest         0a109f422b47    274 MB  3 days ago

Windows 10 WSL Ubuntu 20.04

How do I get past this ?

**Comment by snafu4** [comment]
Try

pbpaste | fabric --stream --model llava:latest --pattern analyze_claims

Neil Greisman
***@***.***
416-277-8907

**Comment by fmotta** [comment]
> pbpaste | fabric --stream --model llava:latest --pattern analyze_claims

Thanks!
This seemed to intuit my use of ollama it seems. :)

It is interesting to see the difference in results by changing llava with llama2-uncensiored.

Oddly llava did far more and seemed to abide by the pattern and llama2-uncensored just informs about the story (cut fragment from hitchhikers guide wiki)

**Comment by snafu4** [comment]
Np.

Not surprisingly, the different models are ‘good’ at different things.

Other than the models with suffixes like ‘code’ or ‘Python’, I wonder if there is a website somewhere that explicitly states what a given model is good (and not good) at providing information on.
