### ISSUE TITLE
[Question]: Possibility to use compiled binary instead of installing with pipx?

### ISSUE THREAD

**Issue by pycanis** [danielmiessler/fabric#465]
### What is your question?

As the title says, I don't want to install pipx just to install fabric. Is it possible to just use a fabric binary?

**Comment by ideologysec** [comment]
Per the Note on the front page dated May 23 2024:

"We will be switching Fabric to Go in a few weeks to avoid all the installation issues with Python. The Go version will be dead-simple to install and will be even faster. Plus easier to update. We already have it working thanks to the heroic efforts of @xssdoctor, and we're just working on testing now! Stay tuned for more info on the release date!"
