### ISSUE TITLE
[Question]: correct use of context.md (-c) for language change

### ISSUE THREAD

**Issue by julliannailluj** [danielmiessler/fabric#475]
### What is your question?

In order to get answers in French, I created a context.md file, located in ~/.config/fabric. It contains this simple instruction: "Please answer in French.". 

Its effectiveness is pretty random, I wonder if i'm using it correctly. Here is an example of how I use it:
yt --transcript https://www.youtube.com/watch?v=VflYjdJ832k | fabric -csp summarize

I tried with various other patterns, with the same random effectiveness. Sometimes only the first and last sentences are in French, more like a comment. Some other times, nothing is in French.

Should I create another pattern to translate the text first and keep using -c afterwards?

**Comment by Robnex** [comment]
I also want to translate some transcripts to german and its also pretty random

**Comment by christrille** [comment]
When downloading videos transcriptions, I recommend ask the Youtube to give you the correct language using the "--lang" parameter:
> yt --transcript --comments --lang fr "https://www.youtube.com/watch?v=eG7yiX7vW7E"

There are several function to check which languages are available.

Advantages: 
- Youtube should have good translation.
- You skip one (heavy) translation operation.

**Comment by ByTao123** [comment]
To translate language, I create a custom pattern instead of extract_wisdom
![Snipaste_2024-06-14_15-02-38](https://github.com/danielmiessler/fabric/assets/79635137/f1c1e631-c3d9-47fa-a333-d9fcd8e397fb)

**Comment by cblte** [comment]
> To translate language, I create a custom pattern instead of extract_wisdom ![Snipaste_2024-06-14_15-02-38](https://private-user-images.githubusercontent.com/79635137/339669994-f1c1e631-c3d9-47fa-a333-d9fcd8e397fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjQzMjAsIm5iZiI6MTcyMTcyNDAyMCwicGF0aCI6Ii83OTYzNTEzNy8zMzk2Njk5OTQtZjFjMWU2MzEtYzNkOS00N2ZhLWEzMzMtZDlmY2Q4ZTM5N2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYzRmZmM5YTljN2MwZjhjZWRjYTQyNTE5NDBiMGQ2ZGU4ZWQyNWZiODZmYjJlOGUzOWI4OGM1YzA1NTc1N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AO24B5W9DshCAPu0HK7y80IqJWL9jpOdVdOXQJ6w5nQ)

Good Day, could you post a link to a paste of your pattern. I would be interested in it. Thanks
