### ISSUE TITLE
After install unter wsl, fabric was not found.

### ISSUE THREAD

**Issue by TomWest61** [danielmiessler/fabric#498]
### What is your question?

My installation:
conda create -n fabric python=3.10
conda activate fabric
git clone https://github.com/danielmiessler/fabric.git
cd fabric
sudo apt install pipx
pipx install .
fabric --setup

fabric not  found.
Any ideas to fix that?
I run ollama serve with llama3.

**Comment by stephanelanger** [comment]
Hi. It would seem like you're missing a "source ~/.bashrc" right between your "pipx install ." and "fabric --setup". Would that help ?

**Comment by TomWest61** [comment]
After "source ~/.bashrc" right between  "pipx install ." and "fabric --setup". im back from "fabric "to "base" in conda. 
"Fabric not found."
