### ISSUE TITLE
[Question]: API key setup unclear

### ISSUE THREAD

**Issue by ehbstudentadam** [danielmiessler/fabric#499]
### What is your question?

After reading the documentation, I am still not clear what API KEY exactly is meant with 'Google API key'.
Google has 464 API keys to use from, could someone provide me with more detail to which on to use?

<img width="622" alt="image" src="https://github.com/danielmiessler/fabric/assets/92335422/a5da35ea-ae08-4ff8-a877-2d348b56c595">
<img width="781" alt="image" src="https://github.com/danielmiessler/fabric/assets/92335422/0aeec558-376e-4dc6-a17a-25e7feffa528">

**Comment by geleeroyale** [comment]
Came here to look for the same answer - I think its for `Gemini`

<img width="848" alt="image" src="https://github.com/danielmiessler/fabric/assets/317685/7e99f6bf-e89a-4a2b-9a1c-ba6a12a40095">

**Comment by salmansarwar5102** [comment]
Thank you for this. I was about to lose my **** looking for this

**Comment by EvocativeOlash** [comment]
> Came here to look for the same answer - I think its for `Gemini`
> 
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/317685/335850223-7e99f6bf-e89a-4a2b-9a1c-ba6a12a40095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjE1MDcsIm5iZiI6MTcxNzg2MTIwNywicGF0aCI6Ii8zMTc2ODUvMzM1ODUwMjIzLTdlOTlmNmJmLWU4OWEtNGEyYi05YTFjLWJhNmExMmE0MDA5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNTQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDM2MGI0OGQxOTA1YjIxMDk5YmM0OWFiNDIzYTU3MGRiNmU1MTZmNDkxYTUxMjBlYjQwNGI1OGFkZDk5YTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cR02Prt0hjgdnoHVbN8-AHw7IPZLaSpcactgsExtD64">

This?
![gemini search 2024-06-08 08 58 02](https://github.com/danielmiessler/fabric/assets/38131177/b6b127a2-891b-42c5-aab9-3ab0bff4f223)

**Comment by InvdrSim** [comment]
Same here, I've obtained a Google API key with the Gemini API enabled. I've entered the key using `fabric --setup`. Using `fabric --listmodels` shows no google models.
Can someone clear this up?

**Comment by rivehafintosh** [comment]
> Thank you for this. I was about to lose my **** looking for this

That makes two of us. Sadly, I think even network chucks video just glossed right past it too. IIRC, I went back to the video to check and he just skipped right past it... unless I missed in somehow.
