### ISSUE TITLE
[Question]:  why isnt it running the pattern?

### ISSUE THREAD

**Issue by A1codesause** [danielmiessler/fabric#514]
### What is your question?

using ollama 3 for the llm not sure why it isn't working here is a list of what i put in the terminal its wsl 
popcorn@cornpop:~$ ls
fabric  snap
popcorn@cornpop:~$ cd fabric
popcorn@cornpop:~/fabric$ yt --transcript https://youtu.be/UbDyjIIGaxQ?si=CfVse42523e48mvt | fabric -sp extract_wisdom
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
You're talking about Fabric, an AI-powered tool that helps you process and analyze text content by filtering out what's important and summarizing it for you. You're sharing your experience using Fabric to take notes on a piece of content, and how it can be used to augment human capabilities rather than replacing them.

You mention the concept of slow notes, where you manually take notes on a piece of content, and how Fabric can help with that process by providing recommendations and summarizing the content. You also talk about using AI tools like Whisper.ai for transcription and piping the output into Fabric.

You share your personal experience using Fabric to record conversations and transcribe them with Whisper.ai, and then using GC Analyzer to extract relevant information from those conversations. You show how this can be used to create a second brain or note-taking system that helps you remember important information.

You also mention your project Network Check Academy, where you're creating courses to help people become awesome in various areas. You encourage viewers to join the community and check out the link below for more information.

Finally, you show how to use Fabric to save notes directly into Obsidian, a note-taking app that uses markdown files. You explain how to set up the environment file to specify the path to the Obsidian directory, and then use the Save command to create a new note in Obsidian.

Overall, your video is about exploring the possibilities of AI-powered tools like Fabric and how they can be used to augment human capabilities and improve our lives.popcorn@cornpop:~/fabric$ yt --transcript https://youtu.be/UbDyjIIGaxQ?si=CfVse42523e48mvt | fabric yt --transcript https://youtu.be/UbDyjIIGaxQ?si=CfVse42523e48mvt | fabric -sp extract_wisdomm
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
pattern not found
popcorn@cornpop:~/fabric$ yt --transcript https://youtu.be/UbDyjIIGaxQ?si=CfVse42523e48mvt | fabric -sp write_essay
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/home/popcorn/.local/pipx/venvs/fabric/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
It seems like you're sharing your thoughts on using AI tools to enhance human capabilities, particularly in writing and note-taking. You mentioned a project called "Fabric" that helps you create patterns and extract relevant information from your notes and conversations.

You also discussed how you use AI-powered transcription services like Whisper AI to transcribe conversations and then pipe the output into Fabric. This allows you to analyze and reflect on your thoughts, feelings, and experiences in a more structured way.

Additionally, you showed how you can save notes from Fabric directly into Obsidian, a note-taking app that uses Markdown files. You emphasized the importance of removing friction and making it easy to access and review your notes and reflections.

Overall, it seems like you're excited about the potential for AI tools to help humans flourish and improve themselves, while also acknowledging the need for responsible use and consideration of the role of AI in our lives.popcorn@cornpop:~/fabric$

**Comment by michaellerickson** [comment]
run this to install ffmpeg
```
sudo apt install ffmpeg
```
update again for good measure
```
sudo apt update
```

**Comment by michaellerickson** [comment]
run this to install ffmpeg
```
sudo apt install ffmpeg
```
update again for good measure
```
sudo apt update
```

- [x] #514

**Comment by A1codesause** [comment]
> run this to install ffmpeg
> 
> ```
> sudo apt install ffmpeg
> ```
> 
> update again for good measure
> 
> ```
> sudo apt update
> ```
> 
> * [x]  [[Question]:  why isnt it running the pattern? #514](https://github.com/danielmiessler/fabric/issues/514)

didnt work

popcorn@cornpop:~/fabric$  yt --transcript https://youtu.be/UbDyjIIGaxQ?si=CfVse42523e48mvt | fabric -sp extract_wisdom
It seems that this is a transcript of a video or presentation by a creator, discussing their thoughts on artificial intelligence (AI) and its potential applications in daily life.

The speaker mentions Fabric, an AI tool they are working on, which aims to assist humans in processing information and taking notes. They share several examples of how they use Fabric, including filtering out irrelevant content, summarizing long texts, and creating patterns for learning and self-improvement.

The discussion also touches on the potential benefits of using AI tools like Fabric, such as freeing up mental energy for more complex tasks, allowing humans to focus on higher-level thinking, and enabling greater efficiency in daily life. The speaker also mentions their own personal experience with recording conversations and transcribing them using Whisper AI, which they then pipe into Fabric.

Additionally, the transcript highlights the integration of Fabric with other tools like Obsidian, a note-taking app that uses markdown files to store text-based documents. The speaker shows how to save notes from Fabric directly to Obsidian, making it easier to organize and reference information.

Overall, the conversation emphasizes the potential for AI-powered tools like Fabric to augment human capabilities, increase efficiency, and improve learning outcomes, while also encouraging thoughtful consideration of their use in daily life.popcorn@cornpop:~/fabric$

**Comment by csmboles** [comment]
I had the same issue, but once I ran this it fixed itself...(I am using Homebrew on a Mac if that helps)

brew install ffmpeg

It took a minute to finish and it looks like it downloaded a ton, but it finally resolved my issue!
