### ISSUE TITLE
[Bug]:  yt namespace collision with yewtube

### ISSUE THREAD

**Issue by kiil** [danielmiessler/fabric#533]
### What happened?

The `yt` util in fabric collides with the very popular TUI for youtube which also uses `yt` to start:

[mps-youtube/yewtube: A Terminal based YouTube player and downloader.](https://github.com/mps-youtube/yewtube)

### Version check

- [X] Yes I was.

**Comment by petterreinholdtsen** [comment]
In Debian, it also collide with the `python3-yt` package (https://yt-project.org/), which provide `/usr/bin/yt`, blocking easy packaging for Debian.
