### ISSUE TITLE
[Bug]: yt only works with youtu.be/xyz, not youtube.com/watch?v=xyz.

### ISSUE THREAD

**Issue by zoneandonly** [danielmiessler/fabric#538]
### What happened?

This works: https://youtu.be/lEXd6TXPw7E
This doesn't: https://www.youtube.com/watch?v=lEXd6TXPw7E
Tried escaping, no joy. 

### Version check

- [X] Yes I was.

### Relevant log output

```shell
zsh: no matches found: https://www.youtube.com/watch?v=lEXd6TXPw7E
```

**Comment by TheBrinkOfTomorrow** [comment]
It's a zsh issue.    It trips over the ? character.  You need to add single or double quotes around the URL, or just escape the ? with a \
e.g.
 https://www.youtube.com/watch\?v=lEXd6TXPw7E
or
'https://www.youtube.com/watch?v=lEXd6TXPw7E'

**Comment by zoneandonly** [comment]
Thanks for your response. I tried single and double quotes to no avail. Docs show the use of URL with ? but without quotes. If memory serves, it used to work without quotes.
