### ISSUE TITLE
[Bug]: list patterns it not listing all patterns from the patterns folder

### ISSUE THREAD

**Issue by teapczynski** [danielmiessler/fabric#542]
### What happened?

I just updated fabric with git pull and when running fabric --list it is not listing all the patterns. 
~/fabric/patterns $ ll -1 | wc -l
112

~/fabric/patterns $ fabric --list | wc -l
109

### Version check

- [X] Yes I was.

**Comment by CyRamos** [comment]
Hey, my issue seems related as well - 
I just create personal `*/patterns/{my_pattern_folder}/system.md`. 
when I check it with  `ls fabric/patterns | grep {my_pattern_folder} ` it does found it
However whenever I use `fabric -l | grep {my_pattern_folder}` it doesn't find it.

**Comment by blakesims** [comment]
> Hey, my issue seems related as well - I just create personal `*/patterns/{my_pattern_folder}/system.md`. when I check it with `ls fabric/patterns | grep {my_pattern_folder} ` it does found it However whenever I use `fabric -l | grep {my_pattern_folder}` it doesn't find it.

Hi, you have to copy your pattern into the config, not the project directory. The patterns are fetched from `~/.config/fabric/patterns`

**Comment by CyRamos** [comment]
> > Hey, my issue seems related as well - I just create personal `*/patterns/{my_pattern_folder}/system.md`. when I check it with `ls fabric/patterns | grep {my_pattern_folder} ` it does found it However whenever I use `fabric -l | grep {my_pattern_folder}` it doesn't find it.
> 
> Hi, you have to copy your pattern into the config, not the project directory. The patterns are fetched from `~/.config/fabric/patterns`

Hey 
Thank you @blakesims 
I did it as well (probably edited my last comment after you answered, but it doesn't work either)

![image](https://github.com/danielmiessler/fabric/assets/40651473/1fb27f90-80b2-41d8-ac40-84d632adbe7a)

**Comment by WielandF** [comment]
Alternativly you can put the patterns in the project folder and run `fabric --setup` which should get them intp the `~/.config/fabric/patterns` and make them useable.
