### ISSUE TITLE
[Question]: --remoteOllamaServer Is it a URL or an IP?

### ISSUE THREAD

**Issue by chka** [danielmiessler/fabric#550]
### What is your question?

The --help says:

```
--remoteOllamaServer REMOTEOLLAMASERVER
                        The URL of the remote ollamaserver to use. ONLY USE
                        THIS if you are using a local ollama server in an non-
                        default location or port
```

My Ollama server is under a long security string like this:

https:// ${host} / ${big long string} /ollama/api/generate

What should I use as remoteOllamaServer because I tried almost every combination and it doesn't show the ollama models with --listmodels.

Thank you

**Comment by cdeschenes** [comment]
Try to just specify the host and port for the Ollama API. This is what works for me
`--remoteOllamaServer http://10.20.30.200:11434`

**Comment by chka** [comment]
> Try to just specify the host and port for the Ollama API. This is what works for me `--remoteOllamaServer http://10.20.30.200:11434`
> 
> 11434 is the default port by Ollama

yes but that assumes your Ollama server's API is under http://10.20.30.200:11434/api/generate and not under vhost path: http://10.20.30.200:11434/abcd1234abcd1234abcd1234/ollama/api/generate

**Comment by marcellodesales** [comment]
@chka Should Fabric support the API path param as well? I'm on the same boat in regards to the API servers have generated paths... For instance, deploying multiple GenAI API Servers similar to Ollama and maintaining the server static, but at a different path...
