### ISSUE TITLE
Option to use other LLM Models

### ISSUE THREAD

**Issue by netsi1964** [danielmiessler/fabric#56]
Love your project! 👏

I would be great if fabric could use local LLMs like Lama from Meta!
I do not know how to do it though...

**Comment by Andortk** [comment]
Same feeling! Love the project too. Would love to see it support openrouter AI API or TogetherAI. Could all be done by passing it through LiteLLM. LiteLLM has connections to all (or most) of the LLM providers via API.

**Comment by danielmiessler** [comment]
Great idea, thank you!

**Comment by Gerkinfeltser** [comment]
Hi, just curious how this is implemented. I'd like to make use of openrouter if possible. 😄
