### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by jnuts74** [danielmiessler/fabric#562]
### What is your question?

Apologies if I missed this in the documentation

Instead of copy and paste data or cat data file piped to pattern, does this have the ability to obtain data via web search or from a specific website (scraped) then be piped to a pattern for analytics.

Example:

Id like it to leverage various specific websites to pull weather related scientific data, metrics and attributes to find commonality and patterns in historical weather data and then pipe that to a custom pattern that contrasts those historical conditions against todays conditions to identify and gauge severe storm predictability. 

Thanks again and sorry for the long question. At least its pretty cool though right?

**Comment by WillJesperson** [comment]
youd have to implement some sort of program to webscrape that for you. Fabric is simply the infastructure that allows you to use consistant prompts on a given AI model. Once it is webscraped though you can pbpaste -- on mac or pipe in a file -- on linux
