### ISSUE TITLE
[Question]: broken pipe

### ISSUE THREAD

**Issue by iplayfast** [danielmiessler/fabric#567]
### What is your question?

I tried out a sample 
yt --transcript https://youtu.be/zdbVtZIn9IM | fabric -m llama3:latest  -sp extract_wisdom
which gave the error 
```bash: /home/chris/.cache/pypoetry/virtualenvs/fabric-4CEgWCkC-py3.10/bin/fabric: No such file or directory
Traceback (most recent call last):
  File "/home/chris/.local/bin/yt", line 8, in <module>
    sys.exit(main_yt())
  File "/home/chris/.local/pipx/venvs/fabric/lib/python3.10/site-packages/installer/client/cli/yt.py", line 148, in main
    main_function(args.url, args)
  File "/home/chris/.local/pipx/venvs/fabric/lib/python3.10/site-packages/installer/client/cli/yt.py", line 113, in main_function
    print(transcript_text.encode('utf-8').decode('unicode-escape'))
BrokenPipeError: [Errno 32] Broken pipe
```
Investing further I tried 
yt --transcript https://youtu.be/zdbVtZIn9IM
which seemed to work. 
I then tried
yt --transcript https://youtu.be/zdbVtZIn9IM | ollama run llama3 "extract wisdom from this"
which also worked.
so apparently I'm not using ollama right?

**Comment by iplayfast** [comment]
Found the problem. I had originally installed a few months back and the new install wasn't being seen and the old one was corrupted. cleaned everything out and started fresh now seems to be working.

**Comment by primed-lan-laucirica** [comment]
I noticed this isn't working today. Is this fixed in a dev branch?
