### ISSUE TITLE
[Question]: Other then OpenAI API(which is chargeable), how can I use other free API?

### ISSUE THREAD

**Issue by lungying857** [danielmiessler/fabric#579]
### What is your question?

It will be great if someone can tell me how to switch to other free API instead of OpenAI API. Thanks.

**Comment by WielandF** [comment]
You could use a local LLM like ollama with the llama3 model?

**Comment by lungying857** [comment]
Thank you very much for all your help. It works work now! :D

**Comment by Uddhav07** [comment]
> You can also make use of services like openrouter.ai. You just need to add `OPENAI_BASE_URL` & `OPENAI_API_KEY` entries to your `.env`.
> 
> * You generate an openrouter api key at https://openrouter.ai/keys & use it as the `OPENAI_API_KEY`.
> * The `DEFAULT_MODEL` is optional & you can get the appropriate names by browsing openrouter for the model you want and hitting the little clipboard icon beside its name when you find it (& paste it as the `DEFAULT_MODEL` or pass it to fabric via the -m arg).
> 
> ```
> DEFAULT_MODEL=meta-llama/llama-3-8b-instruct:free
> OPENAI_API_KEY=sk-or-v1-an-actual-key-generated-via-openrouter.ai/keys
> OPENAI_BASE_URL=https://openrouter.ai/api/v1
> ```
> 
> There is also a service called together.ai which I have not used myself but apparently gives you $25 of free credits for signing up.

i did this in windows it did not work gave me error 401, tries restarting powershell and resetup fabric but it just removes the base url i put in

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/3f2b069f-031b-4030-a23a-891358fd5b4d)

**Comment by woshichuanqilz** [comment]
> You can also make use of services like openrouter.ai. You just need to add `OPENAI_BASE_URL` & `OPENAI_API_KEY` entries to your `.env`.
> 
> * You generate an openrouter api key at [openrouter.ai/keys](https://openrouter.ai/keys) & use it as the `OPENAI_API_KEY`.
> * The `DEFAULT_MODEL` is optional & you can get the appropriate names by browsing openrouter for the model you want and hitting the little clipboard icon beside its name when you find it (& paste it as the `DEFAULT_MODEL` or pass it to fabric via the -m arg).
> 
> ```
> DEFAULT_MODEL=meta-llama/llama-3-8b-instruct:free
> OPENAI_API_KEY=sk-or-v1-an-actual-key-generated-via-openrouter.ai/keys
> OPENAI_BASE_URL=https://openrouter.ai/api/v1
> ```
> 
> There is also a service called together.ai which I have not used myself but apparently gives you $25 of free credits for signing up.


I use something like this but failed. 
1. I use a openai online service not directly from openai. 
2. I fill the env variable . **And the model of this api can be loaded when I setup fabric. **
```
OPENAI_API_KEY=sk-xxx
OPENAI_API_BASE_URL=https://api.bltapi.top/v1
```
3. But I get error when I run fabric command 
`cat test.md | fabric --pattern  extract_wisdom
error, status code: 401, message: Incorrect API key provided: sk-Cs9yP***************************************C222. You can find your API key at https://platform.openai.com/account/api-keys.`

how to fix it?
