### ISSUE TITLE
[Bug]: Blank in pathname for FABRIC_OUTPUT_PATH

### ISSUE THREAD

**Issue by RoeslerM** [danielmiessler/fabric#586]
### What happened?

I wanted to save Fabric output directly to my Obsidian storage.
I use iCloud as storage location, so I can use my Obsidian from multiple devices and while I am on the road.

So I used in $HOME/.config/fabric/.env
**FABRIC_OUTPUT_PATH=/Users/[MY_USER]/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Arbeit/Fabric**
and I received errormessage 

**p | fabric -sp rate_content | save first-try                                          
'/Users/[MY_USER]/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Arbeit/Fabric' does not exist. Create it and try again.**

Note that the system path "Mobile Documents" includes a blank space, which I masked.
I also validated the correct masking in the terminal, a 
cd /Users/[MY_USER]/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Arbeit/Fabric
worked as expected.
After some experiment with local paths, all ended positive, I used

FABRIC_OUTPUT_PATH="~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Arbeit/Fabric"

So I used quotation marks for the entire path, which is now a workaround for my problem.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
martinroesler@MBAM2-Roesler-84 fabric % p | fabric -sp rate_content | save erster-versuch                                          
'/Users/martinroesler/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Arbeit/Fabric' does not exist. Create it and try again.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by dennis605** [comment]
I had the same issue, but when I then put the path in single quotation mark its working perfect, like this:
`FABRIC_OUTPUT_PATH='/Documents/obsidian_vault/input_fabric'`

**Comment by anthonyabraira** [comment]
+1 Any updates on this? Experiencing the same issue.
