### ISSUE TITLE
Unable to get YouTube URLs to interact with models - API and setup all ok

### ISSUE THREAD

**Issue by fearby** [danielmiessler/fabric#587]
### Discussed in https://github.com/danielmiessler/fabric/discussions/577

<div type='discussions-op-text'>

<sup>Originally posted by **fearby** June  9, 2024</sup>
Yes a hobbyist with little experience.
Installed on MacOS ok and API keys added except for Google API
The example on the Github landing page will just give me nothing and the following error:

yt --transcript https://youtube.com/watch?v=uXs-zPc63kM | fabric --stream --pattern extract_wisdom
zsh: no matches found: https://youtube.com/watch?v=uXs-zPc63kM
I'm sorry, but it seems like there was no input provided for me to process. Could you please provide the text content you'd like me to analyze?%

What am I doing wrong?</div>

**Comment by zoneandonly** [comment]
This works: https://youtu.be/lEXd6TXPw7E
This doesn't: https://www.youtube.com/watch?v=lEXd6TXPw7E
l tried quotes around the URL, but to no avail. The "?" seems to be the issue.

**Comment by seven-of-eleven** [comment]
I had the same issue. Found the two solutions based on @zoneandonly. 
1. Quotes around the URL - worked for me
2. Escaping the "?" character with "\" (forward slash) in front of the "?" -  also worked for me. 
    - using the URL above change if from:
       https://www.youtube.com/watch?v=lEXd6TXPw7E
       to:
       https://www.youtube.com/watch\?v=lEXd6TXPw7E

I'm on macOS Sonoma using zsh shell in the terminal.

Thanks.

**Comment by eugeis** [comment]
You can use also

fabric -y "https://youtube.com/watch?v=uXs-zPc63kM" --stream --pattern extract_wisdom
