### ISSUE TITLE
Possibly exposed token

### ISSUE THREAD

**Issue by RichardoC** [danielmiessler/fabric#6]
https://github.com/danielmiessler/fabric/blob/main/infrastructure/server/fabric_api_keys.json#L3 looks like an exposed token,  you might wish to revoke it and replace this with a placeholder/leave it blank.

Sorry if this is a false alarm!

**Comment by matthewdeanmartin** [comment]
I'd recommend using the dotenv library, a .env file and .gitignore to keep the .env file out of source control.

See [python-dotenv](https://pypi.org/project/python-dotenv/)

**Comment by danielmiessler** [comment]
It's not an exposed token. It's an example for controlling client-to-server auth during one's self-setup. But good eye, I appreciate you.
