### ISSUE TITLE
[Question]: extract_wisdom pattern repetitive across IDEAS/INSIGHTS/HABITS

### ISSUE THREAD

**Issue by Alexintosh** [danielmiessler/fabric#611]
### What is your question?

I've notice multiple times that the "extract_wisdom" is mostly repeating the same things in slightly different words across IDEAS/INSIGHTS/HABITS. I'm trying to work on a pattern modification which makes sure each section only proposed unique elements.

Does anyone archived that already? If yes, could you share your modified pattern?

**Comment by vaygr** [comment]
@danielmiessler I believe this is still true as of **1.4.156**.
