### ISSUE TITLE
[Feature request]:  fabric -v prints the installed version info

### ISSUE THREAD

**Issue by greyhound3** [danielmiessler/fabric#616]
### show installed version (suggestion)
I think it would be nice to implement a "show version" if calling "fabic -v" or "fabric --version". Right now, it prints "fabric: error: unrecognized arguments: -v". If starting version numbering system from scratch, why not implement the new, right now proposed python numbering (yy.mm.version), like "24.06.01" for future comfortibility ("24.06.01" <-- more info, less info --> "1.40.0"). :rofl:

**Comment by eugeis** [comment]
Implemented in the current release.
