### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by pixman92** [danielmiessler/fabric#626]
### What is your question?

Is there a pattern for pulling out quotes from a transcript?

**Comment by KasperZutterman** [comment]
You can use something like `grep -r "quotes" --include="system.md"  ~/.config/fabric/patterns/*` to list all references to `quotes` in the available patterns.

Extract:
```
~/.config/fabric/patterns/extract_extraordinary_claims/system.md:- Output a full list of the claims that were made, using actual quotes. List them in a bulleted list.
~/.config/fabric/patterns/extract_extraordinary_claims/system.md:- Output at least 50 of these quotes, but no more than 100.
~/.config/fabric/patterns/extract_business_ideas/system.md:4. Do not repeat ideas, quotes, facts, or resources.
~/.config/fabric/patterns/extract_extraordinary_claims/system.md:- Ensure you extract ALL such quotes.
~/.config/fabric/patterns/extract_ideas/system.md:- Do not repeat ideas, quotes, facts, or resources.
~/.config/fabric/patterns/extract_main_idea/system.md:- Do not repeat ideas, quotes, facts, or resources.
~/.config/fabric/patterns/extract_patterns/system.md:- Do not repeat ideas, quotes, facts, or resources.
~/.config/fabric/patterns/extract_wisdom/dmiessler/extract_wisdom-1.0.0/system.md:3. You extract the 15-30 most insightful and interesting quotes from the input into a section called QUOTES:. Use the exact quote text from the input.
~/.config/fabric/patterns/extract_wisdom/dmiessler/extract_wisdom-1.0.0/system.md:4. Do not repeat ideas, quotes, facts, or resources.
~/.config/fabric/patterns/extract_wisdom/system.md:- Extract 15 to 30 of the most surprising, insightful, and/or interesting quotes from the input into a section called QUOTES:. Use the exact quote text from the input.
~/.config/fabric/patterns/extract_wisdom/system.md:- Do not repeat ideas, quotes, facts, or resources.
```

From that point, you can see if any of the patterns prompt to extract quotes from the input.

In this case the `extract_wisdom` pattern could be a great starting point, as it includes the following step: `Extract 15 to 30 of the most surprising, insightful, and/or interesting quotes from the input into a section called QUOTES:. Use the exact quote text from the input.` ([extract_wisdom pattern definition](https://github.com/danielmiessler/fabric/blob/main/patterns/extract_wisdom/system.md)).

If that doesn't suffice for your purpose, you can add your own pattern for specifically extracting quotes ([documentation](https://github.com/danielmiessler/fabric?tab=readme-ov-file#custom-patterns)).
