### ISSUE TITLE
[Question]: When installing with pipx is very slow, it pauses at "installing fabric from spec"

### ISSUE THREAD

**Issue by Kiasma1** [danielmiessler/fabric#628]
### What is your question?

Operating Environment: Windows10 WSL Ubuntu22.04
Command: pipx install .
![image](https://github.com/danielmiessler/fabric/assets/32356017/41e19a61-1675-435e-8b05-18557cdc2451)
It has been stopped for an hour

**Comment by danindiana** [comment]
@Kiasma1 I'm having the same issues, not installing via ubuntu cli.

**Comment by danindiana** [comment]
OK. So watching network chuck video his install is pretty fast but letting it wait for a while it does appear to install on my system. 

OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 6.5.0-41-generic
 Uptime: 49m
 Packages: 3753
 Shell: bash 5.1.16
 Resolution: 2560x1080
 DE: Xfce
 WM: Xfwm4
 WM Theme: Default
 GTK Theme: Greybird [GTK2]
 Icon Theme: elementary-xfce-darker
 Font: Noto Sans 9
 Disk: 664G / 938G (75%)
 CPU: AMD Ryzen 9 5950X 16-Core @ 32x 4.1GHz
 GPU: NVIDIA GeForce RTX 3060, NVIDIA GeForce GTX 1060 6GB
 RAM: 10491MiB / 128723MiB

**Comment by Logosuniversal** [comment]
How Did you fix this ?

**Comment by Kiasma1** [comment]
> OK. So watching network chuck video his install is pretty fast but letting it wait for a while it does appear to install on my system.
> 
> OS: Ubuntu 22.04 jammy Kernel: x86_64 Linux 6.5.0-41-generic Uptime: 49m Packages: 3753 Shell: bash 5.1.16 Resolution: 2560x1080 DE: Xfce WM: Xfwm4 WM Theme: Default GTK Theme: Greybird [GTK2] Icon Theme: elementary-xfce-darker Font: Noto Sans 9 Disk: 664G / 938G (75%) CPU: AMD Ryzen 9 5950X 16-Core @ 32x 4.1GHz GPU: NVIDIA GeForce RTX 3060, NVIDIA GeForce GTX 1060 6GB RAM: 10491MiB / 128723MiB

no

**Comment by Kiasma1** [comment]
> How Did you fix this ?

no
