### ISSUE TITLE
[Bug]: Local models not appearing

### ISSUE THREAD

**Issue by mardlive** [danielmiessler/fabric#636]
### What happened?

When I run `fabric --listmodels`, no local model appears, even though I have my ollama server running, and with 2 models downloaded, I went through many other similar issues reported in this repository and none of them resolved it. Then I decided to reinstall both ollama and fabric, but the error persists. 

### Version check

- [X] Yes I was.

**Comment by ToeiRei** [comment]
this also affects setting the default model.

**Comment by mardlive** [comment]
In the meantime, I tried re-installing WSL, and fabric and Ollama to no avail, until I tried to install Ollama inside WSL.
And it is now working!!!
Still I thought it should work with the Ollama installed on windows, as all the videos I saw did.
