### ISSUE TITLE
More detail about dynamic path-pattern mapping

### ISSUE THREAD

**Issue by dheerapat** [danielmiessler/fabric#64]
> This has conflicts, unfortunately, and I'm not sure I'm fully grasping the idea. Can you restate?

example: currently when I go to `localhost:5000/extwis` I can send a post request to tell the server to mill my input with your pattern and then send to OpanAI to get the answer

I proposed that instead you building `@app.route("/extwis", methods=["POST"])` for every pattern, we can just make path `/<pattern>` dynamic by adding a mapping dictionary to map path with the pattern user want to use. [more info on this](https://flask.palletsprojects.com/en/3.0.x/quickstart/#variable-rules)

_Originally posted by @dheerapat in https://github.com/danielmiessler/fabric/issues/52#issuecomment-1935518092_

**Comment by danielmiessler** [comment]
Can you give me a full before and after example? I'm having a brain fart on this.

**Comment by danielmiessler** [comment]
Also can you submit as a PR?
