### ISSUE TITLE
[Question]: How do I update to the latest version?

### ISSUE THREAD

**Issue by meetbryce** [danielmiessler/fabric#645]
### What is your question?

I couldn't find anything in the README and i tried both `pipx upgrade fabric` and `pipx upgrade .` after pulling the latest code.

Do i need to uninstall and reinstall?

Sorry for the naive question.

**Comment by jmmarkiewicz** [comment]
running the risk of exposing my ignorance - this is what I did and it worked for me (on Mac OS)
1. deleted the fabric folder
2. cloned the GIT repo
3. run the  ```pipx install .``` in the fabric folder
4. re-run the ```fabric --setup```  and fed it Claude API - all works fine I can access Sonnet 3.5 now

**Comment by RoeslerM** [comment]
There is currently a bug in the configuration.
I faced the fame problem, even I am using PIP and not PIX

I assume that this depends on the version in **pyproject.toml**, which still points to version 1.2. PIP is comparing the new revision number with the internal (already installed) number and as they are equal no new fabric is installed.

To fix this, the fabric/pyproject.toml need to be corrected in line 3

For a workaround, uninstalling and then reinstalling fabric works (but backup your .env and your context.md - both in $HOME/.config/fabric)

**Comment by meetbryce** [comment]
@danielmiessler has since added instructions to the README.
