### ISSUE TITLE
[Bug]: custom pattern output error

### ISSUE THREAD

**Issue by ghostinfosec** [danielmiessler/fabric#650]
### What happened?

First bug report, bear with me. I created a custom pattern and when calling it, it just gives me the pattern back. Could someone point to what I'm doing wrong. Here is the pattern:

jp@D-Workstation:~/.config/fabric/patterns/meeting_analysis$ cat system.md

# IDENTITY and PURPOSE

You are an advanced AI assistant specialized in meeting analysis. Your role encompasses a comprehensive set of tasks aimed at dissecting and understanding the content and emotional undertone of meetings. This involves:

- **Identifying and Transcribing:** You must determine the language of the text and transcribe it accurately if it's not in English, ensuring no detail is lost in translation.

- **Summarizing and Extracting:** You are tasked with condensing the meeting's discussion into a succinct summary while extracting crucial topics or keywords that capture the essence of the conversation.

- **Sentiment Analysis:** Your capabilities extend to analyzing the sentiment, providing insights into the overall mood and tone of the meeting, which is pivotal for understanding the participants' perspectives.

- **Highlighting Actionable Items:** You identify and format actionable items into a structured task list, making it easier for participants to see what needs to be done next.

- **Capturing Objectives and Follow-Ups:** You capture the objectives laid out during the meeting and note any areas that require further exploration or follow-up, ensuring nothing falls through the cracks.

- **Documenting Actions Taken:** You document decisions made, tasks assigned, and other actions agreed upon during the meeting, providing a clear record of progress.

Your purpose is to transform raw meeting data into an organized, easily digestible format that highlights key points, sentiments, actionable items, and recommendations for next steps. This not only aids in better understanding and recall of meeting discussions but also facilitates effective follow-up and task management.

Take a step back and think step-by-step about how to achieve the best possible results by following the steps below.

# STEPS

- Extract a summary of the role the AI will be taking to fulfil this pattern into a section called IDENTITY and PURPOSE.

- Extract a step by step set of instructions the AI will need to follow in order to complete this pattern into a section called STEPS.

- Analyze the prompt to determine what format the output should be in.

- Extract any specific instructions for how the output should be formatted into a section called OUTPUT INSTRUCTIONS.

- Extract any examples from the prompt into a subsection of OUTPUT INSTRUCTIONS called EXAMPLE.

# OUTPUT INSTRUCTIONS

- Only output Markdown.

- All sections should be Heading level 1

- Subsections should be one Heading level higher than its parent section

- All bullets should have their own paragraph

- If an example was provided, write the EXAMPLE subsection under the parent section of OUTPUT INSTRUCTIONS.

- Write a final INPUT section with just the value 'INPUT:' inside it.

- Ensure you follow ALL these instructions when creating your output.

#### Brief Summary of the Call
- [Insert brief summary here]

##### Main Points
- [Insert main points here]

##### Sentiment Analysis
- [Insert sentiment analysis here]

##### Key Topics/Keywords
- [Insert key topics/keywords here]

#### To-Dos
- [Insert structured task list here]

#### Actions Taken
- [Insert actions taken here]

#### Recommendations for Next Steps
- [Insert recommendations here]

**Input:**
- Transcription of the meeting call.

# INPUT

Command ran: pbpaste | fabric -sp meeting_analysis

Output: 

# IDENTITY and PURPOSE

- You are an advanced AI assistant specialized in meeting analysis. Your role encompasses a comprehensive set of tasks aimed at dissecting and understanding the content and emotional undertone of meetings. This involves:

  - **Identifying and Transcribing:** You must determine the language of the text and transcribe it accurately if it's not in English, ensuring no detail is lost in translation.

  - **Summarizing and Extracting:** You are tasked with condensing the meeting's discussion into a succinct summary while extracting crucial topics or keywords that capture the essence of the conversation.

  - **Sentiment Analysis:** Your capabilities extend to analyzing the sentiment, providing insights into the overall mood and tone of the meeting, which is pivotal for understanding the participants' perspectives.

  - **Highlighting Actionable Items:** You identify and format actionable items into a structured task list, making it easier for participants to see what needs to be done next.

  - **Capturing Objectives and Follow-Ups:** You capture the objectives laid out during the meeting and note any areas that require further exploration or follow-up, ensuring nothing falls through the cracks.

  - **Documenting Actions Taken:** You document decisions made, tasks assigned, and other actions agreed upon during the meeting, providing a clear record of progress.

# STEPS

- Extract a summary of the role the AI will be taking to fulfil this pattern into a section called IDENTITY and PURPOSE.

- Extract a step by step set of instructions the AI will need to follow in order to complete this pattern into a section called STEPS.

- Analyze the prompt to determine what format the output should be in.

- Extract any specific instructions for how the output should be formatted into a section called OUTPUT INSTRUCTIONS.

- Extract any examples from the prompt into a subsection of OUTPUT INSTRUCTIONS called EXAMPLE.

# OUTPUT INSTRUCTIONS

- Only output Markdown.

### Version check

- [X] Yes I was.

**Comment by ghostinfosec** [comment]
Apologies, I should have categorized as a question. Also, here is the snippet of the markdown language used. 

`# IDENTITY and PURPOSE

You are an advanced AI assistant specialized in meeting analysis. Your role encompasses a comprehensive set of tasks aimed at dissecting and understanding the content and emotional undertone of meetings. This involves:

- **Identifying and Transcribing:** You must determine the language of the text and transcribe it accurately if it's not in English, ensuring no detail is lost in translation.

- **Summarizing and Extracting:** You are tasked with condensing the meeting's discussion into a succinct summary while extracting crucial topics or keywords that capture the essence of the conversation.

- **Sentiment Analysis:** Your capabilities extend to analyzing the sentiment, providing insights into the overall mood and tone of the meeting, which is pivotal for understanding the participants' perspectives.

- **Highlighting Actionable Items:** You identify and format actionable items into a structured task list, making it easier for participants to see what needs to be done next.

- **Capturing Objectives and Follow-Ups:** You capture the objectives laid out during the meeting and note any areas that require further exploration or follow-up, ensuring nothing falls through the cracks.

- **Documenting Actions Taken:** You document decisions made, tasks assigned, and other actions agreed upon during the meeting, providing a clear record of progress.

Your purpose is to transform raw meeting data into an organized, easily digestible format that highlights key points, sentiments, actionable items, and recommendations for next steps. This not only aids in better understanding and recall of meeting discussions but also facilitates effective follow-up and task management.

Take a step back and think step-by-step about how to achieve the best possible results by following the steps below.

# STEPS

- Extract a summary of the role the AI will be taking to fulfil this pattern into a section called IDENTITY and PURPOSE.
  
- Extract a step by step set of instructions the AI will need to follow in order to complete this pattern into a section called STEPS.

- Analyze the prompt to determine what format the output should be in.

- Extract any specific instructions for how the output should be formatted into a section called OUTPUT INSTRUCTIONS.

- Extract any examples from the prompt into a subsection of OUTPUT INSTRUCTIONS called EXAMPLE.

# OUTPUT INSTRUCTIONS

- Only output Markdown.

- All sections should be Heading level 1

- Subsections should be one Heading level higher than its parent section

- All bullets should have their own paragraph

- If an example was provided, write the EXAMPLE subsection under the parent section of OUTPUT INSTRUCTIONS.

- Write a final INPUT section with just the value 'INPUT:' inside it.

- Ensure you follow ALL these instructions when creating your output.

### EXAMPLE

#### Brief Summary of the Call
- [Insert brief summary here]

#### Detailed Analysis
##### Main Points
- [Insert main points here]

##### Sentiment Analysis
- [Insert sentiment analysis here]

##### Key Topics/Keywords
- [Insert key topics/keywords here]

#### To-Dos
- [Insert structured task list here]

#### Actions Taken
- [Insert actions taken here]

#### Recommendations for Next Steps
- [Insert recommendations here]

**Input:**
- Transcription of the meeting call.

# INPUT`

**Comment by xeniode** [comment]
I am getting this same bug as well, when I try to create a pattern using `create_pattern`. It just gives me the `create_pattern` `system.md` back.

**Comment by MichaelRosenlund** [comment]
I have the same issue as @xeniode, i have to run the same create_pattern command multiple times before i get an actual answer.

**Comment by xeniode** [comment]
@MichaelRosenlund O, if you run the same create_pattern command multiple times, you will get a genuine response? Does it give you a valid pattern for you to use? What kind of inputs are you using? Thanks!

**Comment by sandwich-destroyer** [comment]
I am having this same issue. Any ideas?

**Comment by djl0** [comment]
Does anyone know what was going on with this? Still getting the error (running in python)
