### ISSUE TITLE
Missing requirements.txt file for client install

### ISSUE THREAD

**Issue by natv** [danielmiessler/fabric#67]
In the README quickstart for the client install, it instructs to

# Enter the project and its /client folder
cd fabric/client

# Install the pre-requisites
pip3 install -r requirements.txt

However, there is no requirements.txt in the fabric/client folder. I did find one in the 'server' folder and installed those requirements, but perhaps something is still missing because after adding the alias (or even trying manually), it's not running, it complains that I'm referencing a folder when I do 'fabric -h'

$ fabric -h
-bash: /home/user/ai/fabric/client/fabric: Is a directory

Thanks

**Comment by autumn-traveller** [comment]
Same issue here. Opened a PR to try to fix. https://github.com/danielmiessler/fabric/pull/69

**Comment by agu3rra** [comment]
Hello folks!
The client now uses python poetry to manage dependencies instead of regular `requirements.txt`. Install instructions are on the client readme file [here](https://github.com/danielmiessler/fabric/blob/main/client/README.md).

I think this is just a matter of updating the main README file's instructions for the client.

**Comment by danielmiessler** [comment]
#Can you submit a PR to update that readme?

**Comment by agu3rra** [comment]
> #Can you submit a PR to update that readme?

@danielmiessler It's PR #72.

**Comment by BryanKerrEdTech** [comment]
Does the new install instructions mean we no longer need to do the current Readme's Steps 5 and 6? Seems like the poetry shell makes those steps unnecessary, correct?

**Comment by agu3rra** [comment]
@BryanKerrEdTech
Steps 5 and 6 seem to point to how to add the CLI to your PATH. If you're running the cli after running `poetry shell`, the virtualenv it creates will already know `fabric` and you're correct (no further action required).

However...
If you wish that `fabric` is a known cli command after you reboot your computer and you don't wish to activate the virtualenv every time, I suggest you add it to your path by running:
```bash
# Determine the path of your fabric CLI for the next step
# It should be something like /home/thanos/.cache/pypoetry/virtualenvs/fabric--_h0wFFW-py3.10/bin/fabric
which fabric
```

Then use the detected path to run steps 5 and 6.

**Comment by BryanKerrEdTech** [comment]
Thanks so much for clearing that up for me Andre!
