### ISSUE TITLE
[Question]: I've created an agent that uses fabric with LangChain and Ollama.  Is that okay?

### ISSUE THREAD

**Issue by MikeyBeez** [danielmiessler/fabric#677]
### What is your question?

This is not a real question, because I read the license.  I just wanted to make you aware of my project.  https://github.com/MikeyBeez/RAGAgent/tree/fabric. I hope you like it.  It's for MacOS.  I don't know if Mac is your main system.  I guess I thought you'd like to know that people find your work extremely helpful and beneficial.  Thank you for all your hard work.  BTW, my software is also free and open source.  I hope to help keep AI development moving at top speed.  :)

**Comment by leobenkel** [comment]
where did you find the license ?

**Comment by LaBalaDeOro** [comment]
@leobenkel, the presumed license for `main` is in the `agents` branch https://github.com/danielmiessler/fabric/blob/agents/LICENSE.txt
I created a discussion to clarify that the license for `main` is the same. Pretty sure it is, but wanted to make sure.
