### ISSUE TITLE
[Bug]: Local models not showing up

### ISSUE THREAD

**Issue by Samitch1** [danielmiessler/fabric#713]
### What happened?

I was trying to get Ollama's local models to work with Fabric, but I couldn't see any local models when I listed the models. 
I have 5 models installed, but only the OpenAI and Claude models are listed. 

### Version check

- [X] Yes I was.

**Comment by michaellerickson** [comment]
are these local models available public repos?

what commands did you use to install each one?

what are their names?

**Comment by Muhammad9922** [comment]
I have the same issue, I want to use the local ollama model but it isn't showing any local models. I have configured fabric as in the quickstart guide.

**Comment by HydraBucket** [comment]
I am also recieving this error. Has anyone has any luck amending it? I want to be able to access my models from Ollama.
