### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'chat' error when running fabric in WSL

### ISSUE THREAD

**Issue by katana-hydra** [danielmiessler/fabric#726]
### What happened?

I was trying to run a command using `yt` and `fabric` in WSL with the following command:
yt --transcript 'https://www.youtube.com/watch?v=3cmjFYyTIrk' | fabric -sp extract_wisdom

I expected the command to process the YouTube transcript and extract wisdom using `fabric`. However, I encountered an error: `'NoneType' object has no attribute 'chat'`.

Additionally, I noticed the following warnings and messages in the log output:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1720765001.305330 11563 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
I0000 00:00:1720765001.306492 11563 ev_epoll1_linux.cc:125] grpc epoll fd: 3
I0000 00:00:1720765001.315252 11563 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'

### Version check

- [X] Yes I was.

### Relevant log output

```shell
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1720765001.305330 11563 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
I0000 00:00:1720765001.306492 11563 ev_epoll1_linux.cc:125] grpc epoll fd: 3
I0000 00:00:1720765001.315252 11563 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
Error: 'NoneType' object has no attribute 'chat'
'NoneType' object has no attribute 'chat'
```

**Comment by patonw** [comment]
Probably related to https://github.com/danielmiessler/fabric/issues/684, https://github.com/danielmiessler/fabric/issues/373, etc.

Things to try:
- Configure an OpenAI API key (doesn't need to have credits as long as it's a valid token)
- Set a default model that isn't OpenAI
- Pass a model manually with `-m <modelname>`

**Comment by equinoxel** [comment]
I had the same issue and to me it looks it's a model name problem. I used to run:

```sh
fabric --remoteOllamaServer http://10.0.0.10:11434 -m llama3 -sp extract_wisdom
```

I did a `fabric --listmodels` and got `llama3:latest` as a model available in ollama, so I put the name in verbatim:

```sh
fabric --remoteOllamaServer http://10.0.0.10:11434 -m llama3:latest -sp extract_wisdom
```

Note that if you specify the URL of the `remoteOllamaServer`, you need to define `OLLAMA_HOST=http://10.0.0.10:11434` (same IP) and restart ollama.

**Comment by whoislikegod1** [comment]
Hello all,

i have successfully setup ollama and fabric using wsl. 
The problem i have is how do i have fabric use ollama for prompts?
I can see ollama in --listmodels but whenever i prompt it with "yt --transcript https://youtube.com/watch?v=uXs-zPc63kM -m llama3.1:latest | fabric --stream --pattern extract_wisdom" it hangs.
where do i export my environment variables to? and do those change?
I have read many q/a but cannot find a solution. 

Thank you for any help
