### ISSUE TITLE
[Bug]: If OpenAI has temporary outage - there is no way to use other models (ex. anthropic)

### ISSUE THREAD

**Issue by mwolosewicz** [danielmiessler/fabric#727]
### What happened?

The OpenAI is temporary unavailable so I want to use other model, but I can't change it:

```
fabric --changeDefaultModel claude-3-5-sonnet
Error: Server error '503 Service Temporarily Unavailable' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
fabric --changeDefaultModel claude-3-5-sonnet
Error: Server error '503 Service Temporarily Unavailable' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
```

**Comment by patonw** [comment]
This error handler is too narrow: https://github.com/danielmiessler/fabric/blob/95b58e9e09d2ecc3a1235a1025abb78485eab305/installer/client/cli/utils.py#L426

It should also ignore an (APIStatusError)[https://github.com/openai/openai-python/blob/ec4511a6fa4862770cf14b2b58d3493e9bacb062/src/openai/_exceptions.py#L74] or possibly just all APIErrors

**Comment by alexasherman** [comment]
![photo_2024-10-28_14-09-54](https://github.com/user-attachments/assets/02b604c3-915b-40cd-9264-a6c3010ea63c)
