### ISSUE TITLE
Question on the usage of the `server`.

### ISSUE THREAD

**Issue by agu3rra** [danielmiessler/fabric#73]
I understood the main purpose of the project's `server` is to create endpoints which will host one's own patterns of `system.md` instructions to then forward requests to the OpenAI API. Did I get this right?

I wonder if we could simply "bake" all of the ready to use patterns in the `patterns` folder into the `fabric` CLI directly and then make them discoverable via a built-in `fabric --help` command. We could perhaps allow users to add their own patterns (assuming they won't contribute them back to this repo) into our `~/.fabric/` config folder. Any folder name containing say `~/fabric/foobar/system.md` would then become discoverable for and usable by the CLI.

Does that make any sense? I suppose the alternative is that people should manually add endpoints to the Flask API.

@danielmiessler Thoughts?

**Comment by danielmiessler** [comment]
That's already available. If you don't use the server option, it does exactly what you were describing.
