### ISSUE TITLE
when I use the gui interface the pattern run a generic exemple: 

### ISSUE THREAD

**Issue by owen98fox** [danielmiessler/fabric#731]
### What happened?

when i give a yt transcript in gui interface and select a patternin this case "summarize debate",  (llm llama3 ). I was expecting  to get the summarize of the yt script  but happen instead that it give me a generic interviuwe    "Lera Boroditsky, a cognitive scientist, discusses how our language shapes our thought and perception of reality with Sam Harris, a neuroscientist......"  complitly out of context .

### Version check

- [X] Yes I was.

**Comment by michaellerickson** [comment]
can you give a little more?

how about did you get node and npm?

are you using llama3:70b or llama3:latest?
