### ISSUE TITLE
[Question]: Does Fabric chunk data automatically?

### ISSUE THREAD

**Issue by EatMoreChicken** [danielmiessler/fabric#739]
### Does Fabric chunk data automatically?

After reading the documentation, I am still not clear if Fabric automatically chunks data when sending it to LLMs. For example, if the YouTube video's transcript is too long to fit into the context window, does Fabric automatically chunk the data into multiple requests?

Thank you!

**Comment by bradinator** [comment]
I have received error messages stating I was over the context length.  If there is a way to chunk or otherwise handle longer videos, I'd like to know best practices.

**Comment by EatMoreChicken** [comment]
Hmm, so it sounds like it doesn't chunk the input currently. I know there are several chucking methods out there, but I don't have enough experience at the moment to know the best practice. I'm sure someone else would have some better insight into what needs to be implemented.
