### ISSUE TITLE
[Bug]: pbpaste doenst work

### ISSUE THREAD

**Issue by prometheusone** [danielmiessler/fabric#742]
### What happened?

When I do this command: yt pbpaste | create_summary
it give me always : - The input provided is an invalid YouTube URL, indicating an error in the link format or content access.

however when I copy the actual video ( so press ctr c) and do this yt https://youtu.be/f7Puiilv5Tw | create_summary

it works fine, why is that?

### Version check

- [X] Yes I was.

**Comment by josh-stephens** [comment]
I believe you need to use command substitution here, so try this:
`yt "$(pbpaste)" | fabric -sp create_summary`
