### ISSUE TITLE
When Golang version would be available? Do you need support?

### ISSUE THREAD

**Issue by eugeis** [danielmiessler/fabric#745]
### What is your question?

Hello, great product!
When Golang version would be available? 
Do you need support? I could contribute

Thanks
Eugen

**Comment by blorby** [comment]
Joining the questions (both of them) :)

**Comment by xssdoctor** [comment]
Yes I would love some help. Please email me and lets talk about it

**Comment by blorby** [comment]
i've cloned the repo to anthropic AI with their sonnet 3.5, got this code with some fixes:
https://github.com/blorby/fabric-go

but that's just to understand the work around migration / refactor to go, I guess we'll need a thicker infra before creating patterns for fabric-go - @eugeis agree?

**Comment by xssdoctor** [comment]
Added both of you to the fabric-go repo. talk more there

**Comment by blorby** [comment]
> Added both of you to the fabric-go repo. talk more there

it's a fork with refactor?
