### ISSUE TITLE
[Question]: I'm creating a Go version of Fabric

### ISSUE THREAD

**Issue by cetorres** [danielmiessler/fabric#773]
### What is your question?

Repo: https://github.com/cetorres/ai-buddy

**Comment by persicoDev** [comment]
I'd be glad to assist with that. This approach could serve as an excellent introduction to Fabric for newcomers. By implementing this in Go, we can leverage Fabric as a framework for web applications. Moreover, this method facilitates various other types of integrations, making them straightforward to implement and manage. The combination of Go's efficiency and Fabric's versatility opens up numerous possibilities for robust and scalable solutions.
BUT maybe that's not the goal of this project??

**Comment by mbrydak** [comment]
@cetorres 
Hell yeah. After I've seen fabric I got super excited, I see in the README that it's also gonna be rewrited to Go, but in the meantine – I'd love to try out my Go skills and contribute where possible :D
