### ISSUE TITLE
[Feature request]: Two new options

### ISSUE THREAD

**Issue by michaellerickson** [danielmiessler/fabric#777]
### What do you need?

--export, -e          export as file extension (.txt, .md, .py, .ps1, etc.)
--export_setup, -xp   choose a default file extension for the export, -e option

I propose this improvement for our output to append data (i.e. text/code) into new/existing files.

The shortcuts, -e and -xp, are arbitrary and serve as examples; however, the features could improve code development and document creation.

It might be overkill because https://github.com/danielmiessler/fabric?tab=readme-ov-file#save

**Comment by eugeis** [comment]
Hi, you could just use "> output.md" to redirect the output to a file.
