### ISSUE TITLE
[Question]: I was just wondering if anyone had tried Obsidian + Canolli + Fabric?

### ISSUE THREAD

**Issue by timothyCoxon** [danielmiessler/fabric#778]
### What is your question?

Well, title pretty much covers it..
I am guessing that I don't need to explain Fabric. 

* [Obsidian](https://obsidian.md/) **P**ersonal **K**nowledge **M**anagement system.. Very much like Notion but local, open and extendable. (just in case anyone wasn't already aware of it.). It's got this feature called "Canvas" which is kinda for flow chart and brainstorms. However thanks to the extensions you can extend it's functionalities. Which brings me to...

* [Canolli](https://github.com/DeabLabs/cannoli) which simply put allows you to change the colours of various things or use particular formatting so that the canvas becomes a visual instruction sheet which you can run... 

So as the fabric patterns are all markdown anyway I just cloned the entire patterns directory into obsidian dragged them all onto a canvas where sorted them into a matrix just cause I like to do that kind of thing. My intent was to have a canvas to work on new patterns where I could reference the official ones and see where (for me) the holes where.

![image](https://github.com/user-attachments/assets/7b1877b6-217d-4fdf-9e2b-6bd4eb8459e5)

Then I remembered having seen the cannoli extension, installed it, did a little testing and it does seem to work. I made a couple successful query before I decided to try switch to the local LLM mode on Cannoli which seems to have broken something and now neither work. I've not really had a chance to sit down and work out the issue, but I figured it may be worth sharing that it is a possibility for a GUI with next to no work to get running ;)

![image](https://github.com/user-attachments/assets/d703d1ae-6586-48cf-baf3-96bb48cf914e)

Image above shows a little of what my experiments were like, don't take this as a guide I was trying to work out cannoli but its certainly fun to play around with.. it was very shortly after this I screwed it up with trying for the local llm so I didn't get as far at having it creating new notes or anything like that but it's possible to do with the extension. And no I've not tried to get it running with the js or python canvas block extensions as yet..  

Ooo just thought, of a feature request for Cannoli git..

**Comment by joaomorossini** [comment]
I didn't even know what Cannoli was before I saw your question. Seems really interesting. I'll give it a try! Thanks :D
