### ISSUE TITLE
[Bug]: Youtube yt helper app unable to find matches for any URL

### ISSUE THREAD

**Issue by joaomorossini** [danielmiessler/fabric#783]
### What happened?

I was trying to grab a transcript of a Youtube video and pipe it with the ```extract_business_ideas``` pattern , but got an error stating that no matches were found. I tried different URLs and also double checked that my Youtube API key was enabled. The issue seems to have started after I updated Fabric yesterday (Aug 1st 2024)

### Version check

- [X] Yes I was.

### Relevant log output

```shell
morossini@Joaos-MBP Projects % yt --transcript https://www.youtube.com/watch?v=bemg8bhVO0U
zsh: no matches found: https://www.youtube.com/watch?v=bemg8bhVO0U
```

### Relevant screenshots (optional)

<img width="1188" alt="Screenshot 2024-08-02 at 07 14 43" src="https://github.com/user-attachments/assets/ba9a3606-b75b-4924-a928-2121b64bb7f1">

**Comment by alexasherman** [comment]
![16fb4e7c86c19ffc4afaa](https://github.com/user-attachments/assets/055b9fba-0b90-41a8-a0eb-346d9fcffe3e)

**Comment by joaomorossini** [comment]
Just noticed I forgot the quotes around the URL. My bad
