### ISSUE TITLE
stdin on wsl2 is a nightmare - any solutions?

### ISSUE THREAD

**Issue by salmansarwar5102** [danielmiessler/fabric#789]
I want to use the pattern extract_wisdom on a blog article but stdin on wsl2 is very difficult - can anyone help me?

I am trying this but not working: fabric --pattern extract_article_wisdom > li.txt

**Comment by phren0logy** [comment]
Maybe try "save" to Obsidian? Not exactly what you are looking for, but it might be more effective.
