### ISSUE TITLE
[Bug]: when using ollama with llama3.1:latest can't save output to file

### ISSUE THREAD

**Issue by kcoderhtml** [danielmiessler/fabric#803]
### What happened?

Having set the default model to `llama3.1:latest` with `fabric --changeDefaultModel llama3.1:latest` and restarting my terminal when I run `fabric -t "say hi" -s -o out.txt` it won't save to file. When using llama3 instead it still seems to work. I'm confused as to why this is happening.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
kierank on bjartskular at ~
$ fabric -t "say hi" -s -o out.txt
Hi! How are you today?%                                          
kierank on bjartskular at ~
$ cat out.txt
```

### Relevant screenshots (optional)

![image](https://github.com/user-attachments/assets/bf79ee11-a252-416e-824a-80ef493672b7)

**Comment by fonteijne** [comment]
Hi @kcoderhtml , I assume this is not a bug. 
It's written in de `--help` that when using `-s` to stream the response, it's not possible to pipe it to another comment.

`--stream, -s          Use this option if you want to see the results in realtime. NOTE: You will not be able to pipe the output into another command.`

I _assume_ this is why it's not working.
I've tried the same command, without `-s` and then the file is filled with the response.

**Comment by kcoderhtml** [comment]
Hmm; I was under the impression that the output flag would just concat the response and then save to file regardless of the stdout output.
