### ISSUE TITLE
[Feature request]: Provide binaries as part of releases

### ISSUE THREAD

**Issue by p5** [danielmiessler/fabric#808]
### What do you need?

It's awesome that you switched from Python to Go!  Now we don't need to have Python installed on our workstations to experience Fabric!

Since moving to Go, I assume the application is packaged as a single binary, and doesn't require the typical runtime dependencies (Python or Go), however your installation steps require Go to be installed on the machine.

It would be great if, as part of your release pipelines/processes, you could build and upload these built binaries for each platform so it's just a single curl + chmod to install Fabric. 

The main aim here is to remove as many of the dependencies the user needs to install to get up and running with Fabric, as it's something everyone should try out!

Apologies if I am missing some of the limitations that require this installation method.

If this is something you'd like to include, I am happy to work on it.

**Comment by xssdoctor** [comment]
the pipeline is running. Thanks @eugeis!!

**Comment by p5** [comment]
> the pipeline is running. Thanks @eugeis!!

If the existing workflow is supposed to be linking these binaries to releases, I believe it will need some changes.

https://github.com/danielmiessler/fabric/blob/main/.github%2Fworkflows%2Fgo.yml#L53

This upload-artifact step attached the binaries to the workflows, but not the release.  This makes it nearly impossible for people to see.

Rather than attaching the binaries to each workflow run, we need to link them to the tagged release.

**Comment by ideologysec** [comment]
Also, there's really no need for the macOS binary to get put into a DMG - that's an extra step on both ends (packaging and installing) that doesn't need to be there.

**Comment by p5** [comment]
CC @xssdoctor 
I've PR'd a fix to include the binaries in future GitHub Releases.  I'm not entirely sure if it's setup correctly, but it's an attempt at making something that looks about right 😆

**Comment by ideologysec** [comment]
@p5 done as #812
