### ISSUE TITLE
Documentation Enhancement for Poetry Users - Executable Access

### ISSUE THREAD

**Issue by cycorld** [danielmiessler/fabric#81]
## Description
I recently installed `fabric` using `poetry` and encountered an issue where the `fabric` executable was not directly accessible from the command line. Despite a successful installation, this led to some confusion and required additional steps to resolve the issue.

## Issue Details
- **Environment**: macOS
- **Installation Method**: Poetry
- **Fabric Version**: 1.0.0
- **Python Version**: 3.12

## Problem
After installing `fabric` with `poetry`, I found that attempting to run the `fabric` command in the terminal resulted in a "command not found" error. This issue appears to be due to the `fabric` executable being placed in the virtual environment's `bin` directory, which is not automatically included in the system's `PATH`.

## Temporary Solution
I was able to manually resolve this issue by creating an alias for the `fabric` executable located within the poetry-created virtual environment. Here are the steps I took:

1. Locate the `fabric` executable within the `poetry` virtual environment:
   ```shell
   find ~/Library/Caches/pypoetry/virtualenvs -name fabric
   ```
2. Create an alias in my shell configuration file (`.bashrc` or `.zshrc`):
   ```shell
   alias fabric='/path/to/virtualenv/bin/fabric'
   ```
   Please replace `/path/to/virtualenv/bin/fabric` with the actual path to the executable found in step 1.

## Suggested Improvement
To improve the user experience and assist future users who might encounter a similar situation, I suggest updating the installation documentation with a note or section dedicated to `poetry` users. This could include guidance on how to locate the `fabric` executable within the `poetry` virtual environment and recommend creating an alias for easier use.

## Conclusion
Incorporating this information into the documentation could greatly streamline the setup process for users installing `fabric` via `poetry`, ensuring a smoother initial experience. Thank you for considering this suggestion to enhance the project's documentation and user accessibility.

**Comment by danielmiessler** [comment]
We're currently working to optimize the CLI and GUI installers. This should be fixed soon. Thank you!
