### ISSUE TITLE
[Bug]: Unable to migrate to Go version of Fabric

### ISSUE THREAD

**Issue by DrkPh0enix** [danielmiessler/fabric#814]
### What happened?

I was migrating to the new Go version. I first did pipx uninstall fabric, no errors it said fabric was uninstalled. Next ran go install github.com/danielmiessler/fabric@latest with no errors. Ran fabric --setup and received: fabric: command not found. I can see the bin file for fabric. 

### Version check

- [X] Yes I was.

### Relevant log output

```shell
user@user:~$ sudo go install github.com/danielmiessler/fabric@latest
go: downloading github.com/danielmiessler/fabric v1.4.0
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/samber/lo v1.47.0
go: downloading github.com/jessevdk/go-flags v1.6.1
go: downloading github.com/go-git/go-git/v5 v5.12.0
go: downloading github.com/sashabaranov/go-openai v1.28.2
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/otiai10/copy v1.14.0
go: downloading github.com/liushuangls/go-anthropic/v2 v2.6.0
go: downloading google.golang.org/api v0.192.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/google/generative-ai-go v0.17.0
go: downloading github.com/ollama/ollama v0.3.6
go: downloading golang.org/x/text v0.16.0
go: downloading golang.org/x/sys v0.24.0
go: downloading golang.org/x/sync v0.8.0
go: downloading golang.org/x/oauth2 v0.22.0
go: downloading google.golang.org/grpc v1.64.1
go: downloading cloud.google.com/go/auth v0.8.1
go: downloading github.com/google/s2a-go v0.1.8
go: downloading cloud.google.com/go/compute/metadata v0.5.0
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.2
go: downloading cloud.google.com/go/auth/oauth2adapt v0.2.3
go: downloading github.com/ProtonMail/go-crypto v1.0.0
go: downloading dario.cat/mergo v1.0.0
go: downloading github.com/go-git/go-billy/v5 v5.5.0
go: downloading github.com/pjbgf/sha1cd v0.3.0
go: downloading github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3
go: downloading github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376
go: downloading github.com/emirpasic/gods v1.18.1
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading cloud.google.com/go v0.115.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/skeema/knownhosts v1.2.2
go: downloading github.com/kevinburke/ssh_config v1.2.0
go: downloading github.com/xanzy/ssh-agent v0.3.3
go: downloading golang.org/x/crypto v0.25.0
go: downloading golang.org/x/net v0.27.0
go: downloading cloud.google.com/go/ai v0.8.0
go: downloading github.com/googleapis/gax-go/v2 v2.13.0
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240730163845-b1a4ccb954bf
go: downloading google.golang.org/protobuf v1.34.2
go: downloading github.com/cyphar/filepath-securejoin v0.2.4
go: downloading gopkg.in/warnings.v0 v0.1.2
go: downloading github.com/google/uuid v1.6.0
go: downloading go.opencensus.io v0.24.0
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.51.0
go: downloading github.com/cloudflare/circl v1.3.7
go: downloading github.com/felixge/httpsnoop v1.0.4
go: downloading go.opentelemetry.io/otel v1.26.0
go: downloading go.opentelemetry.io/otel/metric v1.26.0
go: downloading go.opentelemetry.io/otel/trace v1.26.0
go: downloading cloud.google.com/go/longrunning v0.5.7
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20240711142825-46eb208f015d
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.51.0
go: downloading golang.org/x/time v0.6.0
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/go-logr/logr v1.4.2
user@user:~$ fabric --setup
fabric: command not found
```

**Comment by xssdoctor** [comment]
Open up a new terminal window and see what happens

**Comment by DrkPh0enix** [comment]
Same result :(

**Comment by otnl** [comment]
Same here.  Is it an Apple Arm issue? Im on M1 and having the same problem

**Comment by otnl** [comment]
Ok for whatever reason, fabric is installed into ~/go/bin/fabric on my system instead of I think the default ~/.local/bin/fabric

So check that folder and then add to PATH

export PATH=".:$PATH:/Users/USERNAME/go/bin"

**Comment by builder555** [comment]
same issue here

**Comment by johnconnor-sec** [comment]
> Ok for whatever reason, fabric is installed into ~/go/bin/fabric on my system instead of I think the default ~/.local/bin/fabric
> 
> So check that folder and then add to PATH
> 
> export PATH="$PATH:/home/USERNAME/go/bin"

This seems to work, thank you!

**Comment by npayton77** [comment]
Were you able to get the YouTube transcript installed as part of the Go install? I had the same path issue, but I am not seeing the yt transcript downloader being installed.

**Comment by otnl** [comment]
Also to add it to your .zshrc file so it always adds to PATH you can run
echo 'export PATH=".:$PATH:/Users/USERNAME/go/bin"' >> ~/.zshrc

**Comment by DrkPh0enix** [comment]
Oh my gosh that’s a doh moment on my part, I even said I could see the bin file but didn’t connect the dots till now. I’ll try this first thing and see how it goes but I expect it will work

     Respectfully,

Kellen Munden
________________________________

**Comment by DirgoSalga** [comment]
I have also migrated to the Go version and I am able to run the program now and do the initial setup. The yt helper command is no longer available. During setup I was also not asked to provide my YouTube API key.

Any plans of making that tool also available in the new version?

**Comment by xssdoctor** [comment]
Yt is now its own repo. Also in go https://github.com/danielmiessler/yt

**Comment by DrkPh0enix** [comment]
> Ok for whatever reason, fabric is installed into ~/go/bin/fabric on my system instead of I think the default ~/.local/bin/fabric
> 
> So check that folder and then add to PATH
> 
> export PATH=".:$PATH:/Users/USERNAME/go/bin"

This worked, thank you @otnl :)
