### ISSUE TITLE
[Bug]: yt command is missing in go version

### ISSUE THREAD

**Issue by tfriedel** [danielmiessler/fabric#821]
### What happened?

In the python version there was a "yt" version. It seems gone now, in the go version. 
I'd like to have it back. 

### Version check

- [X] Yes I was.

**Comment by tfriedel** [comment]
answering my own question:
it's now in a new repo.
So run:
go install github.com/danielmiessler/yt@latest

This should be added to the readme.

**Comment by DrkPh0enix** [comment]
I did this then ran setup again expecting to enter my youtube API key but was never asked to enter it, any idea on where to put that?

**Comment by xssdoctor** [comment]
If you run yt without the key the error message will tell you what to do

**Comment by DrkPh0enix** [comment]
> If you run yt without the key the error message will tell you what to do

Thank you! Any one having any troubles with their API keys, specifically Gemini?

**Comment by xssdoctor** [comment]
Try it again now. Gemini should now be working

**Comment by danielmiessler** [comment]
It's in the readme now too.

**Comment by Stehos** [comment]
Hi everyone, I came back to Fabric after a few months so I installed it via brew on my macbook but can not use it like before e.g. fabric -y “[https://youtube.com/watch?v=uXs-zPc63kM”](https://youtube.com/watch?v=uXs-zPc63kM%E2%80%9D) –stream –pattern extract_wisdom

it says: YouTube is not configured, please run the setup procedure

does it mean that I need youtube api key?

how it was working before when the API key was not needed? at least I did not find any youtube api keys

**Comment by ksylvan** [comment]
Yes, you need a YouTube API key.

To obtain a YouTube API key, follow these steps:

Log in to the Google Developers Console using your Google account. If you do not have one, create one.

Create a new project by clicking on "Create Project" and entering a project name.

Navigate to the "Explore & Enable APIs" card or go to "APIs & Services > Library" and enable the YouTube Data API v3.

Create credentials by clicking "Create credentials" and selecting "API key". 

An API key will be generated, which you can copy and use in your project.

See https://developers.google.com/youtube/registering_an_application

**Comment by Stehos** [comment]
@ksylvan thank you. it is working fine. but don't you know, how it was working before? I am almost sure that I did not use YouTube Data API v3 last year.

**Comment by ksylvan** [comment]
I don't know. 😄 I'm glad it's working for you now.
