### ISSUE TITLE
[Bug]: Reset command not working

### ISSUE THREAD

**Issue by theblackrussian** [danielmiessler/fabric#823]
### What happened?

I am unable to reset the openAI API key. I entered a key once (key1), deleted that key and now I'm unable to replace it with a brand new API key (key2). I am certain key2 works because I got it tested in Postman with the embeddings. I attached the bash output. As I said, the key in there is key1. I tried entering "reset", 'reset', reset, RESET -- nothing works. How do I replace that bloody api key? I also attached the output I get when trying to configure with `fabric -S` As you can see, I get the message [OpenAI] skiped
None of this makes sense to me..

### Version check

- [X] Yes I was.

### Relevant log output

```shell
error, status code: 401, message: Incorrect API key provided: sk-f2M85***************************************7r4G. You can find your API key at https://platform.openai.com/account/api-keys.

--

Enter your OpenAI API KEY (leave empty for 'sk-f2M85dkdhbZ4OFvCIy5<censored>FJG2cIIn8R334syJ0P7r4G' or type 'reset' to remove the value):
reset
[OpenAI] skiped
```

**Comment by xssdoctor** [comment]
I don't really understand your issue. But you should try to run --setup again and if that doesn't work go into ~/.config/fabric/.env and manually enter your api key

**Comment by theblackrussian** [comment]
@xssdoctor the issue is stated clearly:
> I entered a key once (key1), deleted that key and now I'm unable to replace it with a brand new API key (key2).

As I already stated, the setup doesn't bring any positive outcome.

I checked `~/.config/fabric/.env` and this is key2 in there. Now I'm even more confused.
As I said, key2 is working, I got it tested in Postman few mins ago.

Look at the screen, I can be any clearer. You can clearly see two different keys. Yet, I ran the setup 20 times already. 

**THE API CALL IS STILL MADE WITH THE OLD KEY.**

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/dceb2cc2-b070-46ef-8457-3135b348bff5">

**Comment by xssdoctor** [comment]
That env file looks correct. There seems to be one OpenAI api key in there. If you are getting an error that the key isn't working, I'm not sure what you should do. Which model are you trying to use? Some models only work if there is a certain amount of money in the account

**Comment by theblackrussian** [comment]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/043e8323-310b-43dc-8e3c-4d6fbca69683">



> Some models only work if there is a certain amount of money in the account

Really?

**Comment by xssdoctor** [comment]
Yeah those should all work. Idk that's a really weird error message. I'm trying to reproduce this and I can't

**Comment by theblackrussian** [comment]
@xssdoctor thank you for your assistance with this.

I am still unable to make those API calls, but it appears clear to me that the issue is not from fabric but from openAI themselves.
