### ISSUE TITLE
[Bug]: stream error: stream ID 3; CANCEL; received from peer

### ISSUE THREAD

**Issue by UlwaziM** [danielmiessler/fabric#827]
### What happened?

I was doing [Patterns Loader]

Enter the default Git repository URL for the patterns (leave empty for 'https://github.com/danielmiessler/fabric.git' or type 'reset' to remove the value):

Enter the default folder in the Git repository where patterns are stored (leave empty for 'patterns' or type 'reset' to remove the value):

Downloading patterns and Populating C:\Users\ulwaz\.config\fabric\patterns..

, when stream error: stream ID 3; CANCEL; received from peer
stream error: stream ID 3; CANCEL; received from peer happened. I was expecting the patterns to download without any issues.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
stream error: stream ID 3; CANCEL; received from peer
stream error: stream ID 3; CANCEL; received from peer
```

### Relevant screenshots (optional)

![Screenshot 2024-08-18 142942](https://github.com/user-attachments/assets/d47f2834-539c-4f60-81a6-e574721f3b6f)

**Comment by danielmiessler** [comment]
I think this is coming from the remote API. Try another model and I bet you don't have that issue. I've had similar issues recently with Google.

**Comment by rhoconlinux** [comment]
Hy there, I know this is not a proper solution, but I might become handy to overcome this bug. I run this line in the terminal: 

`
cd /tmp ; git clone https://github.com/danielmiessler/fabric.git ; cp -r fabric-main/patterns ~/.config/fabric/ ; rm -rf fabric-main ; cd ~
`

Cheers.

**Comment by salmansarwar5102** [comment]
> Hy there, I know this is not a proper solution, but I might become handy to overcome this bug. I run this line in the terminal:
> 
> `cd /tmp ; git clone https://github.com/danielmiessler/fabric.git ; cp -r fabric-main/patterns ~/.config/fabric/ ; rm -rf fabric-main ; cd ~`
> 
> What it does?:
> 
> Clones the repository to a temporary directory. Copies the "patterns" folder to ~/.config/fabric/. Deletes the cloned repository. Returns to your home directory.
> 
> Cheers.

sam@LAPTOP-S5LCRFHR:~/.config/fabric$ cd /tmp ; git clone https://github.com/danielmiessler/fabric.git ; cp -r fabric-main/patterns ~/.config/fabric/ ; rm -rf fabric-main ; cd ~
Cloning into 'fabric'...
remote: Enumerating objects: 10958, done.
remote: Counting objects: 100% (3822/3822), done.
remote: Compressing objects: 100% (1648/1648), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2583 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
cp: cannot stat 'fabric-main/patterns': No such file or directory

**Comment by salmansarwar5102** [comment]
Ethernet solved the issue, weird but it worked for me.

**Comment by GalloaFranco** [comment]
> Ethernet solved the issue, weird but it worked for me.

Yeap, +1 with this troubleshooting. I plugged ethernet on my laptop and voila! thanks 👍
