### ISSUE TITLE
[Bug]: After installation fabric --setup doesn't work in go version

### ISSUE THREAD

**Issue by caunus** [danielmiessler/fabric#830]
### What happened?

After installing with 
```bash
go install github.com/danielmiessler/fabric@latest
```
calling `fabric --setup` didn't work because I didn't have the following line in my `.zshrc` on my Mac:
```bash
export PATH="$PATH:$HOME/go/bin"
```
I'm not sure if I will also need the `GOPATH`. It would be nice if this could be added during installation or at least mentioned in the README. Thanks!

### Version check

- [X] Yes I was.

**Comment by danielmiessler** [comment]
Thank you. We'll add that to the install.
