### ISSUE TITLE
[Bug]: YouTube API key can't be blank

### ISSUE THREAD

**Issue by ideologysec** [danielmiessler/fabric#832]
### What happened?

Set up fabric, leave YouTube API key blank (I don't use it).

Expected: works fine

Actual: `YOUTUBE_API_KEY=, is not valid`

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

<img width="361" alt=" 2024-08-18 at 21 58 41" src="https://github.com/user-attachments/assets/bef88489-847f-46a8-9ebc-cf938740f2d2">

**Comment by iqbalabd** [comment]
As a workaround, I ran `fabric --setup` again and entered a random letter (i.e A) when asked for my YOUTUBE API Key although I don't use it. That allowed me to continue with the setup and use fabric.

**Comment by xssdoctor** [comment]
you're right this is an issue. I'll take a look

**Comment by richardstevenhack** [comment]
Second that. Just happened to me.

**Comment by xssdoctor** [comment]
its fixed. Thank you as always @eugeis (seriously this guy has skills)
