### ISSUE TITLE
[Question]: What is the License?

### ISSUE THREAD

**Issue by leobenkel** [danielmiessler/fabric#833]
### What is your question?

I do not see a LICENSE file in this repo. How is it permitted to use this system?

**Comment by mattsilv** [comment]
came here to ask the same question

**Comment by alucarded** [comment]
+1

**Comment by jaredmontoya** [comment]
Seems like in the past it was [MIT](https://github.com/danielmiessler/fabric/blob/agents/LICENSE.txt) and I hope it stays this way, otherwise I will have to mark this as unfree in NixOS repositories. https://github.com/NixOS/nixpkgs/pull/335359

**Comment by jaredmontoya** [comment]
@danielmiessler I packaged fabric for NixOS but the package is not being merged because there is no LICENSE file. Can you please clarify how the project is licensed? Thank you in advance.
