### ISSUE TITLE
[Question]: what are sessions and how do we use em

### ISSUE THREAD

**Issue by Uddhav07** [danielmiessler/fabric#838]
### What is your question?

After reading the documentation, I am still not clear how to get X working. I tried this, this, and that.

**Comment by xssdoctor** [comment]
try this, this should explain it 
echo 'my name is jon' | fabric --session jon

then

echo 'what is my name' | fabric --session jon

basically you name the session, then everythign is saved within that session file, so you can continue your conversation

**Comment by Uddhav07** [comment]
> try this, this should explain it echo 'my name is jon' | fabric --session jon
> 
> then
> 
> echo 'what is my name' | fabric --session jon
> 
> basically you name the session, then everythign is saved within that session file, so you can continue your conversation

![image](https://github.com/user-attachments/assets/e127da98-0890-4551-a47b-f86f2506a0cc)
this ai is dumb lmao but its gemini 1.5 pro exp

**Comment by xssdoctor** [comment]
hmmm i have to take a look, maybe sessions isn't working for gemini

**Comment by Uddhav07** [comment]
> hmmm i have to take a look, maybe sessions isn't working for gemini

the first message didnt work, the second message it did remember

**Comment by ksylvan** [comment]
What's the difference between "sessions" and "contexts"?
