### ISSUE TITLE
[Bug]: Unable to add context in windows

### ISSUE THREAD

**Issue by Uddhav07** [danielmiessler/fabric#839]
### What happened?

I was doing THIS, when THAT happened. I was expecting THAT_OTHER_THING to happen instead.

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

![image](https://github.com/user-attachments/assets/63439190-833f-4848-ada8-9b85ed9b03f6)

**Comment by conacts** [comment]
If I'm not mistaken, it looks like this [commit](https://github.com/danielmiessler/fabric/commit/b01bedb54a4233987feb1252f3a259948b5c23fb) removed the `add context` feature. So maybe this isn't a bug?

**Comment by Uddhav07** [comment]
Oh ok but why

**Comment by xssdoctor** [comment]
tbh i thought it was a stupid feature. A user can literally just do it themselves in the ~/.config/contexts folder. The way I implimented it was bad too. All in all, it was a bad implimentation of an unnecessary feature. If enough people want it back, I can do it easily. But Again, just add a contexts folder and put the context in that folder.

**Comment by conacts** [comment]
idk

**Comment by conacts** [comment]
Isn't taking the folder ~/.config/contexts kinda generic? Wouldn't it make more sense to have it in a ~/.config/fabric folder?

**Comment by xssdoctor** [comment]
Typo. I meant .config/fabric/contexts

**Comment by danielmiessler** [comment]
We don't have the feature there right now, but might add it back soon. Thank you!
