### ISSUE TITLE
Adding own patterns

### ISSUE THREAD

**Issue by doublej** [danielmiessler/fabric#85]
I've created a folder with the system and user file and I've tried running update. But it's not recognizing my added pattern and returns "pattern not found".

What is the right process?

**Comment by danielmiessler** [comment]
No you have to submit a PR to the repo with a requested change to /patterns. And be sure to put it under the main pattern directory with your own username, like I did for /extract_wisdom.

**Comment by danielmiessler** [comment]
Thank you.

**Comment by doublej** [comment]
That seems like a bit much for initial testing? For basic testing purposes I'm editing the files in `~/.config/fabric` for now.
