### ISSUE TITLE
[Bug]: How to use Azure? Setup does not work

### ISSUE THREAD

**Issue by DmacMcgreg** [danielmiessler/fabric#859]
### What happened?

When running setup, its not clear what to put in the endpoint. I've tried a couple of variations of the model, deployment, and api version, along with just the entire string, and it does not seem to work. I keep getting a 404. 
I know that the end point works, since I can make curl requests, and use it in many other applications.

### Version check

- [X] Yes I was.

**Comment by eugeis** [comment]
It is usually something like this:
https://<xy>.openai.azure.com

Go to https://portal.azure.com and your Azure OpenAI service

<img width="246" alt="image" src="https://github.com/user-attachments/assets/eeca91eb-2c52-457b-8d12-a7a0de7f2209">

You will see two keys and the endpoint / base URL.

**Comment by eugeis** [comment]
If it not working for you, please provide more infos.

My endpoint works without problems.

**Comment by DmacMcgreg** [comment]
![CleanShot 2024-08-22 at 16 27 37@2x](https://github.com/user-attachments/assets/a300038d-7ec6-4290-a061-83cda9dcbe9b)
![CleanShot 2024-08-22 at 16 30 04@2x](https://github.com/user-attachments/assets/c005d7d4-f9a4-4c4f-ab68-7d53d8ab1928)
![CleanShot 2024-08-22 at 16 31 09@2x](https://github.com/user-attachments/assets/09810766-8de8-4120-ad36-7b9f56f1a260)

**Comment by eugeis** [comment]
base url / endpoint is only this, 

https://xy.openai.azure.com

without other parts

**Comment by DmacMcgreg** [comment]
Thanks, it works. I would suggest making the instructions a bit stronger though, as it's clearly not idiot proof. 😉
