### ISSUE TITLE
README Instructions need more Clarification

### ISSUE THREAD

**Issue by lmccay** [danielmiessler/fabric#86]
I noticed through one of the older issues that it is expected that you run "poetry shell" to pick up the installed dependencies and find the CLI. This should be added to the instructions after "poetry install", I think.

Steps 5 and 6 seem redundant and maybe slightly inaccurate? When I tried that it:
1. first attempted to run it as a bash script - complaining that there was a problem near the unexpected token '('...
2. then I changed the alias to be "python3 /path/to/fabric/client/fabric" and it complained that it was a directory...
3. then I change it to fully qulify the path to the fabric.py file
4. then it failed to import the dependencies and modules installed by poetry
5. once I used "poetry shell" it seems to work

So, I'd like to fix up the instructions but am not sure what exactly we need to do.

I can certainly interject the use of "poetry shell" but do we actually expect the bashrc alias bit to work without being in the shell?
If so, what else do we need to do there?

Also, what should step 6 actually be? Seems to just be a slight variation on 5 even though it says to restart your shell and to make sure you can do something...

**Comment by mattjoyce** [comment]
@lmccay , I had the same issues, and used the same approach.
navigate to ~/fabric/client/
poetry shell
alias fabric="python3 ~/fabric/client/fabric/fabric.py"

**Comment by lmccay** [comment]
I think that I am going to assume that step 6 should consist of:

poetry shell
and
fabric -h

Not sure that is what was intended there but it at least makes sense and adds the missing need to use shell.

**Comment by danielmiessler** [comment]
We're fixing this as we speak. Thank you!
