### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by sosacrazy126** [danielmiessler/fabric#869]
### What is your question?

I noticed at the end of the README that Jonathan Dunn was recognized as the MVP dev on the project, particularly for leading the development of the new Go version and the GUI, all while being a full-time medical doctor! I wanted to ask if the GUI feature has been changed, because when I run fabric --gui, it doesn't work the same way it did in the pipx version.

**Comment by xssdoctor** [comment]
Haha thanks! I'm working on the gui. It's almost done. I'll let you know
