### ISSUE TITLE
[Bug]: Duplicate output, ignoring patterns

### ISSUE THREAD

**Issue by M15071060** [danielmiessler/fabric#870]
## I was doing THIS:

Setting up Fabric and testing the `yt` function with both the `summarize` and other patterns.

## , when THAT happened. 

Fabric seems to correctly pull the transcript and analyze it, however it **always** summarizes* and typically (though I have seen it not do this a few times) doubles the output: 

![image](https://github.com/user-attachments/assets/00b0b1e9-e41c-47b8-b1f4-71668f2dd1ab)

As I mentioned also, which may be a separate issue, the pattern seems to be ignored, **except** when I first pipe to `summarize`

Without summary first:

![image](https://github.com/user-attachments/assets/0924c431-be9a-4788-9b18-354427791ca1)

With summary first:

![image](https://github.com/user-attachments/assets/7b5442ee-1b6f-4a97-ae6d-97b2f2362793)

Again, still duplicating.

## I was expecting THAT_OTHER_THING to happen instead.

Ideally you don't have to pipe through `summarize` first, and there should not be a duplicated output.

I am on 

Debian GNU/Linux bookworm 12.6 x86_64
go version go1.23.0 linux/amd64
Using self-hosted LLMs, both Mistral and llama3

I apologize if there's an obvious setting or something I missed, but I didn't see an issue quite like this anywhere that I could find readily

### Version check

- [X] Yes I was.

**Comment by r-darwish** [comment]
It seems that it has [already been fixed](https://github.com/danielmiessler/fabric/commit/0ef4e465e4590211b78b0c78fb8c7d4f38ce224a), although I experience this as well when installing using `go install github.com/danielmiessler/fabric@latest`
There's also [another debug output](https://github.com/danielmiessler/fabric/blob/main/vendors/ollama/ollama.go#L95-L97) by Fred

**Comment by LegalPrimes** [comment]
I am getting the same issue, no matter what youtube url I put in when testing the yt | fabric --stream --pattern extract_wisdom command it outputs something like "insights related to the meaning of life, human flourishing, technology's role in the future, artificial intelligence, memes, learning, reading, books, continuous improvement, and similar topics." no matter the topic of the video or if i change the youtube url.

**Comment by eugeis** [comment]
It shall be fixed by now, please retest, thx.
