### ISSUE TITLE
[Question]: Unable to install / migrate to GO

### ISSUE THREAD

**Issue by initcyber** [danielmiessler/fabric#884]
### What is your question?

After reading the documentation, I am still not clear how to get this installation/migration working. I tried the following from the readme:
# Uninstall Legacy Fabric
pipx uninstall fabric

# Clear any old Fabric aliases
(check your .bashrc, .zshrc, etc.)
# Install the Go version
go install github.com/danielmiessler/fabric@latest

(Error starts here/above - I don't even get to the below:)
# Run setup for the new version. Important because things have changed
fabric --setup

And I get this:
$ go install github.com/danielmiessler/fabric@latest
go: github.com/danielmiessler/fabric@latest (in github.com/danielmiessler/fabric@v1.4.3): go.mod:3: invalid go version '1.22.5': must match format 1.23
go.mod:5: unknown directive: toolchain

**Comment by snafu4** [comment]
Try updating to version 1.23 of go.

**Comment by initcyber** [comment]
That was it... Disregard
