### ISSUE TITLE
[Bug]: ERROR: Directory '/home/zzzz/fabric' is not installable. 

### ISSUE THREAD

**Issue by zbhul** [danielmiessler/fabric#886]
### What happened?

I did git clone https://github.com/danielmiessler/fabric.git this worked fine
cd fabric
installed pipx
when i run command pipx install . then i get this error below. Trying to follow networkchucks directions

[Bug]: ERROR: Directory '/home/zzzz/fabric' is not installable. Neither 'setup.py' nor 'pyproject.toml' found. Cannot determine package name from spec '/home/zzzz/fabric'. Check package spec for errors.

I cant get fabric to even install Im doing it on wsl ubuntu

### Version check

- [X] Yes I was.

**Comment by SecretAardvark** [comment]
Those files aren't in the repo anymore because they migrated to Golang. Here's the latest installation instructions: 
https://github.com/danielmiessler/fabric?tab=readme-ov-file#Installation

**Comment by eugeis** [comment]
I can't reproduce, please retest in the current release and reopen if it still occurs.
