### ISSUE TITLE
[Question]: How do I change the preferred output language?

### ISSUE THREAD

**Issue by Hole-code** [danielmiessler/fabric#890]
### What is your question?

How do I change the preferred output language?

**Comment by Hole-code** [comment]
$ yt --transcript https://www.youtube.com/watch?v=vF-MQmVxnCs | fabric --stream --pattern extract_wisdom --context=a.md

I understand that you can add a context, but I don't understand how to make some context default so that you don't have to specify it every time. But context is cool and this way of selecting contexts is great because it allows you to quickly select the right one. but now I'm looking for a way to set a default context.

**Comment by eugeis** [comment]
It is available in the current release:

-g, --language=                   Specify the Language Code for the chat, e.g. -g=en -g=zh
