### ISSUE TITLE
[Question]: Error when using the command "pip install ." and "fabric --setup"

### ISSUE THREAD

**Issue by Jusscon** [danielmiessler/fabric#901]
### What is your question?

I get this error everytime i try to use "pipx install ." 
pipx install .
ERROR: Directory '/home/vigilante' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Cannot determine package name from spec '/home/vigilante'. Check package spec
for errors.
Could you please help me?

**Comment by hvega6** [comment]
It says you need to install go so that you can run the command fabric. I am having trouble installing it

**Comment by eugeis** [comment]
Please check README.md, after Go ist installed, here is how to install, or you can download binaries from the release page:

Here my output:

`❯ go install github.com/danielmiessler/fabric@latest
go: downloading github.com/danielmiessler/fabric v1.4.21

~ via 🐹 v1.23.1 took 14s
❯ fabric
no session, pattern or user messages provided

~ via 🐹 v1.23.1
❯ fabric -h
Usage:
  fabric [OPTIONS]

Application Options:
  -p, --pattern=                    Choose a pattern
  -v, --variable=                   Values for pattern variables, e.g. -v=$name:John -v=$age:30
  -C, --context=                    Choose a context
      --session=                    Choose a session
  -S, --setup                       Run setup
      --setup-skip-update-patterns  Skip update patterns at setup
  -t, --temperature=                Set temperature (default: 0.7)
  -T, --topp=                       Set top P (default: 0.9)
  -s, --stream                      Stream
  -P, --presencepenalty=            Set presence penalty (default: 0.0)
  -r, --raw                         Use the defaults of the model without sending chat options (like temperature etc.) and use the user role
                                    instead of the system role for patterns.
  -F, --frequencypenalty=           Set frequency penalty (default: 0.0)
  -l, --listpatterns                List all patterns
  -L, --listmodels                  List all available models
  -x, --listcontexts                List all contexts
  -X, --listsessions                List all sessions
  -U, --updatepatterns              Update patterns
  -c, --copy                        Copy to clipboard
  -m, --model=                      Choose model
  -o, --output=                     Output to file
  -n, --latest=                     Number of latest patterns to list (default: 0)
  -d, --changeDefaultModel          Change default pattern
  -y, --youtube=                    YouTube video url to grab transcript, comments from it and send to chat
      --transcript                  Grab transcript from YouTube video and send to chat
      --comments                    Grab comments from YouTube video and send to chat
      --dry-run                     Show what would be sent to the model without actually sending it
  -u, --scrape_url=                 Scrape website URL to markdown using Jina AI
  -q, --scrape_question=            Search question using Jina AI

Help Options:
  -h, --help                        Show this help message`

**Comment by JJcol89** [comment]
this all new to me using AI. I get stuck when I run "pipx install ." I already installed "Go" but I keep getting the same error, I was following NetworkChuck YouTube video. this is the error:

ERROR: Directory '/home/jjk/fabric' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Cannot determine package name from spec '/home/jjk/fabric'. Check package spec for errors.

please help!!

**Comment by ksylvan** [comment]
Are you using the latest go based fabric?

The pipx instructions are very old at this point and no longer apply.

```bash
# Install Fabric directly from the repo
go install github.com/danielmiessler/fabric@latest
```

Please read the instructions here for more info:

https://github.com/danielmiessler/fabric?tab=readme-ov-file#installation
