### ISSUE TITLE
[Bug]: "FRED ==>"  doubles output in fabric in combination with local ollama

### ISSUE THREAD

**Issue by mreinwarth** [danielmiessler/fabric#903]
### What happened?

Hi, first: thanks for the great work. Love fabric!

Context: 
* most recent version of fabric on Mac OS 14.6.1 (23G93), 
* **local ollama** with various LLMs, example is llama3.1, but the actual model doesn't matter

Not a go developer, not a heavy GitHub user, but I think I've spotted an issue 
This is what I did (as an example): 

```
~ matthias$ echo "Paul Auster or Haruki Murakama"|fabric -p ai
* Both authors explore the human condition in their works.
* They often incorporate magical realism and philosophical themes.
* Their writing styles are highly lyrical and poetic, respectively.FRED ==> 
* Both authors explore the human condition in their works.
* They often incorporate magical realism and philosophical themes.
* Their writing styles are highly lyrical and poetic, respectively.
```
please note the duplicate response and the string "FRED ==>" at the end of the first instance of the response (output line3)

fabric-main/vendors/ollama/ollama.go line 94 has something like that, not sure if this is the cause, 

```
        if err = o.client.Chat(ctx, &req, respFunc); err != nil {
                fmt.Printf("FRED --> %s\n", err)
        }
        return
```

Thanks in advance for checking, Matthias 

### Version check

- [X] Yes I was.

**Comment by mreinwarth** [comment]
for the time being I wrote a shell filter that removes everything starting with "FRED" and the duplicate text, so that I can use fabric at all again...

**Comment by martinjwoo** [comment]
I've got the same, with no output at all apart from the FRED==>, regardless the model or pattern.

For me it's when I've pbpaste'd and it turns out there's some other crap on the clipboard, usually a very terse piece of text ie not enough for fabric/ LLM to get anything out of. 

hope this helps....
