### ISSUE TITLE
[Bug]: After following Migration instructions "GOPROXY" and "GOSUMDB" remain as issues

### ISSUE THREAD

**Issue by maibarra** [danielmiessler/fabric#906]
### What happened?

I was doing [the migration process](https://github.com/danielmiessler/fabric?tab=readme-ov-file#migration), when THIS happened: after attempting ` go install github.com/danielmiessler/fabric@latest`
```
go: github.com/danielmiessler/fabric@latest: GOPROXY list is not the empty string, but contains no entries
```

After I setup `GOPROXY=https://proxy.golang.org,direct` through zshrc, here's what happened:

```github.com/danielmiessler/fabric@v1.4.3: verifying module: missing GOSUMDB```

. I was expecting Installation in goland to happen instead.

Is there an easier way to migrate old Python-based fabric to new Golang-esque Fabric?

Or should i just try and install the old version again?

Thanks in advance.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
alternative "go install ." showed this output:
go install .                                                              ✔  base   at 16:18:20 
go: downloading github.com/jessevdk/go-flags v1.6.1
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/samber/lo v1.47.0
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/go-git/go-git/v5 v5.12.0
go: downloading github.com/otiai10/copy v1.14.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/liushuangls/go-anthropic/v2 v2.6.0
go: downloading github.com/sashabaranov/go-openai v1.28.2
go: downloading github.com/ollama/ollama v0.3.6
go: downloading github.com/google/generative-ai-go v0.17.0
go: downloading google.golang.org/api v0.192.0
go: downloading github.com/anaskhan96/soup v1.2.5
core/fabric.go:6:2: GOPROXY list is not the empty string, but contains no entries
db/db.go:5:2: GOPROXY list is not the empty string, but contains no entries
db/storage.go:6:2: GOPROXY list is not the empty string, but contains no entries
vendors/anthropic/anthropic.go:9:2: GOPROXY list is not the empty string, but contains no entries
vendors/openai/openai.go:11:2: GOPROXY list is not the empty string, but contains no entries
vendors/gemini/gemini.go:10:2: GOPROXY list is not the empty string, but contains no entries
vendors/gemini/gemini.go:11:2: GOPROXY list is not the empty string, but contains no entries
vendors/gemini/gemini.go:12:2: GOPROXY list is not the empty string, but contains no entries
vendors/ollama/ollama.go:13:2: GOPROXY list is not the empty string, but contains no entries
youtube/youtube.go:8:2: GOPROXY list is not the empty string, but contains no entries
youtube/youtube.go:11:2: GOPROXY list is not the empty string, but contains no entries
core/patterns_loader.go:13:2: GOPROXY list is not the empty string, but contains no entries
core/patterns_loader.go:14:2: GOPROXY list is not the empty string, but contains no entries
core/patterns_loader.go:15:2: GOPROXY list is not the empty string, but contains no entries
core/patterns_loader.go:16:2: GOPROXY list is not the empty string, but contains no entries
core/patterns_loader.go:17:2: GOPROXY list is not the empty string, but contains no entries
core/fabric.go:16:2: GOPROXY list is not the empty string, but contains no entries
cli/flags.go:11:2: GOPROXY list is not the empty string, but contains no entries
```

### Relevant screenshots (optional)

![Screenshot 2024-09-02 at 4 28 34 p m](https://github.com/user-attachments/assets/c81c852d-29e7-4500-be6b-d1f35974a055)

**Comment by ingorichter** [comment]
I'm seeing the same issue. I was able to resolve the `GOSUMDB` error by `export GOSUMDB="sum.golang.org"` but that caused a bunch of warnings

**Comment by bamcop** [comment]
Please execute the go env command in the command line, then paste the output here

**Comment by maibarra** [comment]
Thanks @bamcop , here's the output:

```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/myUser/Library/Caches/go-build'
GOENV='/Users/myUser/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/myUser/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/myUser/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/myUser/.go'
GOSUMDB=''
GOTMPDIR=''
GOTOOLCHAIN=''
GOTOOLDIR='/Users/myUser/.go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/myUser/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/myUser/git/fabric/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/x2/j8d4xkz14nv7p74fmvr8vf0w0000gn/T/go-build2307916941=/tmp/go-build -gno-record-gcc-switches -fno-common'
```
Suggestions are welcome. Thank you!

**Comment by bamcop** [comment]
@maibarra  execute this in the command line
`go env -w GOSUMDB='sum.golang.org'`

**Comment by eugeis** [comment]
Please try again, I can' t reproduce, here my output:

`I can't reproduce it, please try again.

Here my output:

`❯ go install github.com/danielmiessler/fabric@latest
go: downloading github.com/danielmiessler/fabric v1.4.21

~ via 🐹 v1.23.1 took 14s
❯ fabric
no session, pattern or user messages provided

~ via 🐹 v1.23.1
❯ fabric -h
Usage:
  fabric [OPTIONS]

Application Options:
  -p, --pattern=                    Choose a pattern
  -v, --variable=                   Values for pattern variables, e.g. -v=$name:John -v=$age:30
  -C, --context=                    Choose a context
      --session=                    Choose a session
  -S, --setup                       Run setup
      --setup-skip-update-patterns  Skip update patterns at setup
  -t, --temperature=                Set temperature (default: 0.7)
  -T, --topp=                       Set top P (default: 0.9)
  -s, --stream                      Stream
  -P, --presencepenalty=            Set presence penalty (default: 0.0)
  -r, --raw                         Use the defaults of the model without sending chat options (like temperature etc.) and use the user role
                                    instead of the system role for patterns.
  -F, --frequencypenalty=           Set frequency penalty (default: 0.0)
  -l, --listpatterns                List all patterns
  -L, --listmodels                  List all available models
  -x, --listcontexts                List all contexts
  -X, --listsessions                List all sessions
  -U, --updatepatterns              Update patterns
  -c, --copy                        Copy to clipboard
  -m, --model=                      Choose model
  -o, --output=                     Output to file
  -n, --latest=                     Number of latest patterns to list (default: 0)
  -d, --changeDefaultModel          Change default pattern
  -y, --youtube=                    YouTube video url to grab transcript, comments from it and send to chat
      --transcript                  Grab transcript from YouTube video and send to chat
      --comments                    Grab comments from YouTube video and send to chat
      --dry-run                     Show what would be sent to the model without actually sending it
  -u, --scrape_url=                 Scrape website URL to markdown using Jina AI
  -q, --scrape_question=            Search question using Jina AI

Help Options:
  -h, --help                        Show this help message``

**Comment by maibarra** [comment]
Here's my output after running `go install github.com/danielmiessler/fabric@latest`

```
../../go/pkg/mod/github.com/samber/lo@v1.47.0/internal/constraints/ordered_go121.go:6:2: package cmp is not in std (/Users/marcoi/.go/src/cmp)
../../go/pkg/mod/github.com/samber/lo@v1.47.0/internal/rand/ordered_go122.go:5:8: package math/rand/v2 is not in std (/Users/marcoi/.go/src/math/rand/v2)
../../go/pkg/mod/github.com/liushuangls/go-anthropic/v2@v2.8.0/message_stream.go:11:2: package slices is not in std (/Users/marcoi/.go/src/slices)
../../go/pkg/mod/github.com/danielmiessler/fabric@v1.4.55/vendors/openai/openai.go:8:2: package log/slog is not in std (/Users/marcoi/.go/src/log/slog)
../../go/pkg/mod/google.golang.org/grpc@v1.66.2/experimental/stats/metricregistry.go:22:2: package maps is not in std (/Users/marcoi/.go/src/maps)
../../go/pkg/mod/github.com/googleapis/gax-go/v2@v2.13.0/iterator/iterator.go:37:2: package iter is not in std (/Users/marcoi/.go/src/iter)
```

What can I do?
