### ISSUE TITLE
[Bug]: Cannot change default model, always gpt-4o

### ISSUE THREAD

**Issue by eliranwong** [danielmiessler/fabric#919]
### What happened?

I tried to change default model with `fabric -d` many times.  I tried entered corresponding numbers to models, like `gemini-1.5-pro`, `mistral-large:123b`, etc.  However, every time I run fabric without specifying `-m` parameter, I got errors:

```
googleapi: Error 404: models/gpt-4o is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
googleapi: Error 404: models/gpt-4o is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
```

**Comment by eugeis** [comment]
I can't reproduce. Please test it with current release and reopen the issue if still occurs.
