### ISSUE TITLE
PROBLEM trying to install the "yt tool". 

### ISSUE THREAD

**Issue by SME6** [danielmiessler/fabric#921]
### What is your question?

When putting "go install github.com/danielmiessler/yt@latest" in terminal I received the message that "go cannot find GOROOT directory: /usr/local/go." Any idea on how I could fix this issue? 
I would really appreciate if you could give any help to pull this off. Many thanks! I tried this, this, and that.

**Comment by Geelhem** [comment]
did you install go ? im having some issue too but not that one.

**Comment by SME6** [comment]
Yes I did. Everything else worked perfect, but it seems that this specific file wasn't installed because go cannot find it in my directory

**Comment by charlie-romeo** [comment]
I had the same issue, I hadn't set up the Environmental Variables yet.  I got a little ahead of myself.  
check with `echo $GOROOT` it should be /usr/local/go on linux/mac.  not sure about windows

good luck

**Comment by yousecjoe** [comment]
Same issue here. I had to use sudo to get it to work. That should not be the case.

**Comment by yousecjoe** [comment]
After installation, it will still not work if you follow the documentation. 
The docs need improvements. 
As others said, you must not use `--transcript`, and your URL must be in double quotes. That got it to work for me.

**Comment by eugeis** [comment]
Meanwhile yt is integrated to fabric directly, so you could use fabric -y... -p....

Here help page:

`I can't reproduce it, please try again.

Here my output:

`❯ go install github.com/danielmiessler/fabric@latest
go: downloading github.com/danielmiessler/fabric v1.4.21

~ via 🐹 v1.23.1 took 14s
❯ fabric
no session, pattern or user messages provided

~ via 🐹 v1.23.1
❯ fabric -h
Usage:
  fabric [OPTIONS]

Application Options:
  -p, --pattern=                    Choose a pattern
  -v, --variable=                   Values for pattern variables, e.g. -v=$name:John -v=$age:30
  -C, --context=                    Choose a context
      --session=                    Choose a session
  -S, --setup                       Run setup
      --setup-skip-update-patterns  Skip update patterns at setup
  -t, --temperature=                Set temperature (default: 0.7)
  -T, --topp=                       Set top P (default: 0.9)
  -s, --stream                      Stream
  -P, --presencepenalty=            Set presence penalty (default: 0.0)
  -r, --raw                         Use the defaults of the model without sending chat options (like temperature etc.) and use the user role
                                    instead of the system role for patterns.
  -F, --frequencypenalty=           Set frequency penalty (default: 0.0)
  -l, --listpatterns                List all patterns
  -L, --listmodels                  List all available models
  -x, --listcontexts                List all contexts
  -X, --listsessions                List all sessions
  -U, --updatepatterns              Update patterns
  -c, --copy                        Copy to clipboard
  -m, --model=                      Choose model
  -o, --output=                     Output to file
  -n, --latest=                     Number of latest patterns to list (default: 0)
  -d, --changeDefaultModel          Change default pattern
  -y, --youtube=                    YouTube video url to grab transcript, comments from it and send to chat
      --transcript                  Grab transcript from YouTube video and send to chat
      --comments                    Grab comments from YouTube video and send to chat
      --dry-run                     Show what would be sent to the model without actually sending it
  -u, --scrape_url=                 Scrape website URL to markdown using Jina AI
  -q, --scrape_question=            Search question using Jina AI

Help Options:
  -h, --help                        Show this help message``

**Comment by yousecjoe** [comment]
> Meanwhile yt is integrated to fabric directly, so you could use fabric -y... -p....
> 

I realized the YT integration was there very recently. I have been testing the direct integration for the last few nights, and it's working great! I've got some examples that could be used to improve the documentation.

**Comment by eugeis** [comment]
If you like,  please update READMe.md with the decsription and some examples.
