### ISSUE TITLE
[Bug]: You tube Transcript is broken

### ISSUE THREAD

**Issue by Geelhem** [danielmiessler/fabric#923]
### What happened?

I was followed last install for go version and yt, but when I type this :  yt --transcript https://youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT | fabric --stream --pattern extract_wisdom

### Version check

- [X] Yes I was.

### Relevant log output

```shell
get this : 
zsh: no matches found: https://youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT
**SUMMARY**
No summary extracted as there is no input provided.

**IDEAS**
No ideas extracted as there is no input provided.

**INSIGHTS**
No insights extracted as there is no input provided.

**QUOTES**
No quotes extracted as there is no input provided.

**HABITS**
No habits extracted as there is no input provided.

**FACTS**
No facts extracted as there is no input provided.

**REFERENCES**
No references extracted as there is no input provided.

**ONE-SENTENCE TAKEAWAY**
No takeaway extracted as there is no input provided.

**RECOMMENDATIONS**
No recommendations extracted as there is no input provided.%    

Sometime it works but still says video not found but summarises a random video I don't know about.
```

### Relevant screenshots (optional)

![image](https://github.com/user-attachments/assets/ffda6629-9eb4-4c6c-9a74-6b0e28e2e741)

**Comment by carvierdotdev** [comment]
> ### What happened?
> 
> I was followed last install for go version and yt, but when I type this : yt --transcript [youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT](https://youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT) | fabric --stream --pattern extract_wisdom

Did you use this command instead:

```zsh
yt https://www.youtube.com/watch?v=lQVcbY52_gY | fabric --pattern extract_wisdom
```

It's from [Helper Apps](https://github.com/danielmiessler/fabric?tab=readme-ov-file#helper-apps) in the README?

**Comment by carvierdotdev** [comment]
> ### What happened?
> 
> I was followed last install for go version and yt, but when I type this : yt --transcript [youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT](https://youtu.be/YWdDk7jjCn0?si=XB35Y_72bPbU0WGT) | fabric --stream --pattern extract_wisdom
Also, I saw your issue with the GUI. I think there are a couple of options in development for the Go version, which is why when you run fabric -h, those versions aren't displayed

**Comment by yousecjoe** [comment]
The docs need improvements. 
As others said, you must not use `--transcript` and your URL must be in double quotes. That got it to work for me.
