### ISSUE TITLE
[Question]: I am not sure how to set up fabric

### ISSUE THREAD

**Issue by AzidanoValkran** [danielmiessler/fabric#927]
### What is your question?

After reading the documentation, I am still not clear how to get my settings working.

I ran this command in my Terminal (I am using MacOS) `go install github.com/danielmiessler/fabric@latest`

Then after this installed I typed `fabric --setup`

And it says `zsh: command not found: fabric`

What am I doing wrong?

**Comment by SME6** [comment]
That means you haven't installed Go. 

Check this video for a step by step installation.

https://youtu.be/2fj2R6vK6O0?si=DHTmfg4LFlbIkLgX

**Comment by charlie-romeo** [comment]
A couple of thing Azidano.  Many time those `command not found:` errors are $PATH issues or like SME6 said, not installed.

☑️☑️ two quick checks:  
☑️from zsh type `which go` and you should get a path to the go binary  or,
☑️ `set` or `echo $PATH` and make sure  the PATH= variable has`User/<usrname>/go/bin, usr/loca/go/bin` in the PATH. If they are not, SME6 is right that GO needs to be installed. _Use Home Brew on a Mac, if your new to cli, it's just easier. `brew install go`._ 
you can try to source the zsh config or reload terminal.  `source ~/.zshrc` is how you apply the .zshrc config into your current terminal.  

After these checks, set the environmental variables, run `fabric -U` to load the patterns and off you go.

Good luck.  let us know what the resolution is

**Comment by fonteijne** [comment]
I faced the same issue and got it fixed somewhat like @charlie-romeo is writing. Make sure you validate the checks @charlie-romeo wrote first!

For me it all came down to adding `~/go/bin` to my fish `PATH`.
This is the command I used: `set -Ux PATH $PATH $HOME/go/bin`
After a terminal restart, I was able to use `fabric`.

NOTE: 
If `set -UX PATH.......` returns: `set: successfully set universal 'PATH'; but a global by that name shadows it`.
Use the following command: `set -g PATH $PATH $HOME/go/bin`.
To make this persistent, add this command to fish.config (`nano ~/.config/fish/config.fish`).

**Comment by eugeis** [comment]
Yes, it is just a PATH problem.

There is already improved README.md for Mac OS, how to set Go to PATH.

`# Golang environment variables
export GOROOT=$(brew --prefix go)/libexec
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH`
