### ISSUE TITLE
`Feature` Publish client to PyPi to make it easier to use

### ISSUE THREAD

**Issue by GunniBusch** [danielmiessler/fabric#93]
Hi, would it be possible, to publish it on PyPi for example, would be user friendlier.
I could help do it, but earliest next month.

but resources to help: 
https://www.freecodecamp.org/news/how-to-build-and-publish-python-packages-with-poetry/

**Comment by Andortk** [comment]
That would be an awesome idea. I had some trouble having it run on windows actually, so if it's installable via PyPi, I think that would be awesome.
Still kind of not able to get it to run haha! But I'm using some of the patterns. Awesome stuff!

Could really gain traction if it was a bit easier to use. The idea is brilliant!

**Comment by Millz98** [comment]
> That would be an awesome idea. I had some trouble having it run on windows actually, so if it's installable via PyPi, I think that would be awesome. Still kind of not able to get it to run haha! But I'm using some of the patterns. Awesome stuff!
> 
> Could really gain traction if it was a bit easier to use. The idea is brilliant!

Agreed, I still don't fully understand how to install/use it

**Comment by danielmiessler** [comment]
Yes, we're looking to do that, as well as pip and homebrew. Thank you!
