### ISSUE TITLE
[Question]:  how to use analyze_paper?

### ISSUE THREAD

**Issue by abuzai010** [danielmiessler/fabric#930]
### how to use analyze_paper?

How do i use the analyze_paper

I've tried the --context command and add a txt file there but i get this error

C:\Users\abuba>fabric --context C:\Users\abuba\.config\fabric\contexts\Here is the PDF content converted t.txt
could not find context C:\Users\abuba\.config\fabric\contexts\Here: could not load C:\Users\abuba\.config\fabric\contexts\Here: open C:\Users\abuba\.config\fabric\contexts\C:\Users\abuba\.config\fabric\contexts\Here: The filename, directory name, or volume label syntax is incorrect.

bit of a newbie sorry if this has been asked before

**Comment by charlie-romeo** [comment]
so far, i haven't used `--context` for any workflows.  the basics for me are `yt`, `echo`, and `cat` _i think TYPE is the command is windows_ pipe text to fabric. 

An example would be: `type C:\path\to\text.txt | fabric -p analyze_paper`

good luck.

**Comment by abuzai010** [comment]
@charlie-romeo thanks for that will be sure to use the `type ` function

also figured out using `get-clipboard` as an alternative to `pbpaste` shown in the readme section, maybe that should be mentioned there
