### ISSUE TITLE
[Bug]: can not install fabric

### ISSUE THREAD

**Issue by nick11235** [danielmiessler/fabric#935]
### What happened?

when trying to install i get an error message
go install github.com/danielmiessler/fabric@latest
this is the output

### Version check

- [X] Yes I was.

### Relevant log output

```shell
go: downloading github.com/danielmiessler/fabric v1.4.3
go: github.com/danielmiessler/fabric@latest (in github.com/danielmiessler/fabric@v1.4.3): go.mod:3: invalid go version '1.22.5': must match format 1.23
go.mod:5: unknown directive: toolchain
```

**Comment by alexxmugg** [comment]
Your go.mod file in the Fabric repository specifies a Go version that doesn't match, looking for version 1.23, but found 1.22.5.

Check your Go version

**Comment by starfish456** [comment]
I ran into the same issue:

`go install github.com/danielmiessler/fabric@latest
go: github.com/danielmiessler/fabric@latest (in github.com/danielmiessler/fabric@v1.4.3): go.mod:3: invalid go version '1.22.5': must match format 1.23
go.mod:5: unknown directive: toolchain`

Steps to resolve: 

```
➜  go version
go version go1.20.2 darwin/arm64
```
```
➜  brew install go
==> Auto-updating Homebrew...
```
```
➜  go version
go version go1.23.1 darwin/arm64
```

Then it worked

**Comment by eugeis** [comment]
I can't reproduce it, please try again.

Here my output:

`❯ go install github.com/danielmiessler/fabric@latest
go: downloading github.com/danielmiessler/fabric v1.4.21

~ via 🐹 v1.23.1 took 14s
❯ fabric
no session, pattern or user messages provided

~ via 🐹 v1.23.1
❯ fabric -h
Usage:
  fabric [OPTIONS]

Application Options:
  -p, --pattern=                    Choose a pattern
  -v, --variable=                   Values for pattern variables, e.g. -v=$name:John -v=$age:30
  -C, --context=                    Choose a context
      --session=                    Choose a session
  -S, --setup                       Run setup
      --setup-skip-update-patterns  Skip update patterns at setup
  -t, --temperature=                Set temperature (default: 0.7)
  -T, --topp=                       Set top P (default: 0.9)
  -s, --stream                      Stream
  -P, --presencepenalty=            Set presence penalty (default: 0.0)
  -r, --raw                         Use the defaults of the model without sending chat options (like temperature etc.) and use the user role
                                    instead of the system role for patterns.
  -F, --frequencypenalty=           Set frequency penalty (default: 0.0)
  -l, --listpatterns                List all patterns
  -L, --listmodels                  List all available models
  -x, --listcontexts                List all contexts
  -X, --listsessions                List all sessions
  -U, --updatepatterns              Update patterns
  -c, --copy                        Copy to clipboard
  -m, --model=                      Choose model
  -o, --output=                     Output to file
  -n, --latest=                     Number of latest patterns to list (default: 0)
  -d, --changeDefaultModel          Change default pattern
  -y, --youtube=                    YouTube video url to grab transcript, comments from it and send to chat
      --transcript                  Grab transcript from YouTube video and send to chat
      --comments                    Grab comments from YouTube video and send to chat
      --dry-run                     Show what would be sent to the model without actually sending it
  -u, --scrape_url=                 Scrape website URL to markdown using Jina AI
  -q, --scrape_question=            Search question using Jina AI

Help Options:
  -h, --help                        Show this help message`

**Comment by draeician** [comment]
I'm running PopOS and I get the same error:
draeician@nomnom:~$ go version
go version go1.18.1 linux/amd64
draeician@nomnom:~$ go install github.com/danielmiessler/fabric@latest
go: github.com/danielmiessler/fabric@latest (in github.com/danielmiessler/fabric@v1.4.22): go.mod:3: invalid go version '1.22.5': must match format 1.23

This is the latest version that popos has in the repository though.

**Comment by draeician** [comment]
Resolved my issue, but had to install a version of go that's now outside the supported popos ecosystem.

**Comment by leerogers** [comment]
Not sure how to correct.  Seems like a .x version issue?  I tried modifying all references to 1.23.4 in every file I could find.  I am new to go.

lee@Zenbook:~/go/pkg/mod/cache/download/github.com/danielmiessler/fabric/@v$ go install github.com/danielmiessler/fabric@latest
go install github.com/danielmiessler/fabric@latest: github.com/danielmiessler/fabric@v1.4.159: go.mod:3: invalid go version '1.23.4': must match format 1.23

Thanks in advance for any help you can give.
