### ISSUE TITLE
[Question]: Where are the fabric folders?

### ISSUE THREAD

**Issue by brauliodiasribeiro** [danielmiessler/fabric#955]
### What is your question?

I've installed Fabric on Ubuntu Server but I can't find the folders. Everything is empty.
![Screenshot_1](https://github.com/user-attachments/assets/735f0d93-2467-45bf-90b8-5b69cd79bcce)

Apparently I don't have permission to install Fabric in this location.
Any suggestions on how to solve this?
![Screenshot_2](https://github.com/user-attachments/assets/936fb34b-a225-455c-8e13-11fe73dfb847)

**Comment by charlie-romeo** [comment]
I think you should be able to `chown` the `.env` file to your user and have better luck.  something along the lines of:
`$ sudo chown bdrtec:bdrtec .env` 
My files are in the same location, however where `.env` is owned by `root` on your system, my user owns them.  I'm on a mac.  Did you run the install/setup with `sudo`?

**Comment by brauliodiasribeiro** [comment]
> I think you should be able to `chown` the `.env` file to your user and have better luck. something along the lines of: `$ sudo chown bdrtec:bdrtec .env` My files are in the same location, however where `.env` is owned by `root` on your system, my user owns them. I'm on a mac. Did you run the install/setup with `sudo`?

I made it.
I'm still learning a few things about Linux.
Thank you very much for your help.
Now I'm going to try installing the fabric in a container.
