### ISSUE TITLE
[Bug]: Error installing the `to_pdf` helper app

### ISSUE THREAD

**Issue by DaitiDay** [danielmiessler/fabric#956]
### What happened?

When I try to install the `to_pdf` helper app using the command in the documentation, i.e. `go install github.com/danielmiessler/fabric/to_pdf/to_pdf@latest`, I get the following error.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
go: github.com/danielmiessler/fabric/to_pdf/to_pdf@latest: module github.com/danielmiessler/fabric@latest found (v1.4.12), but does not contain package github.com/danielmiessler/fabric/to_pdf/to_pdf
```

**Comment by bamit99** [comment]
Same!![Screenshot_2024-09-13-20-45-31-87_61c78dc80ee02b53007c815fefe993e3.jpg](https://github.com/user-attachments/assets/dbc31742-dabe-4bf5-b39f-a5c8074023b0)

**Comment by akashkankariya** [comment]
There is small error in path
Try this -> go install github.com/danielmiessler/fabric/to_pdf@latest

**Comment by DaitiDay** [comment]
@akashkankariya thank you, that was the problem 😄
