### ISSUE TITLE
Can't install yt helper app on silicon MBP after migrating from python version to Go version

### ISSUE THREAD

**Issue by coachdamon** [danielmiessler/fabric#960]
I migrated from the python version to use go. Installed go with the package manager on silicon-based MBP. Added these into .zshrc (export GOROOT=/opt/homebrew/bin/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH:) but the go directory doesn't exist under /opt/homebrew/bin. 

This prevents me from installing yt, of course, but also makes me wonder if there's something else not configured correctly. Fabric seems to respond ok, but just checking. Any thoughts?

**Comment by coachdamon** [comment]
Found the issue. Needed to change teh GOROOT variable to be "/usr/local/go"

**Comment by yousecjoe** [comment]
Interestingly, the homebrew package manager is used in the environment variable for applied silicon but not for Intel when in fact, I use homebrew on Intel. I'm also running into the GOROOT error a lot of other people are having. I must run go as sudo. I don't recall that being a requirement previously, but I could be mistaken. Go also says you should not run Go apps as root, so there is that.

**Comment by eugeis** [comment]
Meanwhile yt is integrated to fabric itself,  just try tonuse, fabric - y... -p....

**Comment by BryanKerrEdTech** [comment]
> Meanwhile yt is integrated to fabric itself, just try to use, fabric - y... -p....

I think there's a mistake in the new YouTube example. Shouldn't it be:

`fabric -y "https://youtube.com/watch?v=uXs-zPc63kM" --stream | fabric -p extract_wisdom`

**Comment by eugeis** [comment]
No, it shall work with

fabric -y "https://youtube.com/watch?v=uXs-zPc63kM" --stream -p extract_wisdom

The transcript is printed out at first and then it will be passed to the pattern

Is it not working like this?

**Comment by djclarkson** [comment]
Your version ommits the pipe | which is in the docs. But either way for me since migration from yt to fabric -y I get this error "I apologize, but I don't have enough context from the input provided to generate a full summary and analysis as requested. The input appears to be just a greeting "Hi" rather than a full transcript or article about nicotine......"

**Comment by eugeis** [comment]
I can't reproduce it.
I think the max context size of your provider/model is to small.

I am getting this by using of Ollama, llama3.2:latest

❯ fabric -y "https://youtube.com/watch?v=uXs-zPc63kM" --stream -p extract_wisdom -m llama3.2:latest
Here is a summary of the episode:

The host discusses the biology and psychological effects of nicotine, highlighting its immense power as one of the most commonly ingested substances on Earth. He emphasizes that nicotine itself does not cause cancer or other negative health effects, but rather the delivery devices used to consume it do.

He also notes that nicotine is a highly addictive substance, with a 95% failure rate for those who try to quit without proper tools and support. However, he expresses confidence in the ability of individuals to quit smoking or vaping using evidence-based protocols and tools.

The host reviews some of the biological mechanisms underlying nicotine addiction, including its effects on dopamine and acetylcholine levels in the brain. He also mentions alternative approaches to increasing these neurotransmitters for cognitive enhancement or physical performance.

Throughout the episode, he encourages listeners to support the podcast by subscribing to the YouTube channel, leaving a review on Apple and Spotify, and checking out sponsors mentioned at the beginning of the episode.

The host also invites listeners to engage with him and the podcast community through comments, social media, and the Huberman Lab Neural Network Newsletter, which provides summaries of previous podcasts and tools for enhancing sleep, hormone function, focus, and other areas.

**Comment by BryanKerrEdTech** [comment]
> Your version ommits the pipe | which is in the docs. But either way for me since migration from yt to fabric -y I get this error "I apologize, but I don't have enough context from the input provided to generate a full summary and analysis as requested. The input appears to be just a greeting "Hi" rather than a full transcript or article about nicotine......"

I've getting the same with a simple
`pbpaste | fabric -p extract_wisdom  > fout.txt`

**Comment by Stehos** [comment]
Hi everyone, I came back to Fabric after a few months so I installed it via brew on my macbook but can not use it like before e.g. fabric -y “https://youtube.com/watch?v=uXs-zPc63kM” –stream –pattern extract_wisdom 

it says: YouTube is not configured, please run the setup procedure 

does it mean that I need youtube api key?

how it was working before when the API key was not needed? at least I did not find any youtube api keys

**Comment by ksylvan** [comment]
@Stehos Answered here: https://github.com/danielmiessler/fabric/issues/821#issuecomment-2938429493
