### ISSUE TITLE
[Bug]: User error more then bug

### ISSUE THREAD

**Issue by icemarr** [danielmiessler/fabric#964]
### What happened?

Trying to install fabric on a Macbook M1. I am new to Mac and python so Im sure its a setting or config. Ive been trying to follow NetworkChucks youtube on installing but get stuck at "pipx intall ." while in the fabric Directory. I have installed Homebrew and accepted all defaults. This is after resetting Macbook back to factory so all Python should be back to factory as well except for what Homebrew does. When typing the install command I get the following error:

icemarr@Stanleys-MacBook-Air fabric % pipx install .
ERROR: Directory '/Users/icemarr/fabric' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Cannot determine package name from spec '/Users/icemarr/fabric'. Check package spec for errors.
icemarr@Stanleys-MacBook-Air fabric % 

Any help on how to set the install command to go look at homebrew is greatly appreciated. 

### Version check

- [X] Yes I was.

**Comment by charlie-romeo** [comment]
Sorry, no experience with PIPX.  

I'm on a M1 as well but used the current Fabric 1.4.x releases in GO.  Fabric has been rewritten in GO and the readme reflects that.  I think NetworkChuck's video was based on the python/pip version from 6+ months ago.

PIPX basically automates the setup of a `python env` so the app and dependencies don't clutter your file structure or overwrite the osX python install.  I haven't installed anything with pipx, sorry.

If you were able to get home-brew running you will be able to get GO installed and then Fabric after that.  From there, you can get back into the flow with NtChuck.

Good luck.

**Comment by eugeis** [comment]
You could also use binary from Release page. Downloafmd it, rename to fabric and put to your PATH.
