### ISSUE TITLE
[Feature request]: Support LiteLLM

### ISSUE THREAD

**Issue by anaynayak** [danielmiessler/fabric#969]
### What do you need?

Thanks for building fabric! I've been trying it out with ollama and wanted to take this further by using AWS bedrock. I've used LiteLLM elsewhere and it provides good support for transparently handling different LLM vendors. I was wondering if there were plans to introduce LiteLLM support in fabric? 

Existing work (on the earlier python implementation) https://github.com/danielmiessler/fabric/pull/110

I tried to use the OpenAI vendor by explicitly setting the base url to http://localhost:4000 and this seemed to work since it listed the models from litellm. However invoking any fabric patterns fail since it tries to check the `OPENAI_API_KEY` 

config snippet which leads to api key error
```
DEFAULT_VENDOR=OpenAI
DEFAULT_MODEL=llama3.1
PATTERNS_LOADER_GIT_REPO_URL=https://github.com/danielmiessler/fabric.git
PATTERNS_LOADER_GIT_REPO_PATTERNS_FOLDER=patterns
OPENAI_API_KEY=aa
OPENAI_API_BASE_URL=http://localhost:4000/
```

Reported error:
```
❯ echo "add two numbers"| fabric --pattern create_command -m llama3.1
OpenAI error, status code: 401, message: Incorrect API key provided: aa. You can find your API key at https://platform.openai.com/account/api-keys.
could not find vendor.
```

Changes that got it working for me (happy to raise a PR):
https://github.com/danielmiessler/fabric/compare/main...anaynayak:fabric:main

**Comment by eugeis** [comment]
Hi, there was a bug with custom OPENAI_API_BASE_URL, it is already fixed. Please retry it with the current release and close the issue, if it is working.
