### ISSUE TITLE
[Bug]: Cannot install fabric

### ISSUE THREAD

**Issue by gahoccode** [danielmiessler/fabric#977]
### What happened?

Hi after this step F:\fabric>pipx install I got
ERROR: Directory 'F:\\fabric' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Cannot determine package name from spec 'F:\\fabric'. Check package spec for errors. 
Could you please tell me what am I missing here? 

### Version check

- [X] Yes I was.

**Comment by eugeis** [comment]
Please check the installation steps in readme.
Fabric is reimplemented in Go. The binaries are available under Releases or it is possible to install from sources.
