### ISSUE TITLE
[Bug]: yt command doesn't work on Linux (via SSH). Need Help!

### ISSUE THREAD

**Issue by StefanCasenco** [danielmiessler/fabric#978]
### What happened?

yt command works on Windows perfectly, but doesn't work on Linux (VPS)

I wanted to run fabric on my iPhone and run the "Run over SSH" (Linux) shortcut. It worked for a while, but it started outputting meaningful content every other time (1/2) and then stopped working, suggesting it didn't get the transcript. 

I thought I tested the YouTube API too much and got a temporary ban, but I've read that some people also had problems with "yt" command. Nothing works and I need help.

![image_453](https://github.com/user-attachments/assets/dd0e4f34-245e-4aba-b98c-602ac320ac11)
![image_454](https://github.com/user-attachments/assets/3c4de563-de39-4472-b7ed-e316823f3c81)
![image_455](https://github.com/user-attachments/assets/4ceea386-b7a4-443c-ab78-f6b1d3d1c46d)
![image_445](https://github.com/user-attachments/assets/65ccfa72-c9ef-429b-98f6-150a00a5e1a2)
![image_444](https://github.com/user-attachments/assets/0fc41638-2cd3-447d-b033-e96fb2cf0cec)
![image_443](https://github.com/user-attachments/assets/8513e0b8-1711-4691-a2a4-5685d42238d6)

### Version check

- [X] Yes I was.

### Relevant log output

```shell
root@localhost:~# yt --transcript https://www.youtube.com/watch?v=BT-t4-sxykA | fabric -s -p extract_wisdom
SUMMARY:
No content is available for summarization or extraction of insights and ideas.

IDEAS:
- No ideas can be extracted as there is no content provided.

INSIGHTS:
- No insights can be derived from the absence of content.

QUOTES:
- No quotes are available due to lack of content.

HABITS:
- No habits can be identified without any content to analyze.

FACTS:
- No facts can be provided as there is no information available.

REFERENCES:
- No references can be extracted since there is no content to refer to.

ONE-SENTENCE TAKEAWAY:
No takeaway can be provided due to lack of content.

RECOMMENDATIONS:
- No recommendations can be drawn from the absence of content.

--------------------------------------------------------------------------------------------------------
OR
--------------------------------------------------------------------------------------------------------
root@localhost:~# yt --transcript https://www.youtube.com/watch?v=BT-t4-sxykA | fabric -s -p summarize
# ONE SENTENCE SUMMARY:
The content is currently unavailable, as no transcript has been provided for summarization.

# MAIN POINTS:
1. No transcript has been found for analysis or summarization.
2. Content cannot be summarized without available data.
3. Information is limited due to the absence of text.
4. The request for a summary is unfulfilled.
5. Context or details about the content are missing.
6. No insights can be derived without a transcript.
7. Future requests should include accessible text for summarization.
8. The lack of information hampers effective summarization.
9. Clarity on the content's subject matter is absent.
10. Summarization relies on the availability of source material.

# TAKEAWAYS:
1. Always provide a transcript for accurate summarization.
2. Context is crucial for effective content analysis.
3. Summarization cannot occur without available information.
4. Clear communication of content type is important.
5. Ensure accessibility of data for future requests.
```

### Relevant screenshots (optional)

![image_447](https://github.com/user-attachments/assets/54c522ea-9570-4442-b45e-3cd35420f35c)

**Comment by StefanCasenco** [comment]
![image](https://github.com/user-attachments/assets/828f0113-f321-4095-bd42-63ccaaba944b)

using the same api, it works even on ubuntu locally, but doesn't work over ssh, who can help?

**Comment by eugeis** [comment]
Meanwhile yt is integrated to fabric directly,  try to use fabric -y... -p..m instead.

**Comment by bamit99** [comment]
Yes, instead of using YT command, use Fabric -y command with URL to pull youtube transcript.

**Comment by StefanCasenco** [comment]
@bamit99 how would the command with -y look like?

Is it "fabric -y {YouTube URL} -p extract wisdom"

Don't get it

**Comment by StefanCasenco** [comment]
@eugeis  how would the command with -y look like?

Is it "fabric -y {YouTube URL} -p extract wisdom"

Don't get it

**Comment by eugeis** [comment]
e.g.

fabric -y "https://www.youtube.com/watch?v=2fj2R6vK6O0" -sp extract_wisdom

**Comment by StefanCasenco** [comment]
@eugeis 
I works on windows, but doesn't work over SSH
SEE THE SECOND SCREENSHOT

it says "transcript not available", but found on windows (first screenshot)
I use the same OpenAI and YouTube APIs for both (windows and for linux - over SSH)

Please help

![image_598](https://github.com/user-attachments/assets/6d2f69dd-3114-4604-887e-7b86cc619e31)
![image_599](https://github.com/user-attachments/assets/44799a1f-7a49-4ff2-80e9-3224e5c70cbe)
