### ISSUE TITLE
[Feature request]: allow ANTHROPIC_BASE_URL and OPENAI_BASE_URL

### ISSUE THREAD

**Issue by draeician** [danielmiessler/fabric#979]
### What do you need?

This worked fine in the python version, but since moving to go it doesn't work.

**Comment by eugeis** [comment]
OPENAI_BASE_URL is already supported, just run fabric --setup

> Enter your OpenAI API BASE URL (leave empty for 'https://api.openai.com/v1' or type 'reset' to remove the value):

ANTHROPIC_BASE_URL supporet implemented in https://github.com/danielmiessler/fabric/releases/tag/v1.4.23
