### ISSUE TITLE
Error code: 404 - 'The model `gpt-4-turbo-preview` 

### ISSUE THREAD

**Issue by flexorflex** [danielmiessler/fabric#98]
Hi everyone, I follow the instructions, but I get this error msg:

Error: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Can you help me here?

**Comment by chrissonntag** [comment]
Hey there 😀  This means that restrictions of the API Key you have created, do not involve using that Model. You can call fabric with option --listmodels to see what models are available with your Key

**Comment by flexorflex** [comment]
Oh, my bad. I was surprised to find out that ChatGPT and using the API are two different products. Thanks for you support

**Comment by chrissonntag** [comment]
It gets worse. If you were to use your API Key for GPT-3.5, it first seems to work. But in fact for you do not have a quota for it, it gets banned for a couple hours or so. So you cannot use Chat-GPT in the period 🙃

**Comment by flexorflex** [comment]
After depositing to the API account, fabric works flawlessly

**Comment by dpedrinha** [comment]
> After depositing to the API account, fabric works flawlessly

After what?
I'm trying to find how to enable gpt 4 turbo to my API key but can't find how.

**Comment by jamief00** [comment]
I'm assuming you are using the basic plan, so you might not have access to the model. You can use the --changeDefaultModel to a different option.

**Comment by dpedrinha** [comment]
Forget I asked. Just found out that the turbo version is already an Old model according to their website.

[https://openai.com/api/pricing/]https://openai.com/api/pricing/
