### ISSUE TITLE
[Bug]: --changeDefaultModel forces menu of list

### ISSUE THREAD

**Issue by draeician** [danielmiessler/fabric#980]
### What happened?

I entered --changeDefaultModel hermes3:latest, and still get thrown to the menu to make a selection.

fabric --help shows
  --changeDefaultModel CHANGEDEFAULTMODEL
                        Change the default model. For a list of available models, use the --listmodels flag.

The switch is not behaving as described in the --help documentation.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
None required, the system just throws you to the selection menu instead of updating your settings.
```

**Comment by eugeis** [comment]
Thanks, we updated the help docu.
