### ISSUE TITLE
[Bug]: yt command doesn't work on Linux (via SSH). Need Help! (2)

### ISSUE THREAD

**Issue by StefanCasenco** [danielmiessler/fabric#983]
### What happened?

![image](https://github.com/user-attachments/assets/ff132cb5-6a57-495c-a856-0213b9ca14bb)

@eugeis
It works on windows, but doesn't work over SSH
SEE THE SECOND SCREENSHOT

it says "transcript not available" in SSH terminal (second screenshot), but found the transcript of the same exact video (same URL) on windows (first screenshot)
I use the same OpenAI and YouTube APIs for both (windows and for Linux - over SSH)

Please help

![image_601](https://github.com/user-attachments/assets/84dfd13a-788a-4641-9610-5a36076087a7)
![image_602](https://github.com/user-attachments/assets/97ba9149-086d-4aef-b4b5-0e05cf230ba6)

### Version check

- [X] Yes I was.

**Comment by StefanCasenco** [comment]
@eugeis 
Also tried adding a new YouTube API restricted to the VPS IP Address and only use the YouTube Data API v3 and still doesn't work.
![image_603](https://github.com/user-attachments/assets/b88cc794-66d0-4d22-85cf-c815e865a033)

**Comment by itsdoublearon** [comment]
Would this have something to do with YouTube cracking down on third-party services and adblockers?

**Comment by eugeis** [comment]
I can't reproduce it on my linux server over SSH.

<img width="852" alt="image" src="https://github.com/user-attachments/assets/5ebec570-fd51-4cb5-83f3-b7f386cb44aa">

I could check it on yours, but then I would need ssh access data.

**Comment by itsdoublearon** [comment]
It's intermittent with mine at the moment, but I think YouTube themselves have tweaked some things because (maybe related) Invidious doesn't work anymore for me.
