### ISSUE TITLE
[Bug]: unable to install to_pdf helper

### ISSUE THREAD

**Issue by openworker** [danielmiessler/fabric#985]
### What happened?

Attempting to install the to_pdf helper for latest THIS, when the error noted in the log output  related to the go package being unavailable was received
. I was expecting for the to_pdf installtion  to happen instead.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
go install github.com/danielmiessler/fabric/to_pdf/to_pdf@latest
go: downloading github.com/danielmiessler/fabric v1.4.23
go: github.com/danielmiessler/fabric/to_pdf/to_pdf@latest: module github.com/danielmiessler/fabric@latest found (v1.4.23), but does not contain package github.com/danielmiessler/fabric/to_pdf/to_pdf
```

**Comment by Malaeu** [comment]
same here

**Comment by phsamuel** [comment]
same here :)

**Comment by eugeis** [comment]
Documentation updated

please use:

go install github.com/danielmiessler/fabric/to_pdf@latest
