### ISSUE TITLE
[Question]: windows compatible still?

### ISSUE THREAD

**Issue by aldrichwe** [danielmiessler/fabric#988]
### What is your question?

I sat there about 2 weeks ago with two of my uncles who have 30 years of coding experience and it seemed that there was something that we couldn't get through. Go was installed. Fabric cloned. Everytime we ran "pipx install ." nothing happened. We gave up. advice?

**Comment by xssdoctor** [comment]
Pipx doesn't work. We mitrated to go. Take a look at the installation instructions on the GitHub page

**Comment by aldrichwe** [comment]
xssdoctor, new to coding myself. I understand that you switched, the go roots and paths dont seem to be recognized even though go is installed and the go fabric code worked to download. which code should I be using for windows? It says linux or mac

**Comment by ttodosi** [comment]
just to be clear, for windows, do you still have to run on WSL , and does that mean you install GO through WSL?

**Comment by aldrichwe** [comment]
I also would like to know the question posed by dosi

**Comment by OddDuck11** [comment]
I'm using Fabric native on Windows 11. I followed all the install instructions. First installed Go then Fabric. Ran the Fabric setup, put in my API key for OpenAI and it works great. I'm not planning on running local models, so I skipped Ollama install and config. I use Get-Clipboard in Powershell to pipe to fabric.

**Comment by StephenBrough** [comment]
Running fine on Windows 10. Followed all instructions, everything seems to be working.
