### ISSUE TITLE
Can't find module 'utils' (Windows)[Solution]

### ISSUE THREAD

**Issue by chroakPRO** [danielmiessler/fabric#99]
## Environment
- **Operating System**: Windows
- **Python Version**: [3.11.5]
- **Poetry Version**: [1.7.1]
- **Fabric Version**: [0.1.0]

## Issue Description
When attempting to execute a sequence of commands involving Poetry and Fabric, an error is encountered stating that the module 'utils' cannot be found. This issue arises after initiating a Poetry environment and executing the `fabric` command.

### Steps to Reproduce
1. Run `poetry install` to install dependencies.
2. Activate the virtual environment with `poetry shell`.
3. Execute the `fabric` command.

#### Expected Behavior
The `fabric` command should execute without any issues, with all modules being correctly resolved.

#### Actual Behavior
An error message is displayed: `can't find module 'utils'`. This prevents the `fabric` command from executing as expected.

## Solution
The issue appears to be related to an incorrect import statement within the Fabric library. To resolve this issue, a modification in the import path within a specific file is required.

### Detailed Steps to Resolve
1. Navigate to the file located at `\fabric\client\fabric\fabric.py`.
2. In the first line of the file, locate the import statement for `utils`.
3. Modify the import statement from `import utils` to `import fabric.utils`.

After making this change, the `fabric` command executes successfully without encountering the module resolution error.

## Additional Notes
- This solution is specific to the described environment and versions. If the issue persists, please check for any updates or patches for the involved software.
- It's recommended to document any changes made to library files for future reference or in case of updates.

**Comment by danielmiessler** [comment]
Solved, thank you!
