### ISSUE TITLE
[Question]: What is the environment variable for specifying the default locations?

### ISSUE THREAD

**Issue by mwalid207** [danielmiessler/fabric#993]
### What is your question?

**After reading the documentation:**
I wasn't able to find any detailed **documentation** aside from the **README**, which doesn't mention **environment** variables or configuration options in depth.

I would like to specify a custom location for the default config folder rather than using the one in my home directory ($HOME/.config/fabric). Could you please clarify if there’s an environment variable or configuration setting to control this, and how to set it?

Thank you for your help!

**Comment by charlie-romeo** [comment]
Hi @mwalid207.  agree with you on the lack of documentation on this.  You could symlink the `$HOME/.config/fabric` to a directory of your choice and move the structure there.   Worth a try while you wait on an update from the Fabric team.  cheers

**Comment by johnconnor-sec** [comment]
If you go into the cli.go file you can change the fabricDb variable on line 28

**Comment by mwalid207** [comment]
**Thanks a lot**
