### ISSUE TITLE
[Bug]: new install command doesn't work

### ISSUE THREAD

**Issue by fonteijne** [danielmiessler/fabric#999]
### Goal
I wanted to update fabric to its latest version and used the command written in de readme.md
```go install -ldflags "-X main.version=$(git describe --tags --always)" github.com/danielmiessler/fabric@latest```
This results in:
```fatal: not a git repository (or any of the parent directories): .git```

I verified the old instruction still works
```go install github.com/danielmiessler/fabric@latest```

#### Important
I use the Fish shell, but the command also fails when switching to bash.

### Expected result
When running ```go install -ldflags "-X main.version=$(git describe --tags --always)" github.com/danielmiessler/fabric@latest``` I expect fabric to be updated.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
$ go install -ldflags "-X main.version=$(git describe --tags --always)" github.com/danielmiessler/fabric@latest                                                       

1758ms  vr 27 sep 10:20:55 2024
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by eugeis** [comment]
thank you for the issue.

I fixed the description it in the current release and added instruction how to get the latest release binaries or how to install from the source (like it was before)
